= Reference
:page-aliases: acb-components.adoc
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]


In Anypoint Code Builder, use components to build your integrations and implementations:

* <<builtin-connectors>>
* <<core-processors>>

Use MuleSoft commands from the Command Palette:

* xref:ref-acb-commands.adoc[]

Configure MuleSoft (*Mule*) settings, such as the EU or US cloud, and default Mule runtime and Java versions: 

* xref:ref-mule-settings.adoc[]

Configure Anypoint Code Builder proxy settings in Visual Studio Code (VS Code) to work with your network settings:

* xref:ref-proxy-settings.adoc[]

Understand how Maven settings files are identified and updated: 

* xref:ref-acb-maven.adoc[Maven Settings Files]

== Considerations for Generative AI Features in Anypoint Code Builder

Use the following information to understand how consumption billing and usage apply to generative AI features in Anypoint Code Builder.

=== Billing and Usage

* Generative AI features in Anypoint Code Builder consume only *Einstein Requests*.
* No other usage types apply:
** No Conversations
** No Flex Credits
** No Data Cloud usage or storage
* You can view Einstein Request consumption in your Digital Wallet.

=== Feature Limitations

* Generative AI features require internet connectivity and access to Einstein services.
* Outputs are AI-generated and might not always be accurate, complete, or appropriate for your specific use case. Always review before applying in production.
* Generative AI features do not store chat history or conversation transcripts.

//TODO: CONSIDER MAKING A CHILD PAGE:
[[builtin-connectors]]
== Built-In Connectors

include::anypoint-code-builder::partial$acb-component-info.adoc[tags="connectors-ref"]

[[core-processors]]
== Core Processors

include::anypoint-code-builder::partial$acb-component-info.adoc[tags="core-component-ref"]

== See Also

* xref:tutorials.adoc[]
