= MuleSoft Commands in Anypoint Code Builder

Anypoint Code Builder provides a set of commands through the Command Palette. 

// recommended change-> Add Fragment Dependency from Exchange
* `MuleSoft: Add Fragment dependency from Exchange`: +
TODO See xref:des-create-api-fragments.adoc[].

//not available
* `MuleSoft: API Console`: +
Opens the API Console for a design project. See xref:des-create-api-specs.adoc[].

* `MuleSoft: Deploy to CloudHub`: +
TODO See int-deploy-mule-apps.adoc[].

//IN IDE
* `MuleSoft: Design an API`: +
Opens a form for starting an API design project. You can also start an API design project from the UI. See xref:des-create-api-specs.adoc[].

* `MuleSoft: Develop an Integration`: +
Opens a form for starting an integration project. You can also start an integration project from the UI. See xref:int-create-integrations.adoc[].

* `MuleSoft: Export Mule Application Sources`: +
TODO -- LOOK FOR and see if can add to xref:int-export-mule-project.adoc[]. 

//not available
// recommended change-> Export Project to Mule Deployable JAR File
* `MuleSoft: Export Project to Mule Deployable Jar`: +
TODO -- LOOK FOR and see if can add to xref:int-export-mule-project.adoc[]. 

* `MuleSoft: Export Troubleshooting Information`: +
TODO See xref:troubleshooting.adoc[].

* `MuleSoft: Implement an API Specification`: +
TODO See xref:imp-implement-apis.adoc#scaffold-new-integration[]. 

// recommended change-> Implement This Local API
* `MuleSoft: Implement this local API`: +
TODO See xref:imp-implement-local-apis.adoc[].

* `MuleSoft: Import a Mule Project`: +
TODO See xref:int-import-mule-project.adoc[].

* `MuleSoft: Import a Project`: +
TODO See xref:int-import-mule-project.adoc[].

* `MuleSoft: Import API Specification from Design Center`: +
TODO See xref:des-create-api-specs.adoc[].

* `MuleSoft: Import Asset from Exchange`: +
TODO See examples in xref:int-create-integrations.adoc[], xref:imp-implement-apis.adoc[], and xref:int-import-dw-libraries.adoc[].


// "Login" is a noun. "Log in" is a verb.
// recommended change-> Log In to Anypoint Platform
* `MuleSoft: Login to Anypoint Platform`: +
TODO See xref:start-acb.adoc[].

* `MuleSoft: New Mule Configuration File`: +
TODO See xref:int-create-integrations.adoc[].

// "ACB" is not used, could be a legal naming issue
// recommended change-> Open Anypoint Code Builder Settings
* `MuleSoft: Open ACB Settings`: +
TODO: See PR: https://github.com/mulesoft/docs-code-builder/pull/256/files

//NOT YET:
//* `MuleSoft: Open Einstein`: +

// throws an error - reported on ACB Slack channel 011924
// recommended change-> "text editor" -> "Text Editor"
//* `MuleSoft: Open in text editor`: +

* `MuleSoft: Publish API Specification to Exchange`: +
TODO See xref:des-publish-api-spec-to-exchange.adoc[].

// recommended change-> "this local" -> "This Local"
* `MuleSoft: Re-scaffold this local API`: +
TODO See xref:imp-implement-local-apis.adoc[].

// not clear what this one does
//* `MuleSoft: Refresh DataSense Results`: +

// not clear what this one does
//* `MuleSoft: Refresh Projects`: +

* `MuleSoft: Save and Hot-deploy to Local Runtime`: +
TODO: See xref:int-debug-mule-apps.adoc[].

// not in the docs but looks like something we've opened in another way
// Always capitalize a product name. 
// recommended change-> Search in Anypoint Exchange
* `MuleSoft: Search in exchange`: +

// recommended change-> Set Mule Runtime Location
* `MuleSoft: Set Mule Runtime location`: +
Opens the `muleRuntimes` directory. 

//throws error
* `MuleSoft: Show Component in Canvas UI`: +

//doesn't show up in the IDE
* `MuleSoft: Show Mule Graphical Mode`: +

//IN IDE
// recommended change-> Show Project Dependencies
* `MuleSoft: Show Project dependencies`: +
Opens the *Project Dependencies* area of the Explorer view. 
The command `Explorer: Focus on Project Dependencies View` also opens this area. 

//IN IDE
* `MuleSoft: Show Welcome`: +
Opens the *Welcome* tab for Anypoint Code Builder.  

* `View: Show Anypoint Code Builder`: +
Opens the Anypoint Code Builder panel from the IDE.