= MuleSoft Commands in Anypoint Code Builder

Anypoint Code Builder provides a set of commands through the Command Palette. 

// recommended change-> Add Fragment Dependency from Exchange
* `MuleSoft: Add Fragment dependency from Exchange`
+
Add an API spec fragment from Exchange to the project directory so that you can include the fragment in your spec. For a procedure that uses this command, see xref:des-create-api-fragments.adoc#add-fragment-to-project[Add a Fragment from Exchange to Your Project].

//not available
* `MuleSoft: API Console`
+
Opens the API Console for a design project. See xref:des-create-api-specs.adoc[].

* `MuleSoft: Deploy to CloudHub`
+
Deploys an integration or implementation to CloudHub. See xref:int-deploy-mule-apps.adoc#deploy-an-app-to-cloudhub[Deploy an App to CloudHub].

* `MuleSoft: Design an API`
+
Opens a form for starting an API design project. You can also start an API design project from the UI. See xref:des-create-api-specs.adoc[].

* `MuleSoft: Develop an Integration`
+
Opens a form for starting an integration project. You can also start an integration project from the UI. See xref:int-create-integrations.adoc[].

* `MuleSoft: Export Mule Application Sources`
+
Export a sharable JAR file that contains a integration or implementation project. Both types are projects are Mule applications. See xref:int-export-mule-project.adoc#sharable[Export to a Shareable JAR File]. 

//not available
// recommended change-> Export Project to Mule Deployable JAR File
* `MuleSoft: Export Project to Mule Deployable Jar`
+
Export a Mule project with its compiled code and all dependencies into a distributable JAR file. See xref:int-export-mule-project.adoc#deployable[Export to a Deployable JAR File].

* `MuleSoft: Export Troubleshooting Information`
+
Export a compressed file that contains your project’s workspace folders, logs, and information about environment variables, CPU, operating system, and system properties. See xref:troubleshooting.adoc#export-troubleshooting-info[Export Troubleshooting Information].

* `MuleSoft: Implement an API Specification`
+
Import a supported API spec from Anypoint Exchange, and scaffold the spec into an implementation project in the IDE. See xref:imp-implement-apis.adoc#scaffold-new-integration[Scaffold an API and Create an Integration Project].

// recommended change-> Implement This Local API
* `MuleSoft: Implement this local API`
+
Scaffold an API spec project located within the IDE into an implementation project. See xref:imp-implement-local-apis.adoc[Scaffold an API Spec into a New Implementation Project]. 

* `MuleSoft: Import a Mule Project`
+
TODO See xref:int-import-mule-project.adoc[].

* `MuleSoft: Import a Project`
+
TODO See xref:int-import-mule-project.adoc[].

* `MuleSoft: Import API Specification from Design Center`
+
TODO See xref:des-create-api-specs.adoc[].

* `MuleSoft: Import Asset from Exchange`
+
TODO See examples in xref:int-create-integrations.adoc[], xref:imp-implement-apis.adoc[], and xref:int-import-dw-libraries.adoc[].


// "Login" is a noun. "Log in" is a verb.
// recommended change-> Log In to Anypoint Platform
* `MuleSoft: Login to Anypoint Platform`
+
TODO See xref:start-acb.adoc[].

* `MuleSoft: New Mule Configuration File`
+
TODO See xref:int-create-integrations.adoc[].

// "ACB" is not used, could be a legal naming issue
// recommended change-> Open Anypoint Code Builder Settings
* `MuleSoft: Open ACB Settings`
+
TODO: See PR: https://github.com/mulesoft/docs-code-builder/pull/256/files

//
//NOT YET:
//* `MuleSoft: Open Einstein`
//+
//
// throws an error - reported on ACB Slack channel 011924
// recommended change-> "text editor" -> "Text Editor"
//* `MuleSoft: Open in text editor`
//

* `MuleSoft: Publish API Specification to Exchange`
+
TODO See xref:des-publish-api-spec-to-exchange.adoc[].

// recommended change-> "this local" -> "This Local"
* `MuleSoft: Re-scaffold this local API`
+
TODO See xref:imp-implement-local-apis.adoc[].

//
// not clear what this one does
//* `MuleSoft: Refresh DataSense Results`
//
// not clear what this one does
//* `MuleSoft: Refresh Projects`
//

* `MuleSoft: Save and Hot-deploy to Local Runtime`
+
TODO: See xref:int-debug-mule-apps.adoc[].

// not in the docs but looks like something we've opened in another way
// Always capitalize a product name. 
// recommended change-> Search in Anypoint Exchange
* `MuleSoft: Search in exchange`
+

// recommended change-> Set Mule Runtime Location
* `MuleSoft: Set Mule Runtime location`
+
Opens the `muleRuntimes` directory. 

//throws error
* `MuleSoft: Show Component in Canvas UI`
+

//doesn't show up in the IDE
* `MuleSoft: Show Mule Graphical Mode`
+

//IN IDE
// recommended change-> Show Project Dependencies
* `MuleSoft: Show Project dependencies`
+
Opens the *Project Dependencies* area of the Explorer view. 
The command `Explorer: Focus on Project Dependencies View` also opens this area. 

//IN IDE
* `MuleSoft: Show Welcome`
+
Opens the *Welcome* tab for Anypoint Code Builder.  

* `View: Show Anypoint Code Builder`
+
Opens the Anypoint Code Builder panel from the IDE.