= Add Request and Response Details

You can define request and response details for your API specification.


== Before You Begin

* Ensure you set up your MuleSoft environment. +
See xref:setup.adoc[] for more information.
* You created a basic structure for your API specification. +
See xref:design-api-specification.adoc[].

== Add Data Types and Example Fragments from Exchange

. Open the Command Palette (`ctrl/cmd + shift + P`) and type _MuleSoft: Add fragment dependency from Exchange_.
. Add the assets *Training: American Flight Data Type* and *Training: American Flights Example*.
. When prompted, select the latest version of each fragment.
. The status bar shows a *Dependencies successfully added* message.
. In the Package Explorer, you can see both API fragments that you imported:
* *AmericanFlightDataType.raml* defines an object corresponding to the definition of a flight.
* *AmericanFlightsExample.raml* defines the example of data that the flights API returns.

== Add Data Type to your API Specification

Use your imported fragments as types for your API specification:

. Open the *american-flight-api.raml* file in the editor tab.
. In top of the `flights/` resource, add a `types` element, go to a new line and press `tab` to add an indentation
. Add a type named `AmericanFlight:`:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
  post:

  /{ID}:
    get:
--
. Add an `!include` directive and press `ctrl/cmd + spacebar` to bring up the auto-complete options.
. Select `AmericanFlightsDataType.raml`.
. Add a new element under `queryParameters`, press `ctrl/cmd + spacebar` to bring up the auto-complete options, and add the elements:
* `responses`
* `200`
* `body`
* `application/json`
* `type`
. For the `type` element, press `ctrl/cmd + spacebar` and select the `AmericanFlight` type.
. Add `[]` at the end of your `AmericanFlight` type to define it as an array.
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: AmericanFlight[]
  post:

  /{ID}:
    get:
--

== Add an Example Response

Create a new `example:` element for the `response` element for your `/flights` resource:

. Add a new resource at the same level of your `type` response, press `ctrl/cmd + spacebar` to bring up the auto-complete options, and select `examples`.
. Under examples, add an indentation, press `ctrl/cmd + spacebar`, and select *output*.
. Add an `!include` directive and press `ctrl/cmd + spacebar` to bring up the auto-complete options.
. Select `AmericanFlightsExample.raml` as the reference for your example.


== Define a Response in a New Folder

You can define your responses in a folder within your project:

. In the Project Explorer, under your root folder, create a new sub-folder and name it *examples*.
. In the *examples* folder, create a new file named `AmericanFlightExample.raml`.
. Open the file and add the following example:
+
[source,raml,linenums]
--
#%RAML 1.0 NamedExample
value:
    ID: 1
    code: ER38sd
    price: 400
    departureDate: 2017/07/26
    origin: CLE
    destination: SFO
    emptySeats: 0
    plane:
      type: Boeing 737
      totalSeats: 150
--
. Go back to your *american-flights-api.raml* file.
. Create a new set of elements for response under your `/{ID}/get` resource:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: AmericanFlight[]
  post:

  /{ID}:
    get:
      body:
        application/json:
          type: AmericanFlight
          examples:
            output: !include: examples/AmericanFlightExample.raml //<1>
--
<1> New example defined in your `examples` folder.


== Define a Request Example

Similar to defining a response for a method, you can define a request example:

. Specify that a request to the `/flights:post` method requires an `AmericanFlight` object:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: AmericanFlight[]
  post:
    body:
      application/json:
        type: AmericanFlight //<1>

  /{ID}:
    get:
      body:
        application/json:
          type: AmericanFlight
          examples:
            output: !include: examples/AmericanFlightExample.raml
--
<1> `AmericanFlight` is defined as the type for the `post` method.
. Under your `examples` folder, create a new example file named `AmericanFlightNoIDExample.raml`.
. Add the following information to your example file:
+
[source,raml,linenums]
--
#%RAML 1.0 NamedExample
value:
    code: ER38sd
    price: 400
    departureDate: 2017/07/26
    origin: CLE
    destination: SFO
    emptySeats: 0
    plane:
      type: Boeing 737
      totalSeats: 150
--
+
Notice that the ID parameter is missing since you don't have the flight ID when creating a new flight record.
. In your *american-flights-api.raml* file, define the response for your `post` method:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: AmericanFlight[]
  post:
    body:
      application/json:
        type: AmericanFlight
        examples:
          input: !include examples/AmericanFlightNoIDExample.raml //<1>

  /{ID}:
    get:
      body:
        application/json:
          type: AmericanFlight
          examples:
            output: !include: examples/AmericanFlightExample.raml
--
<1> Define the example file you created earlier as an example for your `/{ID}:post` method.

Additionally, you can define the type of response of your `post` method for your `/flights` resource:

. Add a new line under your `/flights:post` method and indent it at the same level as your `body:` element.
. Press `ctrl/cmd + spacebar` to bring up the auto-complete options to create a 201 response:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

types:
  AmericanFlight:

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            type: AmericanFlight[]
  post:
    body:
      application/json:
        type: AmericanFlight
        examples:
          input: !include examples/AmericanFlightNoIDExample.raml
    responses:
      201: //<1>
        body:
          application/json:
            example:

  /{ID}:
    get:
      body:
        application/json:
          type: AmericanFlight
          examples:
            output: !include: examples/AmericanFlightExample.raml
--
<1> Create a 201 response with the required `body` > `application/json` > `example` elements.
. As an example, define a custom message: *Flight added (but not really)*:
+
[source,raml,linenums]
--
responses:
  201:
    body:
      application/json:
        example:
          message: Flight added (but not really)
--


== See Also

* xref:test-api-specification.adoc[Test an API Specification Using Mocking Service]
