= Build Agent Networks in a CI/CD Environment

If you run operations within a CI/CD environment, you can use Anypoint CLI's Agent Fabric plugin to set up, create, build, publish, and deploy agent networks. For more information, see link:https://www.npmjs.com/package/anypoint-cli-agent-fabric-plugin[Anypoint CLI Agent Fabric Plugin].

== Before You Begin

Make sure you meet the prerequisites for this task. For prerequisites, see xref:af-get-started.adoc[].

Install the Anypoint CLI Agent Fabric plugin by running this command in a terminal window: +
`npm i anypoint-cli-agent-fabric-plugin`

=== Authentication

You can authenticate to Anypoint Platform through the command line by running the `anypoint-cli-agent-fabric-plugin` command with a combination of parameters.

Or, you can set a combination of environment variables before running the `anypoint-cli-agent-fabric-plugin` command. For more information, see link:https://docs.mulesoft.com/anypoint-cli/latest/auth#command-line-parameters[Command-Line Parameters and Environment Variables].

Set configuration file authentication using a client ID and client secret from your connected app.

Add authentication values to the configuration file using these commands.

----
$ anypoint-cli-agent-fabric-plugin conf client_id myClientID

$ anypoint-cli-agent-fabric-plugin conf client_secret myClientSecret

$ anypoint-cli-agent-fabric-plugin conf organization myOrgId
----

For more information, see xref:anypoint-cli::auth.adoc[].

=== Create a Target Space for Your Environment

To deploy an agent network, you need a private space on CloudHub 2.0 or a deployment target on Anypoint Runtime Fabric. See xref:af-get-started.adoc#setup-space[].

After you create a target space, set up the ingress and egress gateways for deployment, if you haven't already done so. See xref:af-get-started.adoc#setup-gateways[].

== CLI for Agent Fabric Plugin Reference

Use these commands to set up gateways and author, publish, and deploy agent network projects.

include::anypoint-cli::partial$agent-fabric.adoc[tag=summary]

include::anypoint-cli::partial$agent-fabric.adoc[tag=commands]
