= Get Started with Agent Networks

Setting up Anypoint Code Builder, permissions, access, and gateways ensures that you can create agent networks quickly and easily.

== Before You Begin

Before you get started, review these prerequisites.

=== Anypoint Platform Requirements and Permissions

[cols="1,1"]
|===
|Anypoint Platform Component |Required Permissions

|Runtime Manager
|Manage Servers  Create Applications

|Anypoint Code Builder
|Anypoint Code Builder Developer Mule Developer Generative AI User

|Anypoint Design Center
|Design Center Developer

|API Manager
|Deploy API Proxies Manage Policies

|Exchange
|Exchange Contributor

|Access Management
|xref:access-management::enabling-agentforce.adoc[Enable Agentforce]

|Flex Gateway
|Runtime Manager: Manage Servers Runtime Manager: Read Servers General: Usage Viewer

|CloudHub 2.0 or Runtime Fabric (limited availability)
|xref:runtime-fabric::limitations-self.adoc[Runtime Fabric permissions] xref:cloudhub-2::ps-assign-permissions.adoc[CloudHub 2.0 permissions]
|===

=== Additional Requirements

* Your Anypoint Platform credentials
* xref:anypoint-code-builder::start-acb.adoc[Anypoint Code Builder desktop]

  Allowlist Anypoint Code Builder URLs. For more information, see xref:anypoint-code-builder::urls-to-allow.adoc[Allow URLs for Anypoint Code Builder].

* https://learn.microsoft.com/en-us/powershell/scripting/install/install-powershell-on-windows?view=powershell-7.5&viewFallbackFrom=powershell-7.3[PowerShell] (For Windows operating systems only).
* A tenant relationship established with a trusted Salesforce organization

=== CLI Requirements (Optional)

If you're using the Anypoint CLI to create agent network projects, ensure you meet these requirements.

* Node 20 (v20.19.4) or later. See http://Nodejs.org[Nodejs.org].
* Java 17 or later. Set the `JAVA_HOME` environment variable.
* https://docs.mulesoft.com/anypoint-code-builder/af-build-agent-networks-in-a-ci-cd-environment[Anypoint CLI Fabric Plugin]

== Task Overview

=== Step 1: Set Up Your Agent Network

. Use Anypoint Runtime Manager to set up a private or target space in CloudHub 2.0 or Runtime Fabric.

  See xref:anypoint-code-builder::af-get-started.adoc#set-up-the-private-or-target-space-for-your-environment[Set Up the Private or Target Space for Your Environment].
. Set up Ingress and egress gateways for the private or target space.
  * If using Anypoint Code Builder, see xref:anypoint-code-builder::af-get-started.adoc#set-up-agent-network-gateways-for-the-private-or-target-space[Set Up Agent Network Gateways for the Private or Target Space].
  * If using the Anypoint CLI, see the xref:anypoint-cli::agent-fabric.adoc#agent-network-setup-gateways[anypoint-cli-agent-fabric-plugin agent-network setup gateways command].

=== Step 2: Create a Project

Now you're ready to create an agent network project. Choose one of the following methods:

* xref:af-create-agent-network.adoc#create-a-network-using-the-mulesoft-dev-agent[]
* xref:af-create-agent-network.adoc#create-a-network-using-anypoint-code-builder[]
* xref:af-build-agent-networks-in-a-ci-cd-environment.adoc#agent-network-project-create[Create a Network Using the Anypoint CLI]

=== Step 3: Define Your Agent Network Specification

After you create your agent network project, configure `agent-network.yaml` and `exchange.json` to reflect the structure of your network.

* xref:define-your-agent-network-specification.adoc#define-a-network-using-the-mulesoft-dev-agent[]
* xref:define-your-agent-network-specification.adoc#define-a-network-using-anypoint-code-builder-or-ide[]

=== Step 4: Publish Your Agent Network Assets [[step-4-publish-your-agent-network-assets]]

Build and publish your agent network project as Anypoint Exchange assets. When you publish, an asset is created for each broker, agent, and MCP server that's in your agent network.

* xref:af-publish-agent-network-assets.adoc#publish-your-network-using-the-muleSoft-dev-agent[]
* xref:af-publish-agent-network-assets.adoc#publish-your-network-using-anypoint-code-builder[]
* xref:xref:af-build-agent-networks-in-a-ci-cd-environment.adoc#agent-network-project-publish[Publish Your Network Using the Anypoint CLI]

=== Step 5: Deploy Your Agent Network Instances

Deploy your agent network instance to a deployment target. You can deploy to a CloudHub 2.0 private space or to a Runtime Fabric (limited availability).

* xref:af-deploy-agent-network-targets.adoc#deploy-your-network-using-the-mulesoft-dev-agent[]
* xref:af-deploy-agent-network-targets.adoc#deploy-your-network-using-anypoint-code-builders[]
* xref:xref:af-build-agent-networks-in-a-ci-cd-environment.adoc#agent-network-project-deploy[Deploy Your Network Using the Anypoint CLI]

== Set Up the Private or Target Space for Your Environment

To deploy an agent network, you need a target space on either CloudHub 2.0 or Anypoint Runtime Fabric.

If you already have a private space configured in CloudHub 2.0, you can associate it with the business groups and environments where you'll deploy your agent network.

Depending on your deployment target:

* CloudHub 2.0:
+
. Create a private space in CloudHub 2.0 or verify that you can access an existing private space.
+
To create a private space, see xref:cloudhub-2::ps-create-configure.adoc[].
We recommend naming the private space `agent-network-space`.
. xref:cloudhub-2::ps-config-env.adoc[Associate the new or existing private space with the business groups and environments] where you plan to deploy your agent network.
+
You must complete this step so that the private space appears as a valid deployment target in Anypoint Code Builder and Anypoint CLI.
* Runtime Fabric (limited availability):
+
Create a target space for Runtime Fabric.
+
For information about Runtime Fabric deployments, see xref:gateway::flex-gateway-managed-set-up.adoc#rtf[Managed Flex Gateway on Runtime Fabric].

== Set Up Agent Network Gateways for the Private or Target Space

After you have a target space, use the `MuleSoft: Set Up Agent Network Gateways` command to create the ingress and egress gateways required for deployment in either CloudHub 2.0 or Runtime Fabric. 

For agent networks, you must have at least one small Managed Flex Gateway and one large Managed Flex Gateway in your environment.
For more information about gateways, see xref:gateway::flex-architecture-basic-deployments.adoc[].

For more information about Runtime Fabric deployments, see xref:gateway::flex-gateway-managed-set-up.adoc#rtf[Managed Flex Gateway on Runtime Fabric].

. In Anypoint Code Builder, from the Command Palette, run the command *MuleSoft: Set Up Agent Network Gateways*.
+
If you didn't associate the private space with the business group and environment, you see an error.
. If you're not logged in, log in to your Anypoint Platform account.
. Select the business group, environment, and private or target space.
+
The `MuleSoft: Set Up Agent Network Gateways` command creates these gateways in the private or target space you select:
+
* agent-network-ingress-gw (with public and internal endpoint)
* agent-network-egress-gw (with internal endpoint only)

If the gateways already exist in the selected private or target space, the command doesn’t recreate them. 

== See Also

* xref:af-create-agent-network.adoc[]
