[[get-started]]
= Get Started with Agent Networks

include::anypoint-code-builder::partial$af-shared.adoc[tags=get-started]

[[setup-space]]
== Set Up the Private Space or Deployment Target for Your Environment

To deploy an agent network, you need a private space on  CloudHub 2.0 or a deployment target on Anypoint Runtime Fabric.

If you already have a private space configured in CloudHub 2.0, you can associate it with the business groups and environments where you'll deploy your agent network.

Depending on your deployment target:

* CloudHub 2.0:
+
. Create a private space in CloudHub 2.0 or verify that you can access an existing private space.
+
To create a private space, see xref:cloudhub-2::ps-create-configure.adoc[].
We recommend naming the private space `agent-network-space`.
. xref:cloudhub-2::ps-config-env.adoc[Associate the new or existing private space with the business groups and environments] where you plan to deploy your agent network.
+
You must complete this step so that the private space appears as a valid deployment target in Anypoint Code Builder and Anypoint CLI.
* Runtime Fabric (limited availability):
+
Create a target space for Runtime Fabric.
+
For information about Runtime Fabric deployments, see xref:gateway::flex-gateway-managed-set-up.adoc#rtf[Managed Flex Gateway on Runtime Fabric].

[[setup-gateways]]
== Set Up Agent Network Gateways for the Private Space or Deployment Target

After you have a target space, use the `MuleSoft: Set Up Agent Network Gateways` command to create the ingress and egress gateways required for deployment in either CloudHub 2.0 or Runtime Fabric. 

For agent networks, you must have at least one small Managed Flex Gateway and one large Managed Flex Gateway in your environment.
For more information about gateways, see xref:gateway::flex-architecture-basic-deployments.adoc[].

For more information about Runtime Fabric deployments, see xref:gateway::flex-gateway-managed-set-up.adoc#rtf[Managed Flex Gateway on Runtime Fabric].

. In Anypoint Code Builder, from the Command Palette, run the command *MuleSoft: Set Up Agent Network Gateways*.
+
If you didn't associate the private space with the business group and environment, you see an error.
. If you're not logged in, log in to your Anypoint Platform account.
. Select the business group, environment, and private or target space.
+
The `MuleSoft: Set Up Agent Network Gateways` command creates these gateways in the private or target space you select:
+
* agent-network-ingress-gw (with public and internal endpoint)
* agent-network-egress-gw (with internal endpoint only)

If the gateways already exist in the selected private or target space, the command doesn’t recreate them. 

[[see-also]]
== See Also

* xref:af-create-agent-network.adoc[]
