= MuleSoft for Agentforce: Topic Center Overview

Use MuleSoft for Agentforce:Topic Center (Topic Center) to enable API specifications for topics, which can then be synced in API Catalog in Salesforce and consumed in Agent Builder. Topics are bundles of actions and sets of instructions Agentforce agents use to complete tasks. Actions are tasks that the agent can do, and instructions help the agent understand how to use actions. 

Topic Center automatically makes all of your API operations available as agent actions. Agents perform common tasks autonomously, such as updating records, searching and summarizing data, and securely taking action in various systems. Agents are reusable across any set of topics. 

With Topic Center, you can create instructions for an agent on the way to use an API and automatically transform the API operations to invocable-action based agent actions. 

An agent can have multiple topics. 

Devs develop the API

Visual editor that allows an dev to build agents into the API spec. Apply governance to the API spec. Publishing pipeline through API Catalog. 

Makes agents available to admins OOTB

When API is published, agent actions can be auto generated. Admin goes to Agentforce and adds the available topic. 
API catalog provides centralized discovery of all types of APIs. 

// Add API Catalog to overview for Feb 14th release

== See Also

* xref:https://help.salesforce.com/s/articleView?id=sf.copilot_overview.htm&type=5[What are Agents]
* xref:https://help.salesforce.com/s/articleView?id=sf.copilot_building_blocks.htm&type=5[The Building Blocks of Agents]
* xref:https://help.salesforce.com/s/articleView?id=sf.copilot_topics.htm&type=5[Agent Topics]
