= MuleSoft for Agentforce: Topic Center Overview

Use MuleSoft for Agentforce: Topic Center (also known as Topic Center) to enable API specifications for topics and agents, which can then be synced to API Catalog in Salesforce. You can then augment agent functionality by assigning topics to Agentforce agents in Agent Builder.  

Use the Topic Center visual editor to:

* Enable the API specifications for topics and agents.
* Apply governance rules to validate that your API is ready to generate agent actions and topics in Salesforce.
* Add metadata to make your topic and action-enabled APIs available in Salesforce using Salesforce API Catalog.

Topics are bundles of actions and sets of instructions Agentforce agents use to complete tasks. Actions are tasks that the agent can do, and instructions help the agent understand how to use actions. 

Topic Center automatically makes all of your API operations available as agent actions and topics. Agents perform common tasks autonomously, such as updating records, searching and summarizing data, and securely taking action in various systems. Agents are reusable across any set of topics and can contain multiple topics. 


== See Also

* https://help.salesforce.com/s/articleView?id=sf.copilot_overview.htm&type=5[What are Agents]
* https://help.salesforce.com/s/articleView?id=sf.copilot_building_blocks.htm&type=5[The Building Blocks of Agents]
* https://help.salesforce.com/s/articleView?id=sf.copilot_topics.htm&type=5[Agent Topics]
