= Configure your MuleSoft Environment

Anypoint Code Builder enables you to develop directly on your Anypoint Platform environment.

== Before You Begin

* Ensure you have an Anypoint Platform account.
* Multi-Factor Authentication (MFA) is not supported in this beta release. If your organization uses MFA, you must disable to be able to connect Anypoint Code Builder to your platform organization.

== Log in to Your Anypoint Platform Account

. Open the command palette (`⇧⌘P`) and type *login*.
. Select the *MuleSoft: Login to Anypoint Platform* from the list results.
. Select *Allow* when prompted to sign-in to the platform.
. Sign in using your Anypoint Platform credentials.

To verify you are logged in, ensure that your username shows in the bottom right corner of Anypoint Code Builder.

== Configure the Default Ouput Panel

The output panel displays status messages for various features in Anypoint Code Builder. You must configure your output panel to display information from the Anypoint Code Builder extensions:

. From the menu, select *View* > *Output*.
. In the right top side of the ouput panel, click on the drop-down menu and select *Mule DX Server*.

Anypoint Code Builder now displays information related to the Mule Extensions logs.
