= Connect to EU Cloud

Anypoint Code Builder is also available for EU control plane users.

MuleSoft hosts a version of the Anypoint Platform control plane entirely within the EU (Frankfurt or Dublin data centers). This enables you to deploy and manage your APIs, applications, and related data entirely within the European Union. This includes data and metadata about your MuleSoft implementation.

In addition to EU Cloud, deployment targets for MuleSoft managed runtimes are also hosted in the EU data center. Having both the control and runtime planes entirely within the EU enables you to more effectively meet emerging regulatory requirements.

[NOTE]
Anypoint Platform account data is not shared between the US and EU Cloud. Even if you have an account in US Cloud, you must create a new account in EU Cloud.

See xref:hosting-home::index.adoc[] for more information.

== Access Code Builder from EU Cloud

To access Code Builder from EU Cloud:

. Navigate to `+eu1.anypoint.mulesoft.com+`.
. If you don't have an Anypoint Platform account in EU Cloud, click *Sign Up*.
.. Enter your personal information. All fields are required.
.. Choose a username and a password.
.. Click *Create Account*.
. Enter your username and password, then click *Sign In*.
. Select *Anypoint Code Builder*.

== See Also

* xref:eu-control-plane::index.adoc[]
