= Access Code Builder From EU Cloud

Anypoint Code Builder is available for EU control plane users.

MuleSoft hosts a version of the Anypoint Platform control plane entirely within the EU (Dublin) data centers. This data center enables you to deploy and manage your APIs, applications, and related data entirely within the European Union, including data and metadata about your MuleSoft implementation.

In addition to EU Cloud, MuleSoft hosts deployment targets for managed runtimes in the EU data center. Having both the control and runtime planes entirely within the EU helps your organization meet emerging regulatory requirements.

[NOTE]
Anypoint Platform does not share account data between the US and EU Cloud. Even if you have an account in US Cloud, you must create a new account in EU Cloud.

See xref:hosting-home::index.adoc[] for more information.

== Access Code Builder from EU Cloud

To access Code Builder from EU Cloud:

. Navigate to `+eu1.anypoint.mulesoft.com+`.
. If you don't have an Anypoint Platform account in EU Cloud, click *Sign Up*.
.. Enter your personal information. All fields are required.
.. Choose a username and a password.
.. Click *Create Account*.
. Enter your username and password, then click *Sign In*.
. Select *Anypoint Code Builder*.

After loading Code Builder for the first time, continue by running the setup instructions. See xref:setup.adoc[]

== See Also

* xref:eu-control-plane::index.adoc[]
