= Create XML Snippets

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

Before creating an integration in a Mule application, define user snippets. Snippets are reusable code patterns that you can insert into the configuration XML for your Mule application. 

In addition to providing built-in snippets, Anypoint Code Builder enables you to configure your own user snippets in a JSON format.  Anypoint Code Builder converts the snippets to XML when you add them to the configuration XML of your Mule application.

The XML generated from the snippets helps you configure your applications more quickly and consistently than you can with the basic XML elements available from the configuration XML. For example:

* Built-in Logger snippet:
+
[source,XML]
----
<logger level="" message='$2' doc:name="Logger" doc:id="xgsmzm" />
----

* Basic Logger XML:
+
[source,XML]
----
<logger doc:name="Logger" doc:id="xlkhkz" />
----

To configure the Logger snippet in a Mule application, you specify the values to the attributes defined in the snippet. To configure the basic Logger XML, you must provide the attributes and values. For more information, see xref:work-with-code-snippets.adoc[].

== Before You Begin

Set up your environment. See xref:setup.adoc[].

== Open the User Snippets File

Define user snippets in the `mule-xml.json` file,  in which you specify snippets for connector operations, Core processors, and other elements in the XML configuration file for your Mule applications.  

. In Anypoint Code Builder, navigate to *Configure User Snippets*:

* In the desktop IDE, navigate to *Code* > *Settings* > *Configure User Snippets*.
* In the web IDE, navigate to *File* > *Preferences* > *Configure User Snippets*.
* In either IDE, open the Command Palette by pressing Ctrl+Shift+p (Windows) or Cmd+Shift+p (Mac), and provide the following command:
+
[source,command]
----
Snippets: Configure User Snippets
----
. In the *Select Snippets File or Create Snippets* field that opens, provide:
+
[source,command]
----
mule-xml.json (Mule XML)
----
. If the file has no configurations, `mule-xml.json` provides comments within curly braces:
+
[source,json]
--
{
	// Place your snippets for mule-xml here. Each snippet is defined under a snippet name and has a prefix, body and
	// description. The prefix is what is used to trigger the snippet and the body will be expanded and inserted. Possible variables are:
	// $1, $2 for tab stops, $0 for the final cursor position, and ${1:label}, ${2:another} for placeholders. Placeholders with the
	// same ids are connected.
	// Example:
	// "Print to console": {
	// 	"prefix": "log",
	// 	"body": [
	// 		"console.log('$1');",
	// 		"$2"
	// 	],
	// 	"description": "Log output to console"
	// }
}
--
. Add this snippet code to the file: 
+
[source,json]
--
{
	"Mule Flow": {
		"prefix": "muledx:flow",
		"body": [
		  "<flow name=\"${1:$TM_FILENAME_BASE-Flow}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\">",
		   "",
		  "</flow>"
		]
	 },
	"HTTP Listener Config": {
		"prefix": "muledx:http-listener-config",
		"body": [
		  "<http:listener-config name=\"${1:httpListenerConfig}\" doc:name=\"${2:Listener Config}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\">",
		   "  <http:listener-connection host=\"${3:Host}\" port=\"${4:Port}\"/>",
		  "</http:listener-config>"
		]
	 },
	 "HTTP Listener": {
		"prefix": "muledx:http-listener",
		"body": [
		  "<http:listener path=\"/${1:path}\" config-ref=\"${2:httpListenerConfig}\" doc:name=\"${3:Listener}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\"/>"
		]
	 },
	 "Set Payload": {
		"prefix": "muledx:set-payload",
		"body": [
		  "<set-payload value=\"${1:#[payload]}\" doc:name=\"${2:Set Payload}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\"/>"
		]
	 },
	 "Set Variable": {
		"prefix": "muledx:set-variable",
		"body": [
		  "<set-variable variableName=\"${1:name}\" value=\"${2:#[payload]}\" doc:name=\"${3:Set Variable}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\"/>"
		]
	 },
	 "Logger": {
		"prefix": "muledx:logger",
		"body": [
		  "<logger level=\"INFO\" message=\"${1:#[payload]}\" doc:name=\"${2:Logger}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\"/>"
		]
	 },
	 "Database Config - MySQL": {
		"prefix": "muledx:db-config-mysql",
	  "body": [
		 "<db:config name=\"${1:DatabaseConfig}\" doc:name=\"${2:mySQL DB}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\">",
		 "  <db:my-sql-connection host=\"${3:Host}\" port=\"${4:Port}\" user=\"${5:Username}\" password=\"${6:Password}\" database=\"${7:DatabaseName}\" />",
		 "</db:config>"
	  ]
	 },
	 "Database Select": {
		"prefix": "muledx:db-select",
	  "body": [
		 "<db:select config-ref=\"${1:DatabaseConfigRef}\" doc:name=\"${2:Select}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\">",
			"  <db:sql>",
			"    <![CDATA[${3:SQL}]]>",
			"  </db:sql>",
		 "</db:select>"
	  ]
	 },
	 "Transform Message": {
		"prefix": "muledx:transform-message",
		"body": [
		 "<ee:transform doc:name=\"${1:Transform Message}\" doc:id=\"$RANDOM_HEX-$RANDOM_HEX\">",
		 "  <ee:message>",
		   "    <ee:set-payload>",
		   "      <![CDATA[${2:DataWeave}]]>",
		   "    </ee:set-payload>",
		   "  </ee:message>",
		   "</ee:transform>"
		]
	 }
  }
--
. Proceed to xref:create-basic-integration.adoc[Create a Basic Integration]. 