= Governing APIs
:page-deployment-options: cloud-ide, desktop-ide
// :page-aliases: 

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

Use API governance rulesets in your projects to run API validations and fix validation issues in Anypoint Code Builder.

Anypoint API Governance is a component of Anypoint Platform that enables you to apply governance rules to your APIs as part of the API lifecycle.
For more information, see xref:api-governance::index.adoc[].

//TODO_TODO: order of sections TBD

== Identify and Fix Validation Issues

TODO_TOPIC: Check conformance status of project 

[[add-rulesets]]
== Add Rulesets to a Project

TODO_TOPIC: Select and add one or more rulesets from Exchange as project dependencies to the project (instead of adding one by one)

[[run-validations]]
== Run Validations

TODO_TOPIC: JTBDs: Run & re-run validations: Select or disable individual rulesets/rules to run & re-run (after attempted fixes) one or more validations (see PRD for more detail)

[[monitor-validations]]
== Monitor the Validation Process

TODO_TOPIC:  JTBD: Monitor progress of validation (consider entire workflow that could include other JTBDs)
* TODO_TBD: See validation progress of rulesets (what has failed or passed)
* TODO_TBD: See time left to complete validation and get full report
* TODO_TBD: See how much time to validate a given rule/ruleset (for potentially disabling time-consuming ones)

[[troubleshoot-validations]]
== Troubleshoot Rule Failures

TODO_TITLE: Check topic title

TODO_TOPIC: Check trace to get info on rule failures (and clues about how to fix)
Navigate from rule validation failure to node generating failure (goal: to find and fix validation failure more quickly)
