= Design an API Specification

You can design a new RAML or OAS API specification using Anypoint Code Builder.

Supported OAS and RAML versions are:

* RAML 1.0
* RAML 0.8
* OAS 2.0 (JSON)
* OAS 2.0 (YAML)
* OAS 3.0 (JSON)
* OAS 3.0 (YAML)

== Before You Begin

* Ensure you set up your MuleSoft environment. +
See xref:setup.adoc[] for more information.

== Create a New API Specification

To create a new API specification:

. Open the Command Palette type (`ctrl/cmd + shift + P`) and type _design_.
. Select *MuleSoft: Design an API* from the list of results.
. Type the name of your API specification: +
* `*American Flights API*`
. Type a description of your API.
. Select *New API Specification*.
. Select *RAML 1.0*.
. Select the location of your API specification.

The project explorer now shows you your American Flights API folder with an `american-flights-api.raml` file open in the editor.

== Add a RAML Resource

Start adding resources to your API specification:

. In the editor, add your first resource called *flights*:
+
[source,raml,linenums]
--
#%RAML 1.0
title: American Flights API

/flights:
--
. Review your new resource using API Console by clicking the API Console icon on the top right of your screen.

== Add a RAML Method

With one resource created, you can add a methods to it using auto-complete:

. Under `/flights`, select `enter` to go to a new line and `tab` to indent.
. Select `ctrl/cmd + spacebar` to see all the avaialble options.
. Select *get*.

You can add further methods by going to a new line and keep using the auto-complete feature. For example, you can also add the *post* method.

Both methods now also show on API Console.
