= Mulesoft Dev Agent Example Prompts

Use these example prompts to guide MuleSoft Dev Agent in completing common tasks. Customize the values to match your project or environment.


== Application Deployment and Projects

To deploy an app to CloudHub or Runtime Fabric:

Deploy this app.

To create an implementation project:

Create a Mule project that creates an order in NetSuite every time an opportunity in Salesforce is updated to the ‘Closed Won’ stage.

To deploy an implementation application:

Deploy Mule application in current project. Deploy with high security, high availability, and performance optimized settings.

To modify an existing application:

Update this application so that it [business requirements].


== Exchange Asset Management

To create an asset in Exchange:

I would like to create an asset of [this type] in Exchange with this [name].

To search for an asset in Exchange:

Find [asset name].

To search for an asset within a specific organization:

Find [asset name] in [organization name].


== API Instances

To create an instance and secure it:

Create an instance for the [application_name] and apply the rate limiting policy to that instance.


== Custom Metadata

To set custom metadata that uses sample data:

Can you help me define custom metadata on the following component? This is how the sample data looks:  
[sample_data]

To set custom metadata using a file:

Can you define custom metadata using the sample file below and attach it to [processor_name]?  
@[path_to_file]


== Agent Network Operations

To create an Agent Network:

Create an Agent Network for onboarding employees.

To publish an Agent Network:

Publish this Agent Network project to Exchange.

To deploy an Agent Network:

Deploy this Agent Network project.
