= Develop an Integration

You can use Anypoint Code Builder to build an integration. Developing an integration means that you create a Mule application to orchestrate chains of operations that can be reused or changed as systems or business needs change. Developing an integration with Anypoint Code Builder involves moving beyond patterns into a service-based framework, where you wrap multiple components with sources to decouple them from protocols and routing requirements.

When you build an integration with Anypoint Code Builder you enable multiple services to work as one. Some common use cases are:

* Scheduling data processing
* Connecting cloud and on-premise applications
* Event processing, where multiple services must be composed and must operate simultaneously

The following section teaches you how to create a basic integration, add dependencies and connectors to your Mule application, use Dataweave to transform the payload of your response.

Start by xref:create-xml-snippets.adoc[Creating a User Snippet]
