= Developing an Integration
:page-aliases: help-overview-develop.adoc, develop-an-integration.adoc, tut-dev-develop-integration.adoc

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

Use Anypoint Code Builder to build integrations within a Mule application. Integrations with Anypoint Code Builder rely on a service-based framework that decouples your source from protocols and routing requirements. You can reuse or change operations in the application when your systems or business needs change. 

Integrations enable multiple services to work as one. Some common use cases are:

* Scheduling data processing
* Connecting cloud and on-premises applications
* Event processing in which multiple services are composed and operate simultaneously

Learn to to create a basic integration, add dependencies and connectors to your Mule application, and transform the payload of your response by using DataWeave:

. xref:create-xml-snippets.adoc[]
. xref:connect-to-a-db.adoc[]
. xref:use-dataweave-to-transform-data.adoc[]
