= Implement a Local API


To implement a local API:

. Open an API specification. +
You can either import an API from Design Center, or design a new API specification.
. Open the Command Palette (`ctrl/cmd + shift + P`) and type _MuleSoft: Implement a Local API_.
. Code Builder creates a multi-root workspace to keep your API specification and Mule project in sync. +
A multi-root workspace enables you to work with both your API specification and Mule project folders at the same time.
. After the workspace is created, Code Builder builds your API. +
In this step, Code Builder packages the API specification and publishes it to a local Maven repository as a snapshot.
. Choose a location to store your workspace. +
Your multi-root workspace is a `.code-workspace` file extension that keeps both of your directories coordinates.
+
[IMPORTANT]
--
Save your `.code-workspace` file on your home directory. Do not save it inside your API specification folder.
--
. Choose a project name for your Mule project.
. Choose a location for your Mule project.
. Code Builder scaffolds your current local API specification into a new Mule project.

You can now start iterating between your API specification and its related Mule project.

== Working Iteratively Between Your API Specification and Mule Project

Implementing a local API enables you to reflect your changes to your API design directly into the Mule project that implements your API specification.

Every time you modify your API specification, you can run a *Re-Scaffold this local API* command to update your Mule project based on the changes of your Mule application. For example, if you add a new endpoint on your API specification, Code Builder scaffolds a new flow for that endpoint.


You can close your multi-root workspace by running the *Worspaces: Close Worspace* command. You can re-open your synchronized project by opening the workspace your created when you started implementing your local API.
