= Anypoint Code Builder Overview
:page-deployment-options: cloud-ide, desktop-ide
:page-aliases: ui-help.adoc

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

//intro
Use the Anypoint Code Builder integrated development environment (IDE) for your API designs, implementations, and integration development. Work locally with Anypoint Code Builder for Desktop on Microsoft Visual Studio Code (VS Code) or from your browser with Anypoint Code Builder through Anypoint Platform. The IDEs support the development lifecycle:

* API specification design (OAS or RAML), a mocking service for testing, source control, and publication to Anypoint Exchange
* API implementation features for importing supported API specifications  (OAS, RAML or GraphQL) and autogenerating interfaces (scaffolding) for flows and error handlers within a Mule application
* Integration development to connect systems, transform data to required formats, and provide business logic to manage messages and events programmatically within a Mule application

The desktop and cloud IDEs offer the same Anypoint Code Builder functionality. Use the IDE that works better for your needs. You can share project snapshots between IDEs or with members of your team by using import and export features or by using a source control management (SCM) system of your choice.

For an introduction to Anypoint Code Builder, see our Trailhead badge, https://trailhead.salesforce.com/content/learn/modules/mulesoft-anypoint-code-builder-quick-look[Anypoint Code Builder: Quick Look^] (login required). Sign up if you don't have a Trailhead account. 

//extensions info
[[extension-pack]]
== Anypoint Extension Pack

Get the Anypoint Code Builder experience through the Anypoint Extension Pack for Visual Studio Code. The cloud-based extensions are preinstalled into a code-server implementation that makes VS Code accessible from a browser. The desktop extensions require installation to your VS Code IDE. See xref:setup.adoc[].

[[us-eu-clouds]]
== US and EU Cloud Hosts

Anypoint Code Builder is available through Anypoint Platform from US and EU cloud hosts. To help your organization meet emerging regulatory requirements that differ by region, Anypoint Platform does not share organization information, permissions, account data, or projects between hosts. 

* US Cloud (non-EU region host): https://anypoint.mulesoft.com/login/[anypoint.mulesoft.com^] 
+
MuleSoft hosts this control plane within data centers in the United States.

* EU Cloud (EU-compliant host): https://eu1.anypoint.mulesoft.com/login[eu1.anypoint.mulesoft.com^]
+
MuleSoft hosts this control plane within EU (Frankfurt) data centers.

Anypoint Platform hosts deployment targets for managed runtimes and related data, including data and metadata about your Mule implementations. API specification projects also store source files in the SCM in Design Center on the cloud that you use.

Use of Anypoint Code Builder in the desktop and cloud IDEs requires an Anypoint Platform user account. Access to the cloud IDE for Anypoint Code Builder requires permissions set by an organization administrator (see xref:configure-permissions.adoc[]). 

To open Anypoint Code Builder from Anypoint Platform, see xref:start-acb.adoc#set-up-web[Launch the Cloud IDE]. If you do not have an Anypoint Platform account through your organization, you can sign up in the US or EU Cloud host for Anypoint Platform. 

See xref:hosting-home::index.adoc[] for more information.

== Get Familiar with the Basics

Some knowledge about designing an API using API specification languages (OAS or RAML) can be helpful. API implementations and integration development require familiarity with Mule application development, connectors, and the DataWeave transformation language. Anypoint Code Builder xref:tut-af-deploy-am-flights.adoc[tutorials] help you get started with these tasks.

It's also useful to be familiar with these products and features:

* Anypoint Connectors provide operations for retrieving, modifying, and sending data to and from systems. Anypoint Code Builder provides xref:acb-components.adoc#builtin-connectors[built-in connectors] and access to many other connectors from Anypoint Exchange.

* Core processors (also called Core components or Mule components) are programmatic building blocks that provide the business logic for integration and implementation applications. Examples include For Each (`<foreach/>`), Transform Message (`<ee:transform/>`), and Flow (`<flow/>`). See xref:acb-components.adoc[].

* DataWeave is the programming language for all expressions and data transformations in your integrations and implementations. The language offers function libraries and mechanisms for creating customizations, including your own functions, libraries, and data types. To learn the basics of DataWeave and experiment with DataWeave scripts, see https://dataweave.mulesoft.com/[DataWeave Tutorial and Playground^].

* Scaffolding is an automatic process that uses APIkit to take an API specification as input and autogenerate an XML-based router and endpoints that you implement within a Mule application.

* A flow is a block of components, including any connector operations, that Mule runtime engine (Mule) executes sequentially on an event and the message it contains. A flow can also contain an operation that triggers the creation of the event and initiates the execution of the flow.
+
A subflow is similar to a flow but does not support the configuration of triggers (sometimes called message sources), which are exclusive to flows. 
+
A flow reference enables you to to trigger execution of a flow or subflow from another flow.

* A Mule application contains one or more XML-based configuration files for your connectors, components, secure configuration properties, scaffolded API specifications, and other parts of your integrations and implementations. The application runs on Mule and is part of a project that contains the resources needed to configure, build, run, test, and deploy the application. 

//Mule application development requires some understanding of the Mule message model, predefined Mule variables (`payload`, `attributes`, `vars`, `errors`), and execution of the Mule event within Mule flows.
//TODO: POINT TO helpful areas of the Mule docs (below)

[[business-groups]]
* Business groups organize APIs, Mule applications, and other resources within an Anypoint Platform organization. Organization administrators create and control access to business groups. For details about business groups, organizations, and related management features, see xref:access-management::business-groups.adoc[].

== Anypoint Platform Product Integrations

//relationships to our other products
Both the web and desktop Anypoint Code Builder IDEs integrate with key Anypoint Platform products and features: 

* Anypoint Exchange for publishing the API specifications that you create, and for importing API specifications and development resources (such as connectors) into your projects
* CloudHub for deploying the implementations and integrations that you build 
* Design Center for storing API specifications as they are developed

The use of features provided by Anypoint Platform products through the cloud and desktop IDEs requires a connection from the IDE to Anypoint Platform. You establish this connection by logging in to your Anypoint Platform account from the IDE. For more information, see xref:start-acb.adoc#log-in-to-anypoint-platform-from-the-ide[Log in to Anypoint Platform from the IDE].

== Feedback

To provide feedback about Anypoint Code Builder, complete the https://www.surveymonkey.com/r/acb_feedback[feedback survey^]. 

For questions or general discussion about Anypoint Code Builder, see https://trailhead.salesforce.com/trailblazer-community/topics/mulesoftanypointcodebuilder?sort=LAST_MODIFIED_DATE_DESC[Trailblazer Discussion Topic^].

== See Also

* xref:access-management::index.adoc[]
* xref:exchange::index.adoc[]
* xref:connectors::index.adoc[]
* xref:dataweave::index.adoc[]
* xref:mule-runtime::index.adoc[]
//* xref:design-center::index.adoc[] 
//* xref:studio::index.adoc[]
//* xref:configure-permissions.adoc[Configure Permissions]
//* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
