= Overview

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//intro
Anypoint Code Builder enables you to design, test, and implement API specifications, and to develop, debug, and deploy integrations that connect data from disparate systems and transform your data to required formats. Work locally with Anypoint Code Builder for Desktop on Visual Studio Code or online with Anypoint Code Builder on Anypoint Platform. Anypoint Extension Pack is the set of extensions to Visual Studio Code that provides the Anypoint Code Builder experience in the desktop and web-based IDEs.

* API specification design with OAS or RAML, a mocking service for testing, source control, and publication to Anypoint Exchange
* API implementation features for importing and automatically scaffolding supported API specifications
* Integration development to connect systems, transform data, and manage messages and events programmatically within a Mule application

//extensions info
Anypoint Code Builder is available from the web or from your desktop. The web-based Anypoint Code Builder and desktop-based Anypoint Code Builder for Desktop are a set of MuleSoft extensions to Visual Studio Code (VS Code) IDE. The web-based extensions are built into the code-server VS Code IDE and require no additional software, setup, or machine specifications. The desktop extensions require installation to your VS Code IDE, which is described in xref:setup.adoc[]. 

//relationships to our other products (avoid mentioning features not introduced yet)
Both the web and desktop Anypoint Code Builder IDEs integrate with key Anypoint Platform features: 

* Exchange for publishing the API specifications you create and for importing API specifications and development resources
* Design Center for storing API specifications as they are developed
* CloudHub for deploying the implementations and integrations that you build 

//what do people need to know to get started?
//NOT YET: While built-in features, such as AI-generated suggestions, help guide your work in Anypoint Code Builder, the following background is necessary: 

//While Anypoint Code Builder provides many intuitive features, experience with the following is useful:

To design API specifications, knowledge of API design languages (supported versions of OAS or RAML) is necessary. 
//You can easily transition to Anypoint Code Builder if you already have experience with Anypoint Design Center for this task. 

To implement API specifications and develop integrations, familiarity with Mule application development and the DataWeave transformation language is important. 
//You can easily transition to Anypoint Code Builder if you already have experience with these tasks in Anypoint Studio. 

//TODO: ADD Learning resources are available in the connector docs, Mule docs, DataWeave docs, and dataweave.mulesoft.com, which provides a tutorial and playground for trying out DataWeave scripts.  

//seems like we have no choice but to introduce them to key things they
//need to understand and point them to resources for more info

//TODO: SHOULD WE ADD SOMETHING LIKE THIS (WITH IMPROVED DESCRIPTIONS)?
//TODO: QA and refine the "starter" descriptions below, of course
//Important concepts include the following:

Familiarity with the following concepts is useful when using Anypoint Code Builder to implement APIs and develop integrations:

* Connectors provide operations for retrieving, modifying, and sending data to and from systems. Built-in connectors for Anypoint Code Builder include the HTTP, Database, and Salesforce connectors. Many more connectors are available through Anypoint Code Builder from Anypoint Exchange.
//TODO: we're preparing a way to provide sharable component doc in ACB doc set for these. This bullet could point to that ACB doc once it exists and/or to the connectors section of the docs.

* Components are programmatic building blocks of an integration application. Examples include For Each <foreach/>, Transform Message <ee:transform/>, and Flow <flow/>.
//TODO: we're preparing a way to provide sharable component doc in ACB doc set for these. This bullet could point to that doc or to the component section of the docs. I'd prefer the former, which will exclude refs to Studio.

* DataWeave is the programming language for all expressions and data transformations. The language offers rich function libraries and mechanisms for creating customizations, including your own functions, libraries, and types.
//TODO: POINT TO DW docs, DW playground & tutorial on dataweave.mulesoft.com (below)

* Scaffolding is an automatic process that uses APIKit to convert an API specification into an XML-based router and endpoints that you implement within a Mule application. 
//TODO: Not sure if we need to say more about APIKit; leaning toward no.
//TODO: If already introduced above, prob not needed here unless we're adding some detail

* A Mule application is an XML-based integration application that runs on the Mule runtime engine. The application supports connectors, components, and scaffolded API specifications. 

//Mule application development requires some understanding of the Mule message model (Mule event, Mule message), predefined Mule variables (`payload`, `attributes`, `vars`, `errors`), and execution of the Mule event within Mule flows.
//TODO: POINT TO helpful areas of the Mule docs (below)

//suggest consolidating feedback info on this page and assuming familiarity with GitHub 
//== Feedback

//You can provide feedback about Anypoint Code Builder as a https://github.com/forcedotcom/try-acb-feedback/issues[GitHub issue^]. 

//For questions or general discussions about Code Builder, see see https://trailhead.salesforce.com/trailblazer-community/topics/mulesoftanypointcodebuilder?sort=LAST_MODIFIED_DATE_DESC[Trailblazer Discussion Topic^].

//TODO: ANYTHING ELSE?

== See Also

* xref:exchange::index.adoc[]
* xref:connectors::index.adoc[]
* xref:dataweave::index.adoc[]
* xref:design-center::index.adoc[] 
* xref:mule-runtime::index.adoc[]
* xref:studio::index.adoc[]

//* xref:configure-permissions.adoc[Configure Permissions]
//* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
