= Overview

Anypoint Code Builder is a web-based integrated development environment (IDE) that has all the power and flexibility of Visual Studio Code along with the Anypoint Code Builder extensions. Anypoint Code Builder provides a modern experience for all developers to design, develop, and deploy APIs, integrations, and automation from a single environment.

Anypoint Code Builder makes it easy for admins and developers alike to work without having to worry about downloading software, setup, or machine specifications.

Anypoint Code Builder is in a private beta stage and it's available for any organization that signed up for this beta release. +
Ask your MuleSoft representative if you are not part of this private beta.

Do not use Anypoint Code Builder to develop APIs, integrations, or automation meant for production environments.

== See Also

* xref:configure-permissions.adoc[Configure Permissions]
* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
* xref:get-started.adoc[Get Started]
* xref:user-guide.adoc[User Guide]
