= Overview

Anypoint Code Builder is a web-based integrated development environment (IDE) that has all the power and flexibility of Visual Studio Code along with the Anypoint Code Builder extensions. Code Builder provides a modern developer experience for all developers to design, develop, and deploy APIs, integrations, and automations from a single environment.
// --> add "(..) to work in the cloud" for future releases.

Code Builder makes it easy for admins and developers alike to work without having to worry about downloading software, setup, or their machine specifications.

Code Builder is in a private beta stage and it's available for any organization that signed up for this beta release. +
Ask your MuleSoft representative if you are not part of this private beta.

Do not use Anypoint Code Builder to develop APIs, integrations, or automations meant for production environments.

== See Also

* xref:configure-permissions.adoc[Configure Permissions]
* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
* xref:get-started.adoc[Get Started]
* xref:user-guide.adoc[User Guide]
