= Overview

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

Anypoint Code Builder is a web-based integrated development environment (IDE) based on Visual Studio Code that includes Anypoint Code Builder extensions. Anypoint Code Builder provides a modern experience for all developers to design, develop, and deploy APIs, integrations, and automations from a single environment.

Anypoint Code Builder requires no additional software, setup, or machine specifications.

Anypoint Code Builder is in private beta, and it's available for any organization that signed up for this beta release. +
If you are not part of this private beta, ask your MuleSoft representative to add you.

Do not use Anypoint Code Builder to develop APIs, integrations, or automations meant for production environments.

== See Also

* xref:configure-permissions.adoc[Configure Permissions]
* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
* xref:get-started.adoc[Get Started]
* xref:user-guide.adoc[User Guide]
