= Overview

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

//intro
Anypoint Code Builder provides an integrated development environment (IDE) for designing, testing, and implementing APIs and for developing, debugging, and deploying integrations and implementations that connect disparate systems. 

Work locally with Anypoint Code Builder for Desktop on Visual Studio Code or online with Anypoint Code Builder on Anypoint Platform. The IDEs support the development lifecycle:

* API specification design (OAS, RAML, or GraphQL), a mocking service for testing, source control, and publication to Anypoint Exchange
* API implementation features enable you to import supported API specifications and autogenerate interfaces for flows and error handlers within a Mule application
* Integration development to connect systems, transform data to required formats, and provide business logic to manage messages and events programmatically within a Mule application

API design requires some knowledge of API specification languages (OAS, RAML, or GraphQL). API implementation and integration development require familiarity with Mule application development, connectors, and the DataWeave transformation language. Anypoint Code Builder xref:user-guide.adoc[tutorials] help you get started with these tasks.

Familiarity with the following is useful:

* Connectors provide operations for retrieving, modifying, and sending data to and from systems. Anypoint Code Builder provides <<builtin-connectors, built-in connectors>> and access to many others from Anypoint Exchange.
//TODO: we're preparing a way to provide sharable component doc in ACB doc set for these. This bullet could point to that ACB doc once it exists and/or to the connectors section of the docs. 

* Core components are programmatic building blocks of an integration application. Examples include For Each <foreach/>, Transform Message <ee:transform/>, and Flow <flow/>.
//TODO: we're preparing a way to provide sharable component doc in ACB doc set for these. This bullet could point to that doc or to the component section of the docs. I'd prefer the former, which will exclude refs to Studio.

* DataWeave is the programming language for all expressions and data transformations. The language offers function libraries and mechanisms for creating customizations, including your own functions, libraries, and types.
//TODO: POINT TO DW docs, DW playground & tutorial on dataweave.mulesoft.com (below)

* Scaffolding is an automatic process that uses APIkit to input an API specification and autogenerate an XML-based router and endpoints that you implement within a Mule application.
//TODO: Not sure if we need to say more about APIkit; leaning toward no.
//TODO: If already introduced above, prob not needed here unless we're adding some detail

* A flow is a block of executable components, including any connector operations, execute sequentially on an event and the message it contains within a Mule application. A flow can also contain an operation that triggers the creation of the event and the execution of the flow.

* A Mule application contains one or more XML configuration files for your connectors, components, secure configuration properties, scaffolded API specifications, and other parts of your integrations and implementations. A Mule  application runs on Mule runtime engine and is part of a project that contains the resources needed to build, run, test, and deploy your application. 

//Mule application development requires some understanding of the Mule message model (Mule event, Mule message), predefined Mule variables (`payload`, `attributes`, `vars`, `errors`), and execution of the Mule event within Mule flows.
//TODO: POINT TO helpful areas of the Mule docs (below)

== Anypoint Extension Pack

//extensions info
Anypoint Extension Pack is the set of extensions to Visual Studio Code that provides the Anypoint Code Builder experience in the desktop and web-based IDEs. The web-based extensions are built into the code-server VS Code IDE and require no additional software, setup, or machine specifications. The desktop extensions require installation to your VS Code IDE, which is described in xref:setup.adoc[]. 

//You can easily transition to Anypoint Code Builder if you already have experience with these tasks in Anypoint Studio. 

== Anypoint Platform Product Integrations

//relationships to our other products (avoid mentioning features not introduced yet)
Both the web and desktop Anypoint Code Builder IDEs integrate with key Anypoint Platform features: 

* Exchange for publishing the API specifications that you create and for importing API specifications and development resources into your projects
* Design Center for storing API specifications as they are developed
* CloudHub for deploying the implementations and integrations that you build 

[[builtin-connectors]]
== Built-In Connectors

Built-in connectors include the following:

* xref:db-connector::index.adoc[Anypoint Connector for Database] (Database Connector) 
* xref:email-connector::index.adoc[Anypoint Connector for Email] (Email Connector)
* xref:http-connector::index.adoc[Anypoint Connector for HTTP] (HTTP Connector)
* xref:salesforce-connector::index.adoc[Anypoint Connector for Salesforce] (Salesforce Connector) 

Many other connectors are available through https://www.mulesoft.com/exchange/[Anypoint Exchange^] from your Anypoint Code Builder IDE.

//what do people need to know to get started?
//NOT YET: While built-in features, such as AI-generated suggestions, help guide your work in Anypoint Code Builder, the following background is necessary: 

//TODO: ADD Learning resources are available in the connector docs, Mule docs, DataWeave docs, and dataweave.mulesoft.com, which provides a tutorial and playground for trying out DataWeave scripts.  

//seems like we have no choice but to introduce them to key things they
//need to understand and point them to resources for more info

//TODO: SHOULD WE ADD SOMETHING LIKE THIS (WITH IMPROVED DESCRIPTIONS)?
//TODO: QA and refine the "starter" descriptions below, of course
//Important concepts include the following:


//suggest consolidating feedback info on this page and assuming familiarity with GitHub 
//== Feedback

//You can provide feedback about Anypoint Code Builder as a https://github.com/forcedotcom/try-acb-feedback/issues[GitHub issue^]. 

//For questions or general discussions about Code Builder, see see https://trailhead.salesforce.com/trailblazer-community/topics/mulesoftanypointcodebuilder?sort=LAST_MODIFIED_DATE_DESC[Trailblazer Discussion Topic^].

//TODO: ANYTHING ELSE?

== See Also

* xref:exchange::index.adoc[]
* xref:connectors::index.adoc[]
* xref:dataweave::index.adoc[]
* xref:design-center::index.adoc[] 
* xref:mule-runtime::index.adoc[]
* xref:studio::index.adoc[]

//* xref:configure-permissions.adoc[Configure Permissions]
//* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
