= Devloping an Integration Using Einstein

include::partial$acb-ide-logos.adoc[tags="both-ides"]

Use Einstein for Anypoint Code Builder: Generative Flows (Einstein) to jumpstart your integration development by using natural language prompts to generate your flows. The engine for these generative flows is the pre-trained large language model (LLM) that is natively embedded within Salesforce. These LLMs are the heart of Generative AI capabilities in Anypoint Code Builder. 

== Trust Layer

The Einstein trust layer bridges our platform and the Salesforce native LLMs. 

//This is a placeholder image. I think we should have something similar. Not sure if we want to use this one or create our own. I also don't have Omnigraffle-valkyrie
image::acb-einstein-trust-layer-png[]

//Image is describing the following flow
Anypoint Code Builder user sends prompt to Einstein. 

MuleSoft proprietary data to grounds the prompts before sending them to Open AI via the gateway. 

We make sure that prompts are sent securely and safely to these external models, and that there is Zero data retained outside of Salesforce. 

After a response is generated, it is sent back through the gateway, and we do a validity check to make sure that the flows work with the MuleSoft ecosystem. 

Lastly, we log the prompt and generated responses for monitoring before surfacing the validated response in Anypoint Code Builder.




[IMPORTANT]
This feature uses generative AI, which is known to include inaccurate or harmful responses. Before implementing this feature, review the output for accuracy and safety. You assume responsibility for the output when making business decisions.