= Mocking Data Using a DataWeave Library
:page-deployment-options: cloud-ide, desktop-ide
:imagesdir: ../assets/images
// :page-aliases: mock-data-using-dw-library

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

include::partial$acb-reusable-steps.adoc[tags="in-progress"]

The DataWeave 
https://anypoint.mulesoft.com/exchange/68ef9520-24e9-4cf2-b2f5-620025690913/data-weave-mock-data-generators-library/minor/1.0/[Mock Data Generators Library^]
includes functions to generate random mock data for testing purposes.
Use Anypoint Code Builder to import this library from Exchange and use it to return a random value from the library.

== Before You Begin

Before getting started, ensure you:

* xref:start-acb.adoc[Set up and access the web or desktop IDE].
* xref:int-create-integrations.adoc[Create an integration (Mule App)].

== Mock Data Using a DataWeave library

. Open your integration project in Anypoint Code Builder.
// Pointer to Command Palette
include::partial$acb-reusable-steps.adoc[tags="open-command-palette"]
. Enter `import` and select the following command:
+
[source,command]
--
MuleSoft: Import Asset from Exchange
--
. Select *DataWeave Library*.
. Enter *mock* and select *DataWeave Mock Data Generators Library*.
. Configure a flow with an HTTP listener that exposes a root path (`/`).
+
For example:
+
[source,XML]
--
<flow name="receive-request" doc:name="Flow" >
  <http:listener path="/" config-ref="HTTP_Listener_config" doc:name="Listener" doc:id="bbzemf" />
  <set-payload value="#[]" doc:name="Set Payload" doc:id="ee6848" />
</flow>
--
. Add the following DataWeave script inside the `value` element of the `set-payload` element:
+
[source,dataweave]
--
%dw 2.0
output application/json
import * from mocks::DataGenerators
---


mocks::DataGenerators::randomCity()
--

. Review your XML code:
+
[source,XML]
--
<flow name="receive-request" doc:name="Flow" >
  <http:listener path="/" config-ref="HTTP_Listener_config" doc:name="Listener" doc:id="bbzemf" />
  <set-payload
    doc:name="Set Payload"
    value="#[%dw 2.0 output application/json import * from mocks::DataGenerators --- mocks::DataGenerators::randomCity()]"
    />
</flow>
--
. Import the *HTTP Connector - Mule 4* library from Exchange. 
+
For information about importing connectors, see
xref:int-create-integrations.adoc#import-connectors-from-exchange[Import a Connector from Exchange].

. DO SOMETHING ELSE. 
+
BUT WHAT?

== See Also 

* xref:int-create-integrations.adoc#add-components[Add a Component to Your Project]
* xref:int-deploy-mule-apps.adoc[]