= Secure Configuration Properties 

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

Encrypt sensitive values of properties used in your Mule application, and hide the name of the decryption key in Runtime Manager when the application deploys to CloudHub. 


//TODO: SCREENSHOT SHOWING the files in the project and config XML
TODO TO SELF - SIMPLIFY THE FOLLOWING TO MAKE MORE CONCEPTUAL AND LESS TASK-ORIENTED. ALSO USE CONTENT TO CREATE NUMBERED STEPS (started), WITH ENOUGH DETAIL TO COMPLETE. 

Encrypt properties using the MuleSoft Secure Properties Tool. After encrypting,  create a file for the properties. In the file, specify key-value pairs for which the encrypted property is the value and the key is a unique name of your choice, for example, `my.property : "![En8lII21ZHrdIaINw0+mSA==]"`. Specify the key-value pairs in a `.yaml` or Spring-formatted `.properties` file, and put the file in the `src/main` directory of the project for your Mule application.

To use an encrypted value in a Mule application, specify the key of your encrypted property in the configuration XML. For example, for `my.property : "![En8lII21ZHrdIaINw0+mSA==]"`, use `${secure::my.property}` instead of the encrypted value. Also configure the Secure Configuration Properties snippet (`<secure-properties:config/>`) to identify your properties file, the name of the decryption key (`encryption.key` by default), and the same <<algorithms, algorithm>> that was used to encrypt the value. `<secure-properties:config/>` is a global element at the same level as the `<flow/>` element.

Before deploying your application, provide the name of decryption key as a `secureProperties` value in `mule-artifact.json` For example, if `encryption.key` is the name of the key, add the `secureProperties` line to the file, making sure add a comma before the preceding line.

----
{
    "minMuleVersion": "4.4.0",
    "secureProperties": [encryption.key]
}
----

When you deploy your application to CloudHub, the UI prompts you for the value of your encryption key. After you complete your deployment, Mule Runtime hides the name of the encryption key. When you navigate to the *Properties* tab for the application in Runtime Manager, the encryption key is hidden. 

//TODO: EXAMPLES THAT HAVE CONTEXT 
// * CONFIG XML WITH THE EMBEDDED Secure Configuration Properties snippet AND A COMPONENT OR CONNECTOR WITH A SECURE PROPERTY CONFIG
// * PROPERTIES FILE WITH A SECURED PROPERTY as part of the key-value pair
// * mule-artifact.json example is above


[[steps]]
IN PROGRESS, NEEDS A LOT OF CONTEXT STILL... SOME SCREENSHOTS
//TODO: PROB 3 SECTIONS: encrypt property, apply/use property, hide decryption key

To encrypt sensitive values:

. Download the https://docs.mulesoft.com/mule-runtime/4.4/_attachments/secure-properties-tool.jar[Secure Properties Tool] (an executable JAR file). 

. From the command line, run the Secure Properties Tool on the value or file that you intend to secure. 
+
The tool requires the following settings:

* An encryption algorithm to use, such as Blowfish. The tool supports other algorithms. 
* A value for your decryption key. 
* The unencrypted value of the property to encrypt.

You can use terminal in Anypoint Code Builder for this purpose.

. Specify your encrypted properties in a `.yaml` or Spring-formatted `.properties` file within the `src/main` directory of the project folder for your Mule application. 
+
.Example: my.properties.yaml
----
`my.property : "![En8lII21ZHrdIaINw0+mSA==]"`
----
+
//TODO: ADD section on BEST PRACTICES FOR FILE NAME and related {env} variable 

. In your configuration XML for the Mule application: 

.. Embed and configure the Secure Configuration Properties snippet (`<secure-properties:config/>`) in the configuration XML for the application, providing:

* The same encryption algorithm used to encrypt the value
* The name for your decryption key or the default name, `encryption.key`
* The name of the file that contains your encrypted property

.. To use your encrypted value in your application, provide the key of the encrypted property using the `secure::` prefix. 
+
Example: `${secure::my.property}` 


To hide the name of the decryption key:

. Provide the name of decryption key in `mule-artifact.json` for your Mule project. 
+
Example that use `encryption.key` as the name of the key: 
+
----
{
    "minMuleVersion": "4.4.0",
    "secureProperties": [encryption.key]
}
----

. In your Mule application, deploy the application to CloudHub.
+
Anypoint Code Builder asks you to provide the value of that key when deploying the application to CloudHub from the IDE. 
+
When deployed to CloudHub, Runtime Managers shows the key name but hides its value.


[[algorithms]]
== Supported Algorithms

MuleSoft Secure Properties Tool and Secure Configuration Properties snippet and module support the following algorithms:

* AES 
* Blowfish
* DES
* DESede
* RC2
* RCA

AES is the default for the Secure Properties Tool. 
