= Crafting Prompts for Generative Flow

It is a good idea to have a clear use case containing explicit triggers and actions before you use the Generative Flow feature. The quality of the generated flow depends a lot on the quality of your prompt. 

== Prompt Guidelines

Craft your prompt using natural language, and keep in mind that the more concise and specific you can make your prompt, the more effective it will be when it generates your flow. 

Here are some best practices for writing prompts:

* Be clear and precise:
+ 
Use clear and specific language to describe the use case for the flow to build.
* Include trigger events 
+
Mention the trigger events that initiate the flow, for example, sending an email when a new case is created. 
* Emphasize key components:
+
Highlight the key MuleSoft components to include in the flow, for example, HTTP *Listener* and Email *Send*.
* Specify data objects:
+
* Clearly mention the data objects involved, such as "Salesforce Account object" or any other relevant data source.
* Proofread and revise:
+
Before submitting the prompt, proofread your prompt to ensure that it is clear and comprehensive.

After the initial flow is generated for you, you can then customize the code for your specific needs.

== See Also

* xref:int-gen-flow-examples-ai.adoc[]
* xref:int-create-integrations-ai.adoc[]
* xref:acb-components.adoc[]
