= Crafting Prompts for Generative Flow

It is a good idea to have a clear use case that contains specific tasks to accomplish before you use Generative Flows. The quality of the generated flow will depend on on the quality of your prompt. 

== Prompt Guidelines

You can craft your prompt using natural language, but the more concise and specific you can make it, the better the output will be. 

Here are some best practices for writing prompts:

* Be clear and precise
+ 
Use clear and specific language to describe the use case for the flow to build.
* Include trigger events 
+
Mention the trigger events that initiate the flow, for example, sending an email when a new case is created. 
* Emphasize key components
+
Highlight the key MuleSoft components to include in the flow, for example, HTTP *Listener* and Email *Send*.
* Specify data objects
+
* Clearly mention the data objects involved, such as "Salesforce Account object" or any other relevant data source.
* Proofread and revise
Before submitting the prompt, proofread your prompt to ensure that it is clear and comprehensive.


== Example Prompts

=== Use Case

=== Use Case


== See Also

* xref:int-create-integrations-ai.adoc[]
