= Migrate Your Mule Project from Anypoint Studio to Anypoint Code Builder
:page-deployment-options: cloud-ide, desktop-ide

Migrate your Mule project from Anypoint Studio to Anypoint Code Builder by creating a deployable Mule application archive (JAR file). 
With Anypoint Code Builder, you unlock a modern development experience with advantages like faster startup times, streamlined collaboration, and the integration of MuleSoft for Agentforce: Topic Center to enable API specifications for topics and agents.

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

== Export Your Mule Project to a Sharable JAR File in Anypoint Studio

include::partial$acb-project-migration.adoc[tag="export-mule-projects-from-studio"]

=== Exporting Considerations

include::partial$acb-project-migration.adoc[tag="exporting-considerations-from-studio"]

== Import a Mule Project from a Sharable JAR File in Anypoint Code Builder

include::partial$acb-project-migration.adoc[tag="import-mule-project-into-acb"]

== Understand Workspaces Differences

An IDE workspace is a logical environment that groups your projects. It also contains all associated settings, configurations, and state for development. Workspaces are primarily used for:

* Managing multiple related projects
* Keeping plugin-specific settings and environments consistent
* Isolating different development contexts

=== Workspace Considerations

Anypoint Studio uses an Eclipse workspace that contains multiple projects. Anypoint Code Builder uses a folder-based VS Code workspace, typically with one or more projects per workspace. So Anypoint Code Builder workspace can be physically in the same location. Evaluate these other considerations if migrating your project:

* Make sure Anypoint Code Builder supports the Mule runtime version of your project
* Install relevant extensions, if requested
* Configure Git for your projects, if needed
* Set up any custom build configurations, if needed

=== Import Studio Workspace into Anypoint Code Builder

Import your Anypoint Studio workspace into Anypoint Code Builder as a VS Code workspace.

. In Anypoint Code Builder, go to *File* > *Open Folder*.
. Go to your Studio workspace.
. Select the individual project folder. Don't select the entire workspace.

Alternatively, you can export the Studio workspace as a ZIP file and import the project folder directly into Anypoint Code Builder.

. In Studio, right-click your project and select *Export*.
. Select *General* > *Archive File*.
. Select one or more projects to export.
. Click *Browse* to select the folder where you want to export the ZIP file.
. Click *Finish*.
. In Anypoint Code Builder, open the *Command Palette*.
. Select *MuleSoft: Import a Mule project* and *From compressed file*.
. Select the exported ZIP file.

=== Verify Workspace Setup

After importing your project into Anypoint Code Builder, verify that the setup is correct.

* The `pom.xml` file is compatible with Anypoint Code Builder
* The Mule runtime version is supported in Anypoint Code Builder
* The Maven dependencies resolve correctly
* The project builds successfully after running `mvn clean package` 
* Your Mule application runs as expected in the new Anypoint Code Builder workspace
* Debug configurations are set up to troubleshoot your application
* The configuration XML file show no errors
* The canvas loads correctly, which means that the component dependencies resolve correctly

== See Also

* xref:int-import-mule-project.adoc[] 
* https://code.visualstudio.com/docs/editing/workspaces/workspaces[Visual Studio Code Workspace]

