= Migrate Your Mule Project from Anypoint Studio to Anypoint Code Builder
:page-deployment-options: cloud-ide, desktop-ide

Migrate your Mule project from Anypoint Studio to Anypoint Code Builder by creating a deployable Mule application archive (JAR file). 
With Anypoint Code Builder, you unlock a modern development experience with advantages like faster startup times, streamlined collaboration, and the integration of MuleSoft for Agentforce: Topic Center to enable API specifications for topics and agents.

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

== Export Your Mule Project to a Sharable JAR File in Anypoint Studio

include::partial$acb-project-migration.adoc[tag="export-mule-projects-from-studio"]

=== Exporting Considerations

include::partial$acb-project-migration.adoc[tag="exporting-considerations-from-studio"]

== Import a Mule Project from a Sharable JAR File in Anypoint Code Builder

include::partial$acb-project-migration.adoc[tag="import-mule-project-into-acb"]

== Understand Workspaces Differences

An IDE workspace is a logical environment that groups your projects. It also contains all associated settings, configurations, and state for development. Workspaces are primarily used for:

* Managing multiple related projects
* Keeping plugin-specific settings and environments consistent
* Isolating different development contexts

=== Workspace Considerations

Anypoint Studio uses an Eclipse workspace that contains multiple projects. Anypoint Code Builder uses a folder-based VS Code workspace, typically with one or more projects per workspace. So Anypoint Code Builder workspace can be physically in the same location. Take into account these other considerations when migrating your project:

* Make sure Anypoint Code Builder supports the Mule runtime version of your project
* Install relevant extensions, if requested
* Configure Git for your projects, if needed
* Set up any custom build configurations, if needed

=== Verify Workspace Setup

After importing your project into Anypoint Code Builder, verify the setup is correct:

* Maven dependencies must resolve correctly
* Run `mvn clean package` to make sure the project builds successfully
* Test that your Mule application runs properly in the new Anypoint Code Builder workspace
* Set up debug configurations if needed to troubleshoot your application
* Check for errors and make sure that the configuration XML file and the canvas load correctly to verify that component dependencies resolve correctly

== See Also

* xref:int-import-mule-project.adoc[] 
