= Using the DataWeave Language
:page-deployment-options: cloud-ide, desktop-ide

// use-dataweave-to-transform-data

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

DataWeave is the programming language designed by MuleSoft for data transformation.
It is also the expression language that Mule runtime engine uses to configure components and connectors.

With DataWeave, you can build a simple solution for a common use case for integration developers:

. Read and parse data from one format
. Transform the data.
. Write it out as a different format.

For example, a DataWeave script can receive a CSV file as input and transform it into an array of complex JSON objects, or receive an XML input and write the data out to a flat file format.
DataWeave enables developers to focus on the transformation logic instead of thinking about the specifics of reading, parsing, and writing specific data formats in a performant way.

== Find More Information about DataWeave

* Learn how to use DataWeave: https://dataweave.mulesoft.com/learn/tutorial[DataWeave Tutorial^]
* Try DataWeave scripts interactively: https://dataweave.mulesoft.com/learn/[DataWeave Playground^].
* Learn more about the DataWeave language: xref:dataweave::dataweave-language-guide.adoc[].
* Look up reference information about DataWeave operators and functions:  xref:dataweave::dw-functions.adoc[].
* See sample scripts to solve common transformation scenarios: xref:dataweave::dataweave-cookbook.adoc[].

