= Developing Integrations
// develop-integration

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

Use Anypoint Code Builder to build integrations within a Mule application.
Integrations with Anypoint Code Builder rely on a service-based framework that decouples your source from protocols and routing requirements.
You can reuse or change operations in the application when your systems or business needs change. 

Integrations enable multiple services to work as one. Some common use cases are:

* Scheduling data processing
* Connecting cloud and on-premises applications
* Event processing in which multiple services are composed and operate simultaneously

When developing API integrations, you can:

* xref:int-create-basic-integrations.adoc[Create your integration project].
* xref:int-work-with-code-snippets.adoc[Work with code snippets].
* xref:int-create-secure-configs.adoc[Define and secure properties for your Mule application]
* xref:int-use-dw-to-transform-data.adoc[Transform data using DataWeave].
