= Enable Einstein for Anypoint Code Builder

As an Anypoint Platform Organization Administrator, you can enable the Einstein for Anypoint Code Builder generative flows feature so that everyone in your Anypoint Platform organization can send requests to Einstein through the Einstein-enabled Salesforce org you select. 

== Enabling Einstein for Anypoint Code Builder

. Sign in to Anypoint Platform through Anypoint Code Builder with your organization administrator account. 
. Select the *Enable Einstein for Anypoint Code Builder* checkbox.
. Select the Salesforce organization to route Einstein requests through. 
+
NOTE: The selected Salesforce organization must have Einstein turned on. 
+
You can choose a shared or private Salesforce organization. It's best to use your private Salesforce org so that you can store your Einstein generative AI audit and feedback data in Data Cloud. You can use that data for compliance, analytics, prompt adjustments, and LLM tuning to enhance your generative AI applications.
+
If you choose a shared organization, all Einstein requests are routed through the shared organization and Einstein requests are subject to any rate limiting policies in effect for that organization. 
. 


== See Also

* https://help.salesforce.com/s/articleView?id=sf.generative_ai_enable.htm&type=5[]
