= Configuring DataWeave Expressions

Configure DataWeave expressions in your integrations and implementations from the expression builder UI or from the configuration XML. Mock data for your expressions so that you can preview sample output of your expressions in Anypoint Code Builder.

* <<expression-builder>>
* <<sample-data>>

//TODO: CONVERT TO INCLUDE FOR SHARING
DataWeave is the programming language designed by MuleSoft for data transformation within a Mule app. DataWeave is also the expression language Mule runtime engine uses to configure components and connectors. When you create an implementation or integration in Anypoint Code Builder, you are creating a Mule app that runs on an instance of the Mule runtime engine. 

== Before You Begin

It is important to have a basic understanding of the DataWeave language. DataWeave expressions accept the following: 

* xref:dataweave::dw-functions.adoc[DataWeave functions and operators] and data types that their parameters accept. For example, the concatenation function (xref:dataweave::dw-core-functions-plusplus.adoc[++]) accepts strings, arrays, objects, date-related data types, and so on. 
* xref:dataweave::dataweave-variables-context.adoc[Predefined Mule variables] such as `payload`, `attributes`, `vars`.
* xref:dataweave::dataweave-selectors.adoc[DataWeave selectors] for capturing the values of fields within the payload, attribute, or variable within the xref:mule-runtime::about-mule-event.adoc[Mule event]. 

For more information, see xref:dataweave::index.adoc[]. 

[[expression-builder]]
== Construct a DataWeave Expression from the Canvas UI

Use the DataWeave expression builder to ease configuration of DataWeave expressions, supply sample data for your expression, and preview the expression's output without the need to run your Mule app. 

The expression builder provides the following tabs:

* *Data*: Illustrates the data structure with any sample data that is available. To create sample data, see <<sample-data>>. For example:
+
TODO: ADD SCREENSHOT
TODO: ADD SHORT DESCRIPTION

* *Functions*: Lists all DataWeave functions from all xref:dataweave::dw-functions.adoc#dw_modules[DataWeave modules], such as String, Array, and Core modules. You can hover over the functions to get a short description or click a function's *Details* link to open the full documentation within the expression builder panel. The documentation provides examples and descriptions of any parameters. 

//TODO: within the fx field in the UI, you can also do Ctrl-space to get a list of Core functions only?

* *Preview*: 
+
TODO: ADD SCREENSHOT


To construct a DataWeave expression from the canvas:

. Create an integration project.
+
For guidance, see xref:int-create-integrations.adoc#create-integration-project[Create an Integration Project].
. From the canvas, add a Set Payload component.
+
Set Payload is convenient for demonstrating expression builder functionality. The expression builder is available to components with *fx* fields, which accept DataWeave expressions.
. Use the expression builder to start an expression:
.. Click Set Payload to display its configuration panel, and then click within its *Value* field (an *fx* field) to open the DataWeave expression builder.
+
Notice the *Data*, *Functions*, and *Preview* tabs in the expression builder.
+
TODO: ADD IMAGE
.. Click the *Functions* tab in the expression builder.
+
Notice the list of DataWeave modules, which includes Core and all other DataWeave modules. Each module contains a set of DataWeave functions. 
+
TODO: ADD IMAGE
+
//TODO: VERIFY
If you want to use a function in the Core module only, you can press Ctrl+Space (Mac) or Cmd+Space (Windows) in an empty *fx* field. If a value is already in the field, the list contains other context-specific data, such as a `default` setting or fields in the payload, for example. 
.. In the *Functions* tab, navigate to *Core* -> *++* (for concatenation).
+
Notice that you can hover over the function to get a short description of the function and that you can click *Details* to get full documentation of the function along with parameter descriptions and examples.
+
TODO: ADD IMAGES short description and full doc
.. Click `++` to add the function to *Value* field. 
. In Set Payload, use `++` to concatenate two strings. For example:
+
[source,DataWeave]
--
`"hello" ++ " world"`
--
.. In the expression builder, click *Preview* to view the output of the expression: `"hello world"`
+
TODO: ADD IMAGE
.. In the expression builder, click the *Data* field. 
+
TODO: SHOW WHAT IT SHOWS
. Use DataWeave selectors to construct an expression:

.. Replace the *Value* `"hello" ++ " world"` with the following complex JSON object:
+
[source,json]
--
{ "city" : { 
           "name" : "San Francisco",
           "address" : [{
                         "streetNumber": 10, 
                         "streetName": "Fremont Ave"
                      }, 
                      {
                         "streetNumber": 7, 
                         "streetName": "Decoto Way"
                     }]
         }, 
         "cityURL": "sf.org", 
         "phonenumber" : [
                         ["432-332-1112", "333-443-1325"], 
                         ["333-443-4421", "333-443-2211"]
                       ], 
                       "population": 100300, 
                       "popularSchools": ["St Charles", "JFK School"]
}
--
.. In the expression builder, click the *Data* field to display the structure of the JSON object with its preconfigured values. 
+
TODO: ADD IMAGE
.. In the canvas, add a Set Variable component after Set Payload.
+
TODO: ADD IMAGE
//TODO:VERIFY THAT THIS IS WHAT OCCURS
.. In the *Value* field, press Cmd+Space (Mac) or Ctrl+Space (Windows), and select `payload` from the resulting list.
.. Click the *Data* tab in the expression builder to display the structure of the payload.
+
TODO: ADD IMAGE
+
Notice that the structure of the payload matches the structure you set in Set Payload. 
.. In the *Value* field of Set Variable, type a dot (`.`) after `payload` (for example, `payload.`), press Cmd+Space (Mac) or Ctrl+Space (Windows), and select *city* from the list of available fields in the payload.
+
TODO: ADD IMAGE
+
The *Value* field now contains `payload.city`.
.. Click the *Preview* field for this value to view the the output.
+
[source,json]
--
{
  "name": "San Francisco",
  "address": [
    {
      "streetNumber": 10,
      "streetName": "Fremont Ave"
    },
    {
      "streetNumber": 7,
      "streetName": "Decoto Way"
    }
  ]
}
--

== Construct a DataWeave Expression from the XML

Use auto-complete menus from the XML to list DataWeave functions and TODO_TODO. 

In the XML, fields that accept DataWeave expressions begin with a hash and are surrounded by square brackets. For example: `#[payload]`, `#[payload.childfield.grandchildfield]`, `["hello" ++ "world"]`.

TODO_TODO

[[sample-data]]
== Create Sample Data for your Mule Apps

Add sample data to your configurations so that you can test and preview  DataWeave expressions in your components locally, without running your application to retrieve Mule event data from an external source. 

When Anypoint Code Builder does not recognize a value, the IDE provides a visual indicator that there is an issue with the value. Issues include:

* `Unable to find sample input`, for example, for a Mule variable, such as `payload`. 
+
For this issue, you can use the *Quick Fix* to provide sample data for the variable. 
* `Unable to resolve reference`, for example, for a sequence of characters like `afkdldjf` that is not recognized.
+
For this issue, you can use the *Quick Fix* that provide a DataWeave script that converts the characters into a DataWeave variable.
* `Expects _x_ but got _y_`, for example, `Expects 1 argument but got 0` in a case such as `round()`, which is missing an argument. Similar errors indicate that an argument is of the wrong data type or that a function is otherwise malformed and requires correction.
* `Invalid input`, for example, for characters such as `?` that are not valid.
+
TODO: NEED REF OR RULE FOR VALID OR INVALID CHARACTERS

Use Quick Fix to provide sample data for a Mule variable:

. TODO

Use Quick Fix to define a DataWeave variable:

. TODO




////
[[xml-example]]
The procedure that follows builds the following configuration XML:
[%collapsible]
====
[source,xml]
--
<?xml version="1.0" encoding="UTF-8"?>
<mule xmlns="http://www.mulesoft.org/schema/mule/core" xmlns:doc="http://www.mulesoft.org/schema/mule/documentation"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ee="http://www.mulesoft.org/schema/mule/ee/core"
  xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core http://www.mulesoft.org/schema/mule/core/current/mule.xsd
	http://www.mulesoft.org/schema/mule/ee/core http://www.mulesoft.org/schema/mule/ee/core/current/mule-ee.xsd"> 
  
  <flow name="my-flow">
    <set-payload value="#[{city : {name : 'San Francisco', address : [{'streetNumber': 10, 'streetName': 'Fremont Ave'}, {'streetNumber': 7, 'streetName': 'Decoto Way'}]}, 'cityURL': 'sf.org', phonenumber : [[432-332-1112, 333-443-1325], [333-443-4421, 333-443-2211]], population: 100300, 'popularSchools': ['St Charles', 'JFK School']}]" doc:name="Set payload" doc:id="jjpylf" /><!--1-->
    <set-variable value='#[payload]' doc:name="Set Variable" doc:id="efdd3ab0-4072-4955-aef6-524bb962d3b0" variableName="action" mimeType="application/json" /><!--2-->
    <set-variable value="#[payload.city.address.streetNumber]" variableName="$2" doc:name="Set variable" doc:id="fntjwh" />
    <logger doc:name="Logger" doc:id="cxfbec" message="#[vars.action]" />
    <ee:transform doc:name="Transform" doc:id="nlltzc"><!--3-->
      <ee:message>
        <ee:set-payload>
          <![CDATA[
              %dw 2.0
              output application/json
              ---
              payload
              ]]>
        </ee:set-payload>
      </ee:message>
    </ee:transform>
    <set-variable value="#[vars.action]" variableName="smoney" doc:name="Set variable" doc:id="vpqjyb" /><!--4-->
  </flow>
  
</mule>
--
. Set Payload component sets 
. 
. 
. 
====
////

