= Getting Analytics on Mule Apps with Autodiscovery
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//overview: what is autodiscovery
//include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-ref"]

Set up API autodiscovery to track analytics on requests to endpoints in a deployed Mule app from API Manager, on Anypoint Platform.  
//include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-concept"] 

Autodiscovery configuration requires the following:

* An API spec on Anypoint Exchange that defines the endpoints in your Mule app
* An API instance ID from a Mule Gateway proxy that is associated with an API spec on Anypoint Exchange 
+
A global element (`<api-gateway:discovery/>`) that you add to your Mule app requires this ID. Mule Gateway is an API gateway embedded within Mule runtime engine (Mule) that can connect directly to a Mule app. 
* Credentials (client ID and secret) that enable the Mule runtime instance in your Mule app to access the business group on Anypoint Platform that manages your Mule Gateway proxy 

To acquire and configure the ID and credentials for autodiscovery in a Mule app, see <<setup>>.
//TODO: WHAT IS THE RELATIONSHIP BETWEEN THE SPEC AND APP?

[[prereqs]]
== Before You Begin

You must have a supported API spec. To get analytics on your app in API Manager through autodiscovery, you must select a spec from Anypoint Exchange or upload the spec directly to a Mule Gateway proxy in API Manager. 

For guidance with the creation of API specs, see:

* xref:anypoint-code-builder::des-create-api-specs.adoc[] to design a spec from Anypoint Code Builder
* xref:design-center::design-designing-api-specs-fragments.adoc[] to design a spec from Design Center 

For guidance publishing an API specs to Exchange, see:

* xref:anypoint-code-builder::des-publish-api-spec-to-exchange.adoc[] to publish your spec from Anypoint Code Builder 
* xref:design-center::design-publish.adoc[] to publish your spec from Design Center

[[setup]]
== Set Up API Autodiscovery in Anypoint Code Builder

. Meet the prerequisites in <<prereqs>>.
. In Anypoint Platform:
.. Obtain the client ID and secret for your business group from Access Management (https://anypoint.mulesoft.com/accounts/businessGroups/[US], https://eu1.anypoint.mulesoft.com/accounts/businessGroups[EU]).
+
The credentials are associated with a business group. For more guidance ,see <<credentials>>. 
.. Navigate to API Manager to obtain an API instance ID from a Mule Gateway proxy for your API specification. 
+
For more guidance, see <<obtain-instance-id>>.
. In Anypoint Code Builder: 
.. Configure autodiscovery in your Mule app by adding a global `api-gateway:discovery` element with your API instance ID value for the `apiID` attribute.
+
For guidance, see <<config-element>>.
.. Append the client ID and client secret for your business group to the default Mule runtime arguments in the *Settings* tab.
+
For more guidance, see <<append-credentials>>.
.. Run your application to ensure that the API is connected by checking the build logs:

* The client ID and client secret validated successfully against API Manager 
* The underlying `GateKeeper` is available (unblocked) and in `FLEXIBLE` mode
* The API Gateway extension is in `STANDALONE` mode

. In API Manager, check that the is registered (active) and produce metrics in API Manager by triggering an endpoint in your Mule app. 


[[credentials]]
=== Obtain a Client ID and Client Secret 

To pair a Mule app with your API spec in API Manager, you must first obtain client ID and client secret for the business group on Anypoint Platform that hosts your API specification and hosts (or will host) your Mule proxy. 

//TODO: DO WE REQUIRE ANY SPECIAL PERMISSIONS TO GET THIS INFO FROM ACCESS MANAGER? 

. Open the list of business groups in Access Management, on Anypoint Platform (https://anypoint.mulesoft.com/accounts/businessGroups/[US], https://eu1.anypoint.mulesoft.com/accounts/businessGroups[EU]).
+
To navigate to the business group list from the Anypoint Platform home page instead, open Access Management, and click *Business Groups*.
. In the business group list, click the name of your business group.
. Click the *Settings* tab for your business group.
. Obtain the *Client ID* and *Client Secrets* values from the *Settings* tab in Access Manager. 

//see https://docs.mulesoft.com/mule-gateway/mule-gateway-org-credentials-mule4#obtaining-credentials

[[obtain-instance-id]]
=== Obtain Your an API Instance ID from API Manager

The API instance ID is available from a Mule proxy an administrator must create a Mule Gateway proxy. 

* If you have a Mule gateway proxy for your Mule app, see <<find-instance-id>>.
* If you do not have a Mule gateway proxy for your Mule app, see <<create-proxy>>.

[[find-instance-id]]
==== Locate the Instance ID

. 

[[create-proxy]]
==== Create a Mule Proxy



//TODO: DOES THIS REQUIRE ADMIN ACCESS

. Meet the prerequisites in <<prereqs>>.
. Open API Manager to *API Administration* 

.. Click *Add API*, and select *Add new API*.
.. In the *Runtime* page that opens, click *Mule Gateway* and then click *Next*.
+
Retain the default settings on the *Runtime* page:

* *Proxy Type*: *Connect to existing application (basic endpoint)*
* *Mule version*: *Mule 4* 

.. Click *Connect to an existing application (basic endpoint)* to connect to a Mule app using API autodiscovery.
+
Alternatively, you can upload the API directly by using 
.. 

[[append-credentials]]
=== Append Credentials to Mule Runtime Settings

In Anypoint Code Builder, append the client ID and secret to you default Mule runtime arguments. Do not delete other settings.

//TODO: IS ONLY ONE CLIENT ID AND SECRET ALLOWED PER ACB INSTALLATION?

////
For example:
-M-Danypoint.platform.client_id=1bf98d35846f4323a32c3c5384aacd97 -M-Danypoint.platform.client_secret=989ED120B3f74604919d00b48D0F9Ef5
////

MULE_HOME/bin/mule \
-M-Danypoint.platform.client_id=XXXXXXXX \
-M-Danypoint.platform.client_secret=XXXXXXXX



[[config-element]]
=== Configuring the Autodiscovery Element in a Mule App

//see https://docs.mulesoft.com/mule-gateway/mule-gateway-config-autodiscovery-mule4#configuring-the-autodiscovery-element-in-your-mule-application


////
reminder API reqs
. Create supported API spec. (DC or elsewhere)
. Publish to Exchange. 
. From API Manager:
.. Click Add New API
.. Select Mule Gateway (from UI: "API gateway embedded in Mule runtime. Connect directly to an existing Mule app or deploy a new proxy app.")
. Connect to you API spec on Exchange. (be sure to use correct asset type -- TODO_TODO: can you use any of the asset types? or just RAML/OAS) 
. Click Next (bottom of page)

////


//TODO: EDIT THIS INTRO
include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-config-xml"]

//TODO: PROVIDE ACB STEPS