= Configuring Components
:page-deployment-options: cloud-ide, desktop-ide
:open-config-xml: In the Explorer, open the configuration XML file for your project:

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

Configure connectors and processors within your implementation and integration projects from the canvas or configuration XML. 

Common tasks include the following: 

* xref:int-work-with-code-snippets.adoc[Work with Code Snippets]
* <<add-components>>
* xref:int-configure-dw-expressions.adoc[Configure Expressions]
* <<check-connection>>
* <<import-connectors-from-exchange>>
* <<open-component-from-xml>>

== Before You Begin

* Determine which connectors, processors, and snippets you intend to use.
+
// Note on ways to start component configs: 
include::partial$acb-component-info.adoc[tags="note-component-add-config"]
// Pointer to component reference:
include::partial$acb-component-info.adoc[tags="note-component-ref"]

* Review xref:index.adoc#get-familiar-with-the-basics[Get Familiar with the Basics] to ensure that you are familiar with important concepts and features. 
+
Understand the basics of Mule flows, the Mule event structure, including the payload, attributes, and Mule variables. To transform data and add expressions to your components, have some familiarity of the DataWeave language.

[[add-components]]
== Add a Component to Your Project

//add component content
include::partial$acb-component-info.adoc[tags="add-components"]

== Disable Components
You can temporarily remove components from your flow without deleting them by disabling them directly from the canvas. This action is equivalent to commenting out code in the XML editor.

To disable a component:

. Right-click a component in the canvas.
. Select *Disable Component*.

Disabled components appear with a dashed outline and a disabled icon. In the XML editor, the component is wrapped in an XML comment (<!-- ... -->), preserving the code but preventing it from executing.
Disabled components appear greyed out in the canvas and are ignored at runtime.

=== Re-enable a Disabled Component

To restore a component:
. Right-click the disabled component.
. Select *Enable Component*.

This also removes the comment from the XML view.

If you previously set a breakpoint on a component and then disable it, the breakpoint remains associated with the component but is inactive. +
You can't add new breakpoints to a disabled component until it's re-enabled.

== Navigate to referenced flows

If a component references another flow (for example, via a Flow Reference connector), you can quickly access the target flow in the canvas. To navigate to the referenced flow:

. Right-click the connector.
. Select *Go to Flow*.

Anypoint Code Builder will open the target flow either in the application canvas or the MUnit canvas, depending on the context.
In the MUnit canvas, you can use Flow Reference components to invoke or simulate execution of other flows. To help you trace and validate the logic, you can navigate to the referenced flow from within the test. To open the referenced flow:

. Right-click the Flow Reference component in the MUnit canvas.
. Select *Go to Flow*.

Anypoint Code Builder opens the target flow in the application canvas (or in another MUnit test flow if that's the target).
• Right-click a Flow Reference in the MUnit canvas to navigate to its target flow.



[[import-connectors-from-exchange]]
== Import a Connector from Exchange

//import connector content
include::partial$acb-component-info.adoc[tags="import-connector-exchange"]

[[check-connection]]
== Test a Connection Configuration

//add component content
include::partial$acb-component-info.adoc[tags="check-connection"]

[[open-component-from-xml]]
== Open a Component in the Canvas from the XML Editor

//open from xml
include::partial$acb-component-info.adoc[tags="open-component-from-xml"]

== Connection Configuration Panel

include::partial$acb-component-info.adoc[tags="connection-configuration-panel"]
