= Getting Metrics on Mule Apps with Autodiscovery
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//overview: what is autodiscovery
//include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-ref"]

Set up API autodiscovery in a Mule app to display metrics in API Manager on requests to endpoints in the app. API Manager is part of Anypoint Platform. 

Autodiscovery configuration in a Mule app requires an API instance ID from a Mule Gateway API in API Manager that is associated with a supported API spec. To acquire and configure the API ID and Anypoint Platform credentials in a Mule app, see <<setup>>.
//include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-concept"] 



//TODO: WHAT IS THE RELATIONSHIP BETWEEN THE SPEC AND APP?

[[prereqs]]
== Before You Begin

If you don't have a Mule Gateway instance ID for your Mule app, you must create one.
//(see SEE_TODO_TODO_TODO). 
Mule Gateway API configuration in API Manager requires a supported API spec on Anypoint Exchange. 

* For guidance with the creation of API specs, see:

** xref:anypoint-code-builder::des-create-api-specs.adoc[] to design a spec from Anypoint Code Builder
** xref:design-center::design-designing-api-specs-fragments.adoc[] to design a spec from Design Center 

* For guidance publishing an API specs to Exchange, see:

** xref:anypoint-code-builder::des-publish-api-spec-to-exchange.adoc[] to publish your spec from Anypoint Code Builder 
** xref:design-center::design-publish.adoc[] to publish your spec from Design Center

For an API spec and Mule app example, see <<examples>>.

[[setup]]
== Set Up API Autodiscovery in a Mule App

Autodiscovery configuration in a Mule app requires:

* A global element (`<api-gateway:discovery/>`) that references an API ID for a Mule Gateway instance. 
+
Mule Gateway is an API gateway embedded within Mule runtime engine (Mule) that can connect directly to a Mule app. 
* Credentials (client ID and secret) that enable the Mule runtime instance in your Mule app to access the business group in Anypoint Platform that manages your Mule Gateway API instance 

To set up autodiscovery:

. Meet the prerequisites in <<prereqs>>.
. In Anypoint Platform:
.. Obtain the client ID and secret for your business group from Access Management (https://anypoint.mulesoft.com/accounts/businessGroups/[US], https://eu1.anypoint.mulesoft.com/accounts/businessGroups[EU]).
+
The credentials are associated with a business group. For more guidance ,see <<credentials>>. 
.. Navigate to API Manager to obtain an API instance ID from a Mule Gateway API instance for your API specification. 
+
For more guidance, see <<obtain-instance-id>>.
. In your Mule app in Anypoint Code Builder: 
.. Configure autodiscovery in your Mule app by adding a global `api-gateway:discovery` element with your API instance ID value for the `apiID` attribute.
+
For guidance, see <<config-element>>.
.. Append the client ID and client secret for your business group to the default Mule runtime arguments in the *Settings* tab.
+
For more guidance, see <<append-credentials>>.
.. Run your application to ensure that the API is connected by checking the build logs:

* The client ID and client secret validated successfully against API Manager 
* The underlying `GateKeeper` is available (unblocked) and in `FLEXIBLE` mode
* The API Gateway extension is in `STANDALONE` mode

. In API Manager, check that the is registered (active) and produce metrics in API Manager by triggering an endpoint in your Mule app. 


[[credentials]]
=== Obtain a Client ID and Client Secret 

To pair a Mule app with your API spec in API Manager, you must first obtain client ID and client secret for the business group on Anypoint Platform that hosts your API specification and hosts (or will host) your Mule proxy. 

//TODO: DO WE REQUIRE ANY SPECIAL PERMISSIONS TO GET THIS INFO FROM ACCESS MANAGER? 

. Open the list of business groups in Access Management, on Anypoint Platform (https://anypoint.mulesoft.com/accounts/businessGroups/[US], https://eu1.anypoint.mulesoft.com/accounts/businessGroups[EU]).
+
To navigate to the business group list from the Anypoint Platform home page instead, open Access Management, and click *Business Groups*.
. In the business group list, click the name of your business group.
. Click the *Settings* tab for your business group.
. Obtain the *Client ID* and *Client Secrets* values from the *Settings* tab in Access Manager. 

//see https://docs.mulesoft.com/mule-gateway/mule-gateway-org-credentials-mule4#obtaining-credentials

[[obtain-instance-id]]
=== Obtain Your an API Instance ID from API Manager

The API instance ID is available from a Mule proxy an administrator must create a Mule Gateway proxy. 

* If you have a Mule gateway proxy for your Mule app, see <<find-instance-id>>.
* If you do not have a Mule gateway proxy for your Mule app, see <<create-proxy>>.

[[find-instance-id]]
==== Locate the Instance ID

. 

[[create-proxy]]
==== Create a Mule Proxy



//TODO: DOES THIS REQUIRE ADMIN ACCESS

. Meet the prerequisites in <<prereqs>>.
. Open API Manager to *API Administration* 

.. Click *Add API*, and select *Add new API*.
.. In the *Runtime* page that opens, click *Mule Gateway* and then click *Next*.
+
Retain the default settings on the *Runtime* page:

* *Proxy Type*: *Connect to existing application (basic endpoint)*
* *Mule version*: *Mule 4* 

.. Click *Connect to an existing application (basic endpoint)* to connect to a Mule app using API autodiscovery.
+
Alternatively, you can upload the API directly by using 
.. 

[[append-credentials]]
=== Append Credentials to Mule Runtime Settings

In Anypoint Code Builder, append the client ID and secret to you default Mule runtime arguments. Do not delete other settings.

//TODO: IS ONLY ONE CLIENT ID AND SECRET ALLOWED PER ACB INSTALLATION?

MULE_HOME/bin/mule \
-M-Danypoint.platform.client_id=XXXXXXXX \
-M-Danypoint.platform.client_secret=XXXXXXXX



[[config-element]]
=== Configuring the Autodiscovery Element in a Mule App

//see https://docs.mulesoft.com/mule-gateway/mule-gateway-config-autodiscovery-mule4#configuring-the-autodiscovery-element-in-your-mule-application


[[analytics-view]]
== View Analytics in API Manager

TODO_TODO_TODO

[[examples]]
=== Examples

Examples tested for API autodiscovery include the following:

* <<oas-spec>>:
+
Testing involved creating the spec in Design Center, publishing the spec to Exchange, creating an Mule Gateway API instance in API Manager that is associated with the spec on Exchange.
* <<mule-app>>
+
Testing involved adding the `<api-gateway:autodiscovery/>` element with the `apiID` value for the Mule Gateway API instance in API, appending the client ID and secret to the default Mule runtime arguments in Anypoint Code Builder, deploying the app locally by running the app in debug mode, making requests to the defined endpoint, and checking that the associated Mule Gateway instance on API Manager is *Active* and that the requests produce data (key metrics) in the instance's charts. 

[[oas-spec]]
==== Example: OAS Spec

The following OAS spec defines a single endpoint in the <<mule-app, Mule app example>>. 

[source,yaml]
----
openapi: "3.0.0" <!--1-->
info:
  version: 1.0.0
  title: my-autodiscovery-api
servers:
  - url: https://my-autodiscovery-app.us-e2.cloudhub.io
paths:
  /current-time: <!--2-->
    get:
      responses:
        "200":
          description: asd
          content:
            application/json:
              schema:
                type: object
                properties:
                  current-time:
                    type: string
              example:
                current-time: "2024-08-05 14:56:12"  <!--3-->
----
--
[calloutlist]
. OAS 3.0 specification
. `/current-time` endpoint definition
. Formatted example of a date-time value
--


[[mule-app]]
==== Example: Mule Application

[source,xml]
----
  <http:listener-config name="HTTP_Listener_config" > <!--1-->
    <http:listener-connection host="0.0.0.0" port="8081" />
  </http:listener-config>
  
<api-gateway:autodiscovery apiId="YOUR_API_ID_HERE" flowRef="currentTimeFlow" doc:name="Autodiscovery" /> <!--2-->

  <flow name="currentTimeFlow"> <!--3-->
        <http:listener path="/current-time" config-ref="HTTP_Listener_config" doc:name="Listener" doc:id="bce0d0-5b0387"/> <!--4-->
        <ee:transform doc:name="Transform" doc:id="ahlupg" > <!--5-->
            <ee:message>
                <ee:set-payload >
                <![CDATA[#[%dw 2.0
output application/json
---
{
	"current-time": now() as String {format: "yyyy-MM-dd hh:mm:ss"}
}]]]>
            </ee:set-payload>
            </ee:message>
        </ee:transform>
        <logger doc:name="Logger" doc:id="bhcobk" message="#[payload]"/> <!--6-->
  </flow>

----
--
[calloutlist]
. HTTP Listener connection configuration example
. Autodiscovery configuration that references the flow `currentTimeFlow`
+
If you try this app, replace `YOUR_API_ID_HERE` with the `apiID` value of an Mule Gateway instance associated with the <<OAS spec example, oas-spec>>. 
. Flow `currentTimeFlow`
. HTTP listener with endpoint configuration `path="/current-time"`
+
This endpoint matches the name of the endpoint defined in the <<OAS spec example, oas-spec>>.
. Transform Message component that uses DataWeave to get the current time in the specified format
+
The format matches the formats defined in the <<OAS spec example, oas-spec>>.
. Logger component that prints the current time (in the `payload`) upon requests to `http://localhost:8085/current-time` when the app is running
--

////
reminder API reqs
. Create supported API spec. (DC or elsewhere)
. Publish to Exchange. 
. From API Manager:
.. Click Add New API
.. Select Mule Gateway (from UI: "API gateway embedded in Mule runtime. Connect directly to an existing Mule app or deploy a new proxy app.")
. Connect to you API spec on Exchange. (be sure to use correct asset type -- TODO_TODO: can you use any of the asset types? or just RAML/OAS) 
. Click Next (bottom of page)

////


//TODO: EDIT THIS INTRO
include::mule-gateway::partial$autodiscovery-mule4.adoc[tags="autodiscovery-config-xml"]

//TODO: PROVIDE ACB STEPS