= Load and Run the Docker Image

To run Anypoint Code Builder you must install Docker in your machine and download the Anypoint Code Builder Docker image distribution.

== Before You Begin

* Install Docker Desktop in your machine. +
Follow the https://www.docker.com/get-started/[Docker Get Started Instructions^] for more information.
* Download the https://drive.google.com/file/d/1WTwn1sZZYVSVRmgYmiVuFkZCK9pee7cC/view[Anypoint Code Builder Docker image^]. +
* Ensure you have an Anypoint Platform account.

== Load The Anypoint Code Builder Image to Docker

Docker Desktop is an application for your macOS or Windows environment used to run and share containerized applications. During the beta 1 release, Anypoint Code Builder is a containerized application that you can run on your local machine using Docker Desktop.

To run the Anypoint Code Builder image on your local Docker installation:

. Open the Docker Desktop application.
. Open a terminal window and navigate to the directory where you downloaded the Anypoint Code Builder Docker image. For example:
+
[source,bash,linenums]
--
cd ~/Downlads/
--
. Run the following command to unzip the Docker image and load it to your Docker Desktop installation:
+
[source,bash,linenums]
--
gunzip -c mule-dx-dist-vxx.x.x.tar.gz \ //<1>
| docker load
--
<1> Replace `vxx.x.x` with the version of the Docker image you downloaded.
+
Note that this step might take several minutes to complete.
. In your Docker Desktop application, select *Images* from the left side navigation bar. +
Ensure that the Anypoint Code Builder image is loaded.
. Run the following command to start Anypoint Code Builder:
+
[source,bash,linenums]
--
docker run -i --rm --name mule-dx -d -p8080-8100:8080-8100 \
-v $HOME:$HOME \
artifacts.msap.io/mulesoft/mule-dx-dist:vxx.x.x \ //<1>
&& sleep 3 \
 && open http://localhost:8080
--
<1> Replace `vxx.x.x` with the version of the Docker image you downloaded.
. A new tab in your browser opens showing an instance of Anypoint Code Builder.
+
[NOTE]
--
Ensure to keep only one browser tab running Anypoint Code Builder. Multiple browser tabs cause the application to stall.
--

When you run Anypoint Code Builder for the first time, an instance of Mule Runtime Engine loads and requires you to reload your Anypoint Code Builder instance. When prompted, select *Reload*.

== Stop Running Anypoint Code Builder

Run the following command to stop your Anypoint Code Builder image:

[source,bash,linenums]
--
docker stop mule-dx
--
