= Mule Application Packaging

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

Anypoint Code Builder packages your Mule applications into deployable JAR files that you can later deploy to a running Mule runtime engine. The package contains the application and all its dependencies whether those be JAR files required by the application or by its plugins.

Every Mule application has two descriptors. These descriptors define your Mule application’s dependencies:

* A `mule-artifact.json` file. +
This file describes how your application is composed. +

* A `pom.xml` file. +
This file describes all the dependencies required by the package to work properly.


== Mule Application Structure Reference

At design time, your Mule application must have at least these three basic components:

[%header%autowidth.spread,cols=",,"]
|===
| Component | Type | Description
| `src`
| Folder
| The source directory for your application's productive source code and tests. +
See a reference for this folder below.

| `pom.xml`
| Descriptor
| The POM file of your Mule application. +
This file describes all of your application's required dependencies.


| `mule-artifact.json`
| Descriptor
| The mule-artifact file of your Mule application. +
This file describes how your Mule application is composed.

|===

These three components are mandatory. If one of them is missing, Anypoint Code Builder cannot package the project into a deployable JAR file. +
Additionally, the packaging process does not consider any other directory or file in the root folder of your Mule application.

== Source Directory Reference

The `src` directory has two main folders: `main` and `test`. +
The plugin does not consider any other directory inside `src` when packaging the application.

=== src/main

src/main is the root folder for all the productive source code of the application.

[%header%autowidth.spread,cols=",,"]
|===
|Folder  | Folder Type | Description

| `src/main/mule`
| source
| The root folder of the Mule configuration files. +
It can contain nested folders, in the way of Java packages.

This folder is mandatory.

| `src/main/resources`
| resource
| It contains the application resources, such as XML, JSON, and properties files. +
Jar files located here are loaded by the application classloader but as plain file resources.
|===

The packaging process sends all files inside `src/main/mule` and `src/main/resources` to the root directory of your binary package. +
Nested folders within `src/main/mule` are preserved as directories within the root directory of the binary package.

=== src/test

src/test is the root folder for all the test source code of the application.

[%header%autowidth.spread,cols=",,"]
|===
|Folder | Folder Type | Description

| `src/test/java`
| source
| It’s the root folder of the test classes used to validate the custom Java code of the app. +
It follows the conventions of any normal Java application.

| `src/test/munit`
| source
| It contains the MUnit source code. +
It can contain nested folders in the way of packages.

| `src/test/resources`
| resource
| It contains resources, such as XML, JSON,  and properties files. +
This folder also contains files describing metadata being referenced in the `mule-config.xml`.

|===

== See Also

* xref:package-mule-application.adoc[Package a Mule Application]
