= Export Mule Applications

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

Package Mule application resources in a sharable or deployable JAR file. A Mule application is an integration or implementation created with Anypoint Code Builder.

* A <<sharable, sharable JAR file>> is lightweight because it contains only the configuration files for the application and does not contain libraries or other dependencies defined in the POM file (`pom.xml`) that are required for your application to run and deploy successfully. You or your teammates can import the JAR file into Anypoint Studio (Studio) or into another Anypoint Code Builder instance. The IDEs generate the dependencies automatically based on the settings in the `pom.xml`.
+
Use the command `MuleSoft: Export Mule Application` for this purpose. This command works the same way as command sequence `Task: Run Task` > `mule` > `mule: Package Only Sources`, which takes the compiled code and packages its source code only.

//TODO: SAY MORE ABOUT SUPPORTED ENVIRONMENTS: CREATE STORY
* A <<deployable, deployable JAR file>> contains the compiled code and all dependencies. Deploy the JAR file to any supported environment, such as CloudHub or on-premises. 
+
Use the command `MuleSoft: Export Project to Mule Deployable Jar` for this purpose. This command works the same way as command sequence `Task: Run Task` > `mule` > `mule: Package Only Sources`, which packages the compiled code and all dependencies into a distributable JAR.. 

[[sharable]]
== Export to a Sharable JAR File

Export and package source files from your project into a light JAR file that you can share, import, and continue developing in Studio or Anypoint Code Builder. Typically, the JAR file is small because it provides the minimum resources required by the IDE. 

Source files include:

* The configuration XML and other files in the `src` folder, including resource files
* `mule-artifact.json`
* `pom.xml`

To package the source files only:

. Open a configuration XML in a project for a Mule application that you intend to export.
. Open the Command Palette by pressing Ctrl+Shift+p (Windows) or Cmd+Shift+p (Mac), and provide the following command:
+
[source,command]
----
MuleSoft: Export Mule Application
----
+
The terminal window in the IDE opens automatically to provide the status of the packaging process, which includes execution of the export command, a scan for the project to export, and the packaging of the project snapshot into a JAR file.
+
The file name for the JAR file follows the pattern `_application-name_-_version_-SNAPSHOT-_shareable_-mule-application.jar`, for example: `my-app-example-1.0.0-SNAPSHOT-shareable-mule-application.jar`.
. Find or download the JAR file by following the prompts that appear in the IDE after the packaging process completes successfully:

* In the desktop IDE, click *Open* to open you Explorer (Windows) or Finder (Mac) window to the directory that contains the JAR file.
+
The terminal window in the IDE also provides the path to the JAR.
* In the cloud IDE, click *Download* to download the JAR file to a directory on your local machine.
+
If the JAR file is larger than 32 MB, the folder must not be a built-in folder that contains system files, such as Downloads, Desktop, or Documents folders. 

To open a sharable JAR file in a project workspace within Anypoint Code Builder, see xref:upload-a-project.adoc[]. To import to Anypoint Studio, see xref::studio::import-export-packages.adoc[].

//TODO: HOW TO IMPORT TO STUDIO: xref::studio::import-export-packages.adoc[]??
//      https://docs.mulesoft.com/studio/7.15/import-export-packages

[[deployable]]
== Export to a Deployable JAR File

//TODO: NEED TO POINT TO INFO ON SUPPORTED DEPLOYMENT ENVIRONMENTS

Export a Mule application to a JAR file that you can deploy within a supported environment, such as CloudHub. 

. Open a configuration XML in a project for a Mule application that you intend to export.
. Open the Command Palette by pressing Ctrl+Shift+p (Windows) or Cmd+Shift+p (Mac), and provide the following command:
+
[source,command]
----
MuleSoft: Export Project to Mule Deployable Jar
----
+
The terminal window in the IDE opens automatically to provide the status of the packaging process, which includes execution of the export command, a scan for the project to export, and the packaging of the project snapshot into a JAR file.
+
The file name for the JAR file follows the pattern `_application-name_-_version_-SNAPSHOT-mule-application.jar`, for example: `my-app-example-1.0.0-SNAPSHOT-mule-application.jar`.
. Find or download the JAR file by following the prompts that appear in the IDE after the packaging process completes successfully:
* In the desktop IDE, click *Open* to open you Explorer (Windows) or Finder (Mac) window to the directory that contains the JAR file.
+
The terminal window in the IDE also provides the path to the JAR.
* In the cloud IDE, click *Download* to download the JAR file to a directory on your local machine.
+
If the JAR file is larger than 32 MB, the folder must not be a built-in folder that contains system files, such as Downloads, Desktop, or Documents folders. 

Deployment procedures vary by Mule runtime host and deployment model. For example, you can deploy to CloudHub through the Runtime Manager UI or REST API. See xref:hosting-home::index.adoc#runtime-plane-hosting-options.adoc[Runtime Plane Hosting Options] and xref:mule-runtime::deploying.adoc[] for more information.

//REMOVED Package a Lightweight JAR that Lacks Sources

== See Also

* xref:mule-runtime::package-a-mule-application.adoc[Package a Mule Application]
