= Set Up Source Control in Anypoint Code Builder
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

MuleSoft recommends that you use source control management (SCM) to store and share projects that you create with Anypoint Code Builder. A useful SCM provides change history of each file and a branching methodology to maintain project quality, full traceability, the ability to restore earlier versions of your files, and a way to recover source code if your Anypoint Code Builder environment is lost or removed. To learn more about branching strategies and working effectively with multiple team members, see the https://git-scm.com/book[Git documentation^].

This example shows how to use GitHub and Git to manage your Anypoint Code Builder source code. Although you can choose to use another source control management (SCM) system, GitHub and the Git command line interface (CLI) are widely used in the industry and supported out-of-the-box by VS Code. For more information, see https://code.visualstudio.com/docs/sourcecontrol/overview[Using Git source control in VS Code^] in the VS Code documentation. 
//TODO: DEPENDS ON FILE NAME CHANGE MERGE BEFORE UNCOMMENTING
//For additional source control options available only to API specifications that you import from Design Center, see xref:des-sync-scm.adoc[].

* <<prereqs>>
* <<create-repo>>
* <<config-git>>
* <<commit-source>>
* <<open-github>>
* <<start-project-from-git>>

[[prereqs]]
=== Before You Begin

Ensure that these prerequisites are in place:

* A GitHub account
+
If you do not have an account create one from the https://github.com/join[Join GitHub^] page on the GitHub site.

* A Git installation on your computer 
+
If Git is not installed on your computer, follow the https://github.com/git-guides/install-git[Git installation instructions^] for your machine.

* Access to Anypoint Code Builder from the desktop or cloud IDE
+
For setup and installation information, see xref:start-acb.adoc[], and be sure to meet all prerequisites. 

* A project in Anypoint Code Builder
+
For example, to create an integration project, see xref:int-create-integrations.adoc[].

[[create-repo]]
=== Create a Git Repository for Your Project

Start with an existing repository or create a new one. If you already have a Git repository that you can use for your project, proceed to <<config-git>>. 

Generally, one repository per project is useful for separate management of your projects, for example, to support your versioning needs or other project-specific requirements.

To create a repository for your project:

. Complete the form in the GitHub page https://github.com/new[Create a new repo^]:

* Determine a name for your repository, such as *acb-project-repo* or the name of your project.
* Create a *Private* repository so that others cannot view source files in your repository.
. Click *Create repository*.
. Proceed to <<config-git>>.

[[config-git]]
== Configure Your GitHub Properties

Check for and configure your username and email properties so that you can add, update, and retrieve your project files from your remote repository in GitHub. 

//open ACB terminal:
include::anypoint-code-builder::partial$acb-reusable-steps.adoc[tag="open-terminal"]
. From the Anypoint Code Builder terminal, check for any existing GitHub configuration by running this command:
+
[source,command]
----
git config --list
----

* If your GitHub `user.name` and `user.email` are listed, proceed to <<commit-source>>.
* If your GitHub `user.name` and `user.email` are not listed or if no data returns, configure the properties:

.. Run this command to set your `user.name`, replacing `YourUserName` with your GitHub username:
+
[source,command]
----
git config –-global user.name "YourUserName"
----
.. Run this command to set your `user.email`, replacing `your@email.com` with your GitHub email address:
+
[source,command]
----
git config –-global user.email "your@email.com"
----
+
If two-factor authentication is enabled on your GitHub account and you are prompted for a password, enter your personal access token instead of your GitHub login password. For more information, see GitHub documentation https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication[Access GitHub with 2FA^].
. Proceed to <<commit-source>>.

[[commit-source]]
== Commit Source Code Changes to Your Repository 

From the Anypoint Code Build terminal, commit your project files to your repository. 

//open ACB terminal:
include::anypoint-code-builder::partial$acb-reusable-steps.adoc[tag="open-terminal"]
. In the terminal echo "# my-new-acb-repo" >> README.md
. Initialize your GitHub repository within Anypoint Code Builder with this command:
+
[source,command]
----
git init
----
. Track all files in the current directory by entering this command:  
+
[source,command]
----
git add .
----
. Commit the added files to your local Git repository with this command:
+
[source,command]
----
git commit -m “first commit”
----
. Switch branches to the main branch.
+
[source,command]
----
git branch -M main
----
. Link your local repository to your remote repository, replacing `_yourusername_` with your Git username and `_yourrepository_` with your repository's name:
+
[source,command]
----
git remote add origin https://github.com/_yourusername_/_yourrepository_.git
----
. Push your project files to your repository.
+
[source,command]
----
git push -u origin main
----
. Proceed to <<open-github>>

[[open-github]]
== Find Your Project Files in GitHub

After completing <<commit-source>>, find your project files in your new repository.

. Log in to https://github.com/[GitHub^]. 
. In GitHub, navigate to your new project repository.
. Navigate to `src/main/mule` to view the configuration XML file (or files) for your project.
. Proceed to <<start-project-from-git>>

[[start-project-from-git]]
== Clone Your Git Repository into an Folder

After adding a project to your Git repository on GitHub, you can clone it into your desktop or cloud IDE. Cloning is helpful for retrieving a backup of a deleted project or for sharing your project in another Anypoint Code Builder IDE. For example, you can work on the same project in the desktop and cloud IDE if your project is stored in a Git repository. 



//open ACB terminal:
include::anypoint-code-builder::partial$acb-reusable-steps.adoc[tag="open-terminal"]
. Navigate to your home directory for Anypoint Code Builder. 
. Clone your GitHub repository into your new directory:
+
[source,command]
----
git clone https://github.com/_yourusername_/_yourrepo_.git
----
. Open the folder AnypointCodeBuilderGitHubDemo. Open the command palette and select File: Open Folder..



5. Select the directory that contains the new AnypointCodeBuilderGitHubDemo folder we just created.



6. Verify that your source code is available for you to continue to develop your MuleSoft integration


