= Configuring MuleSoft Settings in the IDE
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

//TODO: MuleSoft settings or Mule (project or runtime) settings only? 

Anypoint Code Builder provides configurable MuleSoft settings that apply across your projects. Many of the default settings are usually suitable. However, if you use the EU cloud, it is important to change the default US cloud setting. Some settings are configurable in the desktop IDE only.

//TODO: is this for Mule projects only or potentially for any ACB project, including design/api spec project?

To open the settings: 

//shared steps for opening Mule settings
include::partial$acb-reusable-steps.adoc[tags="open-mule-settings"]

For information about specific Mule settings, see the sections that follow.

////
HIDING EINSTEIN SECTION: NOT FOR FEB RELEASE
[[setting-einstein]]
==  Mule > Application: Einstein

If an organization administrator set permissions for you to access and use Einstein AI features, you can disable or enable (default) the feature in your IDE. When you disable Einstein, the UI no longer displays AI features.

For access to Einstein, see start-configure-permissions.adoc[].
////

[[setting-group-id]]
== Mule › Application: Group ID

Set the Maven group ID value for the IDE to use when you create a Mule integration or implementation project. This setting populates the `pom.xml` file for each Mule project. The default is `com.mycompany`, for example, `<groupId>com.mycompany</groupId>` in the `pom.xml`. You can change the setting within your project, as needed.

For information about Maven group IDs, see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Introduction to the POM^] in the Apache Maven Project documentation. 

[[setting-lsp]]
== Mule › Lsp › Trace: Server

Trace the communication between VS Code and the `muleLanguageServerProtocol` service. 

Available settings: 

* *off*: Default setting
* *messages*: //TODO: DESCRIPTION
* *verbose*: //TODO: DESCRIPTION

//TODO: what is muleLanguageServerProtocol and when would you want to use the settings? Do they interact with any other settings?

[[setting-mule-args]]
== Mule › Runtime: Default Arguments

Set default command-line arguments to use when starting Mule Runtime engine (Mule). Mule starts when you run a Mule application in an integration or implementation project. 

//TODO: Are there any we don't want people to touch

////
//TODO: TBD IF WE WANT TO PROVIDE THESE 
Default settings:

----
-M-Dmule.forceConsoleLog -M-Dmule.testingMode -M-XX:-UseBiasedLocking -M-Dfile.encoding=UTF-8 -M-XX:+UseG1GC -M-XX:+UseStringDeduplication -M-Dcom.ning.http.client.AsyncHttpClientConfig.useProxyProperties=true -M-Dmule.debugger.test.port=8000 -M-Dmule.debug.enable=true console0
----
//// 

Common uses are to append an encryption key value (such as `-M-Dencryption.key=my-key`) that is used when running a local deployment that incorporates secure configuration properties, or for a variable (such as `-M-Denv=dev`) that Mule uses when selecting a configuration properties file by its file name. For more information about these uses, see xref:int-create-secure-configs.adoc[]. 

[[setting-metaspace]]
== Mule › Runtime: Default Metaspace Size

Metaspace is an area for non-heap memory used to store class metadata, constant pool information, and method bytecode.

Typically, the default of *1g* (1 GB) is sufficient. However, you can change the metaspace size when installing Mule Runtime engine (Mule). 
//TODO: WHEN INSTALLING MULE FOR THE FIRST TIME ONLY, OR WHAT ABOUT WHEN UPDATING?

If you are using the cloud IDE, be aware of the memory available to the container before changing this value.
//TODO: HOW WOULD THEY KNOW 

[[setting-mule-home]]
== Mule › Runtime: Mule Home

When you update Anypoint Extension Pack version, the IDE extracts the latest supported Mule version to this directory. Typically, there is no need to change the default directory. 

In Windows, on the desktop IDE, avoid issues with long paths by using the default path or, if you need to change the path, install to a directory that is close to the root directory. 

Note that IDE uses the latest installed version of Mule. Selecting another version from the directory does not change the version that runs your apps.

[[setting-runtime-dir]]
== Mule › Runtime: Mule Runtimes Directory

Set the default download directory for different versions of Mule Runtime engine (Mule).

For example, the default directory in the desktop IDE on a Mac is similar to `/Users/me/muleRuntimes`. In the cloud IDE, the default is similar to `/home/me/muleRuntimes`. 

//TODO: can they change the directory in the cloud IDE?
////
POTENTIAL STORY
Mule › Runtime: Mule Runtimes Directory :  We have guidance on the use of the terms related to Mule here. “Mule runtimes” (plural) isn’t allowed. Could we use something like Mule › Runtime: Mule Runtime Engine Instance Directory, Mule Runtime Instance Directory, or even Mule Runtime Engine Directory, instead? Do we need to make it plural?
See https://confluence.internal.salesforce.com/display/MTDT/Term+Presentation+Reference
////

[[setting-region]]
== Mule: Control Plane

Select a control plane for your desktop IDE:

* *US Cloud* (default)
* *EU Cloud*

In the cloud IDE, this setting is not configurable because it is set automatically based on the region where your Anypoint Platform account resides. 

For more information, see xref:index.adoc#us-eu-clouds[US and EU Cloud Hosts].

[[setting-telemetry]]
==  Mule > Telemetry

Enable or disable telemetry services in the US cloud. When telemetry services are enabled, the IDE sends anonymous usage data to the MuleSoft team. The data helps the team identify important usage trends.

//TODO: CAN YOU SET IN CLOUD?
//TODO: What's the default? on or off?

[[setting-logging]]
==  Mule > Logging: Level

Set the verbosity of logs that appear in the Anypoint Code Builder extension and Mule DX Server logs. Verbosity options are progressive:

* Off: No issues 
* Fatal: Fatal issues only
* Error: Fatal and Error issues 
* Warn (default): Fatal, Error, and Warn issues  
* Info: Fatal, Error, Warn, and Info issues 
* Debug: Fatal, Error, Warn, Info, and Debug issues
* Trace: Fatal, Error, Warn, Info, Debug, and Trace issues

