= Configuring MuleSoft Settings in the IDE
:page-deployment-options: cloud-ide, desktop-ide

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

Anypoint Code Builder provides configurable MuleSoft settings that apply across your projects. Many of the default settings are usually suitable. However, if you use the EU cloud, it is important to change the default US cloud setting. Some settings are configurable in the desktop IDE only.

//TODO: is this for Mule projects only or potentially for any ACB project, including design/api spec project?

To open the settings: 

//shared steps for opening Mule settings
include::partial$acb-reusable-steps.adoc[tags="open-mule-settings"]

For information about specific Mule settings, see the sections that follow.

[[setting-einstein]]
==  Mule > Application: Einstein

If an organization administrator set permissions for you to access and use Einstein AI features, you can disable or enable (default) the feature in your IDE. When you disable Einstein, the UI no longer displays AI features.

For access to Einstein, see start-configure-permissions.adoc[].

[[setting-group-id]]
== Mule › Application: Group ID

//TODO: VERIFY

Set the Maven group ID value for the IDE to use when you create a Mule integration or implementation project. This setting populates the `pom.xml` file for each Mule project. The default is `com.mycompany`, for example, `<groupId>com.mycompany</groupId>` in the `pom.xml`. You can change the setting within your project, as needed.

For information about Maven group IDs, see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Introduction to the POM^] in the Apache Maven Project documentation. 

[[setting-lsp]]
== Mule › Lsp › Trace: Server

Trace the communication between VS Code and the `muleLanguageServerProtocol` service. 

Available settings: 

* *off*: Default setting
* *messages*: //TODO: DESCRIPTION
* *verbose*: //TODO: DESCRIPTION

//TODO: what is muleLanguageServerProtocol and when would you want to use the settings? Do they interact with any other settings?

[[setting-mule-args]]
== Mule › Runtime: Default Arguments

Set default command-line arguments to use when starting Mule Runtime engine (Mule). Mule starts when you run a Mule application in an integration or implementation project. 

//TODO: Are there any we don't want people to touch

////
//TODO: TBD IF WE WANT TO PROVIDE THESE 
Default settings:

----
-M-Dmule.forceConsoleLog -M-Dmule.testingMode -M-XX:-UseBiasedLocking -M-Dfile.encoding=UTF-8 -M-XX:+UseG1GC -M-XX:+UseStringDeduplication -M-Dcom.ning.http.client.AsyncHttpClientConfig.useProxyProperties=true -M-Dmule.debugger.test.port=8000 -M-Dmule.debug.enable=true console0
----
//// 

Common uses are to append an encryption key value (such as `-M-Dencryption.key=my-key`) that is used when running a local deployment that incorporates secure configuration properties, or for a variable (such as `-M-Denv=dev`) that Mule uses when selecting a configuration properties file by its file name. For more information about these uses, see xref:int-create-secure-configs.adoc[]. 

[[setting-metaspace]]
== Mule › Runtime: Default Metaspace Size

Set the metaspace size when installing Mule Runtime engine (Mule) for the first time. The default is *1g*. 

//TODO: What does 1g mean? 
////
//TODO: what is metaspace? When would someone change this? 
Are we talking about this?
Metaspace, formerly known as PermGen (Permanent Generation), is a non-heap memory area that stores class metadata, constant pool information, and method bytecode. It was introduced in Java 8 as a replacement for PermGen, which was removed due to memory management issues.
Source is medium.com: https://medium.com/@AlexanderObregon/introduction-to-javas-memory-model-heap-stack-and-metaspace-ceaeb565921c#:~:text=Metaspace%2C%20formerly%20known%20as%20PermGen,due%20to%20memory%20management%20issues
////
//TODO: would cloud IDE users ever need to set this? 

[[setting-mule-home]]
== Mule › Runtime: Mule Home

Set your local Mule Runtime engine (Mule) installation directory. This setting defaults //TODO: to the most current installation directory? 

//TODO: do we have any recommendations (i.e., using the latest release)?
//TODO: what is this for and when would you want to change it? 
//TODO: looks like there are 3 standalone Mule installations on my laptop. check cloud IDE. 
//TODO: do projects update to use the latest runtime installation?

[[setting-runtime-dir]]
== Mule › Runtime: Mule Runtimes Directory

Set the default download directory for different versions of Mule Runtime engine (Mule).

For example, the default directory in the desktop IDE on a Mac is similar to `/Users/me/muleRuntimes`. In the cloud IDE, the default is similar to `/home/me/muleRuntimes`. 

//TODO: can they change the directory in the cloud IDE?
////
POTENTIAL STORY
Mule › Runtime: Mule Runtimes Directory :  We have guidance on the use of the terms related to Mule here. “Mule runtimes” (plural) isn’t allowed. Could we use something like Mule › Runtime: Mule Runtime Engine Instance Directory, Mule Runtime Instance Directory, or even Mule Runtime Engine Directory, instead? Do we need to make it plural?
See https://confluence.internal.salesforce.com/display/MTDT/Term+Presentation+Reference
////

[[setting-region]]
== Mule: Control Plane

Select a control plane for your desktop IDE:

* *US Cloud* (default)
* *EU Cloud*

In the cloud IDE, this setting is not configurable because it is set automatically based on the region where your Anypoint Platform account resides. 

For more information, see xref:index.adoc#us-eu-clouds[US and EU Cloud Hosts].

[[setting-telemetry]]
==  Mule > Telemetry

Enable or disable telemetry services in the US cloud. When telemetry services are enabled, the IDE sends anonymous usage data to the MuleSoft team. The data helps the team identify important usage trends.

//TODO: CAN YOU SET IN CLOUD?
//TODO: What's the default? on or off?

[[setting-logging]]
==  Mule > Logging: Level

Set the verbosity of logs that appear in the logs. Verbosity options are progressive:

//TODO: WHICH LOGS? MS DX Server? Other? Where do you find the logs? Scope of logs (Mule projects or what)? I see logs in the Mule runtime folder (see Mule home above). Are Mule logs affected by this setting or just the UI or what?

* Off: No issues 
* Fatal: Fatal issues only
* Error: Fatal and Error issues 
* Warn (default): Fatal, Error, and Warn issues  
* Info: Fatal, Error, Warn, and Info issues 
* Debug: Fatal, Error, Warn, Info, and Debug issues
* Trace: Fatal, Error, Warn, Info, Debug, and Trace issues

