= Getting Started with Anypoint Code Builder
:page-deployment-options: cloud-ide, desktop-ide
:page-aliases: setup.adoc, connect-eu-cloud.adoc, load-acb-web-ide.adoc, log-in-anypoint-platform.adoc, get-started.adoc
:restart-ide: Restart the IDE to load all your changes. 

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

Anypoint Code Builder is built from the Anypoint Extension Pack for Visual Studio Code. Both the desktop and cloud IDEs for Anypoint Code Builder share these extensions. The cloud IDE provides built-in extensions to the code-server implementation of Visual Studio Code for the web.

* <<set-up-desktop>>: For the desktop IDE, you must load the extension pack to your local Visual Studio Code IDE. 
* <<set-up-web>>: For the cloud IDE, you must log in to Anypoint Platform and acquire the permission to use Anypoint Code Builder. 

[[set-up-desktop]]
== Set up the Desktop IDE

//start desktop IDE
include::anypoint-code-builder::partial$acb-start-desktop.adoc[]

[[set-up-web]]
== Launch the Cloud IDE 

//launch cloud IDE
include::anypoint-code-builder::partial$acb-start-cloud.adoc[]

[[change-clouds]]
== Set the Desktop IDE to the EU or US Cloud

In the desktop IDE, you can change your Anypoint Platform control plane to the US or EU cloud. US cloud is the default. Anypoint Platform instances do not share user accounts, projects, or other data. For more information, see xref:index.adoc#us-eu-clouds[US and EU Cloud Hosts]. 


//shared steps for opening Mule settings
include::anypoint-code-builder::partial$acb-reusable-steps.adoc[tags="open-mule-settings"]
include::anypoint-code-builder::partial$acb-reusable-steps.adoc[tags="mule-settings-nav-options"]
. Scroll to *Mule: Control Plane*.
. Select *US Cloud* or *EU Cloud*.
. {restart-ide}
. Follow the steps in xref:anypoint-code-builder::start-acb.adoc#login-ide[Log in to Anypoint Platform from the IDE].
