= Synchronize Changes with Design Center

Anypoint Code Builder has integrated source control management (SCM) and includes Git support.

You can use the integrated SCM in Anypoint Code Builder to synchronize your local API Right now our API specification is just stored locally. We need to push our changes to Anypoint Design Center.

When you change your API specification, the Source Control icon in the Activity Bar on the left shows you an overview of how many changes you currently have. Selecting the icon shows you the details of your current changes: *CHANGES*, *STAGED CHANGES*, and *MERGE CHANGES*.

== Before You Begin

* Ensure you set up your MuleSoft environment. +
See xref:setup.adoc[] for more information.
* You created a basic structure for your API specification. +
See xref:design-api-specification.adoc[].
* You configured request and response data for  your API specification. +
See xref:design-api-specification.adoc[].


== Reviewing Changes in Files

Anypoint Code Builder can highlight differences made in files since you last synchronized them with the main branch on Design Center.

. Navigate to your `exchange.json` file.
. Click the file; you will now see a working tree opened as an editor tab.
. Review the working tree and see how deletions (red) and additions (green) are highlighted.

In this case, you added some dependencies to our API by reusing API fragments we downloaded from Anypoint Exchange.

== Staging Your Changes Individually

The `git add` command adds a change from your working directory to the staging area. It tells Git that you want to include updates to a particular file in the next commit. In Anypoint Code Builder you can do this by using the buttons in the UI:

. Navigate to *Source Control*.
. Select the plus icon next to `american-flight-api.raml`.
. Review the changes in the *Source Control* panel. Note that the file has moved into *Staged Changes*.

Additionally, you can perform these actions using the embedded command line.

=== Staging Multiple Changes

You can add multiple files at the same time:

. Navigate to *Source Control*.
. Click the plus icon in the section header to stage the remaining changes.
. Review the changes in the *Source Control* panel. Note that the file has moved into *Staged Changes*.

Additionally, you can perform these actions using the embedded command line.

== Committing Changes

Use the `git commit` command to save the changes you staged earlier to your local repository:

. Navigate to *Source Control*.
. Click in the message box at the top of the panel.
. Enter a message that summarizes the change or changes being made. +
A good commit message helps summarize the changes being made across multiple files by multiple developers.
. To commit the changes click the tick mark in the *Source Control* header.
. Review the *Source Control* panel. Your changes have now disappeared and the *Source Control* button in the Activity Bar does not show any changes.


== Pushing changes to Anypoint Design Center

The git push command is used to upload local repository content to Anypoint Design Center.

. Navigate to *Source Control*.
. Select the three dots that appear in the *Source Control* header.
. Select *Push*.
. Enter your Anypoint Platform username and password when prompted. Wait for your changes to be synchronized successfully.
