= Test an API Specification Using Mocking Service

With a designed API specification, you can use Mocking Service to mock your API and test
the request and responses you designed in your API specification.

== Before you Begin

* Ensure you set up your MuleSoft environment. +
See xref:setup.adoc[] for more information.
* You created a basic structure for your API specification. +
See xref:design-api-specification.adoc[].
* You created request and response details for your API specification. +
See xref:add-request-response-details.adoc[Add Request and Response Details].

== Test your API Specification

. In API Console, select the `get` method for the `flights/` resource.
. Select the *Try It* button.
. Select the *destination* text box under *Query Parameters* and verify the 3 values you defined in your API specification show up.
. Select *Send*.
. Verify that API Console returns the response you defined with the imported fragment.

Additionally, you can review your configured response examples when querying your mocked API endpoints.

//TODO: Add Screenshots.
