= Troubleshoot Generative Flow

Errors sometimes occur when you use the Einstein Generative Flow feature.

== Unexpected Query Results

If the generative flow is not returning accurate and useful results for the prompts you enter, rewrite your prompt and follow the guidelines xref:int-create-integrations-ai.adoc#craft-ai-prompt[for crafting an effective prompt].

== Fixing Errors for Unknown Connectors

To fix errors for unknown connector operations, or operations from connectors that are not bundled with your project, use *Quick Fix* to search for that operation in Exchange. 

== Einstein Does Not Appear for EU Cloud Users on the Desktop IDE

If you are signed in to your Anypoint Platform account on the EU Cloud and Einstein doesn't appear in the UI, verify the following:

* You are signed in to Anypoint Platform through the Anypoint Code Builder app.
* xref:int-create-integrations-ai.adoc#before-you-begin[You have the required permissions].
* You completed the xref:start-acb.adoc#change-clouds[Set the Desktop IDE to the EU or US Cloud] procedure.

== Limitations

The Einstein Generative Flow feature works only when you have one project at a time open. It doesn't work if you have multiple projects open concurrently. 