= Test Your GraphQL Implementation
:page-deployment-options: cloud-ide, desktop-ide
:imagesdir: ../assets/images

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

With a scaffolded project, run your application locally and test the endpoints of your Mule application.

Note that because the GraphQL schema does not allow examples, Anypoint Code Builder scaffolds an empty project, so in this first run, your responses are empty.

== Before You Begin

Complete these procedures: 

* Set up your MuleSoft environment. +
See xref:setup.adoc[] for more information.
* Implement the Books API GraphQL Schema. +
See xref:tut-graphql-implement-api.adoc[].

== Run Your Application

To locally deploy your Mule Application, run a debug session in Anypoint Code Builder:

. In Anypoint Code Builder, open the *Books Implementation* project.
. Select *Run and Debug* in the Activity Bar, then press the *Start Debugging* icon.
. In the IDE's terminal, use the `curl` command, and create a `POST` request to the local address, adding the `/graphql` path: `+http://localhost:8081/graphql+`:
+
[source,curl]
--
curl --request POST \
--location 'http://localhost:8081/graphql' \
--header 'Content-Type: application/json' \
--data '{
    "query": "query bookById($id: ID) {bookById(id: $id){ id name pageCount author{ id firstName lastName}}}",
    "variables": {
        "id": 1
    }
}'
--
+
See xref:int-trigger-flows.adoc#trigger-flow[Trigger a flow] for guidance with triggering a localhost URL from the IDE's terminal.
. Send the `curl` request.
+
Anypoint Code Builder returns an empty field for the book:
+
[source,GraphQL]
--
{
    "data": {
        "bookById": null
    }
}
--
====

Other queries you can try for your endpoint are:

* Query `books`:
+
[source,GraphQL]
--
query books {
	books{
		id
		name
		pageCount
		author{
			id
			firstName
			lastName
		}
	}
}
--
* Query `bestSellers`
+
[source,GraphQL]
--
query bestsellers {
	bestsellers{
		books{
			id
			name
			pageCount
			author{
				id
				firstName
				lastName
			}
		}
		authors{
			id
			firstName
			lastName
		}
	}
}
--

All these requests will return an empty result.

== Next Step

* xref:tut-graphql-configure-flow-responses.adoc[]. +
Populate each flow with a custom response for each query.
