= Tutorials
:page-deployment-options: cloud-ide, desktop-ide
:page-aliases: user-guide.adoc

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//LOGO (web, desktop, or both)
// include::partial$acb-ide-logos.adoc[tags="both-ides"]

* xref:tut-af-amflights-overview.adoc[]: 
+
Use Anypoint Code Builder to design and implement an API specification example called American Flights API that returns flight information from a MySQL database.

* xref:tut-local-api-specification.adoc[]: 
+
Scaffold an API specification into an interface to implement within your IDE, and sync changes to the specification with the interface without first publishing to Anypoint Exchange. For example, after adding a new endpoint to your API specification, you can re-scaffold the change into the interface to add a flow for that endpoint to the interface's configuration XML file.

* xref:tut-graphql-implement-api.adoc[]:
+
Implement a GraphQL API that you publish to Exchange.

* xref:tut-slack-create-escalation-api.adoc[]: 
+
Create an integration that notifies you through email or Slack when a new case is created in Salesforce.
