= Tutorials
:page-aliases: user-guide.adoc

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"] 

//LOGO (web, desktop, or both)
include::partial$acb-ide-logos.adoc[tags="both-ides"]

xref:tut-am-flights-overview.adoc[]: 

Use Anypoint Code Builder to create an API specification example called American Flights API. In this API, reuse API fragments from Anypoint Exchange, create data types and response examples, test your API using API Console, save your API to Design Center, and publish the API as an asset to Exchange.

xref:tut-local-api-specification.adoc[]: +
Scaffold an API specification into an interface project within your IDE, and synchronize changes to the specification with the interface without first publishing to Anypoint Exchange. For example, after adding a new endpoint to your API specification, you can re-scaffold the change into the interface to add a flow for that endpoint to the interface’s configuration XML file.

xref:tut-graphql-implement-api.adoc[]: +
Implement a GraphQL API that you publish to Exchange.

xref:tut-contacts-create-synchronization-sfdc-api.adoc[]: +
Create an API specification that synchronizes your contacts database with Salesforce.

xref:tut-slack-create-escalation-api.adoc[]: +
Create an integration that notifies you through email or Slack when a new case is created in Salesforce.