= URLs to Allow to Run Anypoint Code Builder

Allow Anypoint Code Builder URLs in your client OS security settings to let the IDE work with the external and Anypoint Platform hosts.

== Allow Anypoint Code Builder URLs

Allow URLs to ensure the best performance in Anypoint Code Builder.

. Security and antivirus software
+
If you have security and antivirus software, add Anypoint Code Builder to the allowlist. Running real-time antivirus protection software on your operating system can have a negative impact on Anypoint Code Builder performance. Steps to solving these performance issues vary depending on your antivirus software.
+
Allowlist recommendation:
+
Allow or exclude from your antivirus software Anypoint Code Builder, its Java executables, and the Anypoint Code Builder installation and workspace file locations.

. Anypoint Code Builder directories
+
All Anypoint Code Builder users need read and write permissions for the directory where Anypoint Code Builder is installed.
+
If you use a Windows antivirus application, ensure that the plugins/ and features/ directories are under the trusted category.
+
Allowlist recommendation:
+
Allowlist the Anypoint Code Builder workspace folder in your client OS security settings. In Windows, allowlist the Windows default temp folder where Anypoint Code Builder stores temporary files.

. MuleSoft and Third-Party URLs

Allow these URLs so that they aren't blocked or interrupted by your organization's firewall or proxy.

[NOTE]
Some entries use a wildcard (*) to indicate that all subdomains must be allowed. The parent domain itself (e.g., anypoint.code-builder.platform.salesforce.com) may not resolve directly, as it serves as a base for specific service endpoints. This is expected behavior.


*MuleSoft*

1. MuleSoft Maven repositories and connectors update site 
** \https://*.anypoint.code-builder.platform.salesforce.com
2. Anypoint Code Builder update sites
** \https://*.anypoint.code-builder.platform.salesforce.com
3. Anypoint Platform services: CloudHub, Exchange, Core Services [Commcloud / Hyperforce]
** \https://*.anypoint.mulesoft.com
** \http://*.platform.mulesoft.com
4. Nexus
** \https://*.nexus.build.msap.io
5. All assets downloaded from Exchange
** \https://*.exchange2-asset-manager-kprod.s3.amazonaws.com
** \https://*.exchange2-asset-manager-kprod-eu.s3.eu-central-1.amazonaws.com
6. Resources for API Portals
** \https://*.exchange2-file-upload-service-kprod.s3.amazonaws.com

*Third-Party*

1. Maven
** \https://*.repo.maven.apache.org/maven2
** \https://*.repo1.maven.org/maven2
2. LaunchDarkly
** \https://*.clientstream.launchdarkly.com
** \https://*.clientsdk.launchdarkly.com
** \https://*.app.launchdarkly.com
** \https://*.events.launchdarkly.com
** \https://*.otel.observability.app.launchdarkly.com
** \https://*.pub.observability.app.launchdarkly.com
