= What's New


== June 2023


Anypoint Code Builder introduces important enhancements and fixes.

== Support for EU Cloud

EU Cloud users of Anypoint Platform can now use Code Builder from their management plane.

See xref:connect-eu-cloud.adoc[] for more information.


== Synchornization Between Local API Specification and Mule Project

You can now work work on your API specification and its Mule project implementation simultaneously.

Anypoint Code Builder enables you to scaffold your API specification into a Mule project without having to publish it to Exchange. You can work on your Mule project, then edit the API specification, and re-scaffold it to reflect your new changes. Both API design and API implementation tasks are now synchronized. You can then publish your API specification and deploy your Mule project from there.


== April 24, 2023

Anypoint Code Builder migrated to a new underlying architecture.

Your web IDE instance URL changed. You can get the new URL by launching the web IDE from the central page or checking the IDE details.

Additionally, your session cookie is now different, so you must update them if you are xref:ping-locally-deployed-app.adoc[Pinging A Locally Deployed App] from a REST client.


== April 2023


Anypoint Code Builder provides important enhancements and fixes.

// Upgrade your webIDE instance to benefit from all the improvements in this version

=== Business Group Support

Business groups provide more fine-grained control over access to resources. Code Builder introduces support for business groups when working with assets from Exchange.

See xref:business-group-support.adoc[] for more information.

=== Search Filters when Implementing an API

Code Builder introduces filters to refine your search results when looking for an API asset from Exchange to implement.

See xref:filter-search-results.adoc[] for more information.

=== Improved Canvas UI

Code Builder improves the Mule application design process enabling you to add components to your flow from the canvas.
