= What's New

== April 24, 2023

Anypoint Code Builder migrated to a new underlying architecture.

Your web IDE instance URL changed. You can get the new URL by launching the web IDE from the central page or checking the IDE details.

Additionally, your session cookie is now different, so you must update them if you are xref:ping-locally-deployed-app.adoc[Pinging A Locally Deployed App] from a REST client.


== April 2023


Anypoint Code Builder provides important enhancements and fixes.

// Upgrade your webIDE instance to benefit from all the improvements in this version

=== Business Group Support

Business groups provide more fine-grained control over access to resources. Code Builder introduces support for business groups when working with assets from Exchange.

See xref:business-group-support.adoc[] for more information.

=== Search Filters when Implementing an API

Code Builder introduces filters to refine your search results when looking for an API asset from Exchange to implement.

See xref:filter-search-results.adoc[] for more information.

=== Improved Canvas UI

Code Builder improves the Mule application design process enabling you to add components to your flow from the canvas.
