= Contributions Welcome

Before creating a pull request review the following:

* xref:LICENSE.txt[LICENSE.txt]
* xref:SECURITY.adoc[SECURITY.adoc]
* xref:CODE_OF_CONDUCT.adoc[CODE_OF_CONDUCT.adoc]

When you submit your pull request, you are asked to sign a contributor license agreement (CLA) if we don't have one on file for you.

Skip to main content
+200 points
Module
Build AI Models in Einstein Studio

Build, train, and evaluate your own predictive AI models in Einstein Studio.
0%
Progress: 0%%
+200 points
Module
Artificial Intelligence and Machine Learning with Google Cloud

Explore how organizations use AI and ML to transform their business processes.
0%
Progress: 0%%
+100 points
Module
Salesforce Premier Success Onboarding

Celebrate completing the Salesforce Premier Success Onboarding Program!
0%
Progress: 0%%
+200 points
Module
ApexGuru

Use AI and machine learning models to scan Apex code and get code recommendations.
0%
Progress: 0%%
+300 points
Module
External Client App Basics

Create an external client app, and package it for distribution.
0%
Progress: 0%%
+300 points
Module
Slack Solutions and Tools

Learn tips and tools for using Slack and be your most productive self at work.
0%
Progress: 0%%
+100 points
Module
Tableau Viz Extensions: Quick Look

Add custom viz types to your Tableau worksheets with Viz Extensions.
0%
Progress: 0%%
+200 points
Module
Einstein Conversation Mining Report Creation

Enhance customer engagement with insights from Einstein Conversation Mining Reports.
0%
Progress: 0%%
+200 points
Module
Tableau for Teaching

Teach data skills in the classroom with Tableau licenses and learning resources.
0%
Progress: 0%%
+400 points
Project
Connect Data Cloud to Copilot and Prompt Builder

Combine harmonized data and generative AI to create powerful interactions and automations.
0%
Progress: 0%%
+600 points
Module
Administrator Certification Maintenance (Spring '24)

Review Salesforce updates to maintain your Administrator certification.
50%
Progress: 50%%
complete
+200 points
Module
Integrated Care Management

Improve health outcomes and bridge care gaps with advanced care planning.
Completed 7/13/24
complete
+300 points
Module
Vehicle and Asset Management in Automotive Cloud

Customize pages to efficiently manage asset and vehicle information.
Completed 7/13/24
complete
+100 points
Module
Life Sciences Cloud: Quick Look

Transform clinical research, commercial operations, and patient services.
Completed 7/14/24
complete
+100 points
Module
Einstein Copilot for Tableau: Quick Look

See how Einstein Copilot for Tableau is your AI-powered assistant for exploring data.
Completed 7/12/24
complete
+500 points
Module
Deep Dive into Industries Order Management Decomposition

Discover how to decompose customer orders into suborders.
Completed 7/13/24
complete
+300 points
Module
Loyalty Management APIs

Integrate your loyalty program with external systems for a unified customer experience.
Completed 7/14/24
+100 points
Module
Drive Productivity with Einstein AI

Complete this trail to gain the skills you need to become proficient with Einstein AI.
0%
Progress: 0%%
complete
+400 points
Module
Data Cloud Use Cases

Get the most out of Data Cloud for Sales, Service, Marketing, and more.
Completed 7/15/24
+300 points
Module
Business Metrics and Insights with Tableau Pulse

Explore metrics, configure your digest, and use data insights to drive business decisions.
0%
Progress: 0%%
+300 points
Module
Financial Services Cloud Basics

Explore solutions to personalize engagement, streamline onboarding, and scale service.
0%
Progress: 0%%
+200 points
Module
The Value of Security Controls

Use security controls to drive risk-informed business decisions.
0%
Progress: 0%%
+200 points
Project
Quick Start: Create a Prompt Builder Flex Template

Integrate a flow and a Flex prompt template to generate a custom newsletter.
0%
Progress: 0%%
+100 points
Project
Quick Start: Create a Sales Email Prompt Template

Generate personalized, targeted emails at scale using a sales email prompt template.
0%
Progress: 0%%
+600 points
Project
Configure a Net Zero Cloud Org

Complete critical administrative tasks to prepare your Net Zero Cloud org.
0%
Progress: 0%%
Progress: 0%%
~10 hrs 10 mins•0%
