//
//tag::component-title[]

= Transform (<transform/>)

//end::component-title[]
//

//
//tag::component-short-description[]
//     Short description of the form "Do something..." 
//     Example: "Configure log messages anywhere in a flow."

Convert input data to a new output structure or format.

//end::component-short-description[]
//

//
//tag::component-long-description[]
DataWeave is the programming language for all expressions and data transformations in your integrations and implementations. The language offers function libraries and mechanisms for creating customizations, including your own functions, libraries, and data types. To learn the basics of DataWeave and experiment with DataWeave scripts, see https://dataweave.mulesoft.com/[DataWeave Tutorial and Playground^].

//end::component-long-description[]
//


//SECTION: COMPONENT XML
//
//tag::component-xml-title[]

[[component-xml]]
== Component XML

This component supports the following XML structure:

//end::component-xml-title[]
//
//
//tag::component-xml[]

[source,xml]
----
<ee:transform doc:name="Transform" doc:id="xnpgke" >
    <ee:message >
        <ee:set-payload ><![CDATA[%dw 2.0
output application/java
---
{
}]]></ee:set-payload>
        </ee:message>
    </ee:transform>
----

A single Transform component element (`<ee:transform/>`) can specify content for all parts of the Mule event:

* Mule message: `<ee:message/>` can contain `<ee:set-payload/>` and `<ee:set-attributes/>`.
* Mule variables: `<ee:variables/>` can contain one or more `<ee:set-variable/>` elements.
//end::component-xml[]
//
//tag::component-snippet-xml[]

[[snippet]]

=== Snippet XML

Snippet XML in Anypoint Code Builder serves as a customizable template for the component. 

[source,xml]
----
----

//end::component-snippet-xml[]
//
//
//
//
//TABLE: ROOT XML ATTRIBUTES (for the top-level (root) element)
//tag::component-xml-attributes-root[]

[%header,cols="1,3a"]
|===
| `<transform/>` Attributes 
| Description

| `doc:name` 
| Editable name for the component.

| `doc:id` 
| Automatically generated identifier for the component.

| `mode` 
| Specifies the DataWeave script execution mode. Accepted values: `immediate` or `deferred`. See xref:dataweave::dataweave-memory-management.adoc[DataWeave Memory Management] for additional information.
|===
//end::component-xml-attributes-root[]
//
//
//TABLE (IF NEEDED): CHILD XML ATTRIBUTES for each child element
//  Repeat as needed, adding the next number to the tag value. 
//  Provide intro text, as needed.
//tag::component-xml-child1[]

[%header, cols="1,3"]
|===
| Attributes | Description

| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.

|===
//end::component-xml-child1[]
//
//
//TABLE (IF NEEDED): GRANDCHILD XML ATTRIBUTES for each grandchild element
//  Repeat as needed, adding the next number to the tag value. 
//  Provide intro text, as needed.
//TAG
//tag::component-xml-descendant1[]
[%header, cols="1,3"]
|===
| Attributes | Description

| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.
| `attribute_here` | DESCRIPTION_HERE_WITH_DEFAULT_IF_AVAILABLE Defaults to `DEFAULT_HERE`.

|===
//end::component-xml-descendant1[]
//


//SECTION: EXAMPLES
//
//tag::component-examples-title[]

== Examples

The following examples show how to configure an inline transformations, call DataWeave scripts to apply a transformation. 
//end::component-examples-title[]
//
//
//tag::component-xml-ex1[]
[[example1]]

=== Example: Inline DataWeave Transformation

The following example sets the payload using an inline DataWeave script.

[source,xml]
----
<ee:transform 
  doc:id="747f74d4-cb66-4f8e-8222-24784e6863ae"
  doc:name="Transform" >
    <ee:message>
        <ee:set-payload>
          <![CDATA[%dw 2.0
            output application/xml
            ---
            example: {
                message @(id: "DSF-829"): "Hello World!",
                date: |2017-03-21|,
                items: 
                {
                    item1: 728,
                    item2: "14422"
                }
            }
          ]]>
       </ee:set-payload>
    </ee:message>
</ee:transform>
----

The DataWeave script within `<ee:set-payload/>` returns this XML output:

[source,output]
----
<example>
  <message id="DSF-829">Hello World!</message>
  <date>2017-03-21</date>
  <items>
    <item1>728</item1>
    <item2>14422</item2>
  </items>
</example>
----

//end::component-xml-ex1[]
//
//
//tag::component-xml-ex2[]
[[example2]]

=== Example: Calling an External DataWeave Script

The following example calls an external DataWeave script to set the payload. 

[source,xml]
----
<ee:transform doc:id="747f74d4-cb66-4f8e-8222-24784e6863ae"
  doc:name="Transform" doc:mode="immediate">
    <ee:message>
      <ee:set-payload resource="transform.dwl" />
    </ee:message>
</ee:transform>
----
//end::component-xml-ex2[]

//tag::component-xml-ex3[]

[[example3]]

=== Example: Payload, Attribute, and Variable Transformation

The following example creates transformations for the payload, an attribute, and a variable.

[source,xml]
----
<ee:transform 
  doc:id="747f74d4-cb66-4f8e-8222-24784e6863ae"
  doc:name="Transform" >
    <ee:message>
        <ee:set-payload>
        <![CDATA[%dw 2.0
        output application/json
        ---
        (payload map (value0, index0) -> 
        {
            id: value0.id,
            username: value0.username,
            address: 
            {
                street: value0.address.street
            },
            website: value0.website
        })]]>
        </ee:set-payload>
        <ee:set-attributes>
        <![CDATA[%dw 2.0
        output application/json
        ---
        {
            requestPath: attributes.requestPath
        }]]>
        </ee:set-attributes>
    </ee:message>
    <ee:variables>
        <ee:set-variable variableName="myVar">
            <![CDATA[%dw 2.0
            output application/json
            ---
            {
                a: payload[0].phone
            }]]>
        </ee:set-variable>
    </ee:variables>
</ee:transform>
----

Assume this payload:

[source,payload]
----
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  }
]
----

The script within `<ee:set-payload>` returns this JSON output:

[source, json]
----
[
  {
    "id": 1,
    "username": "Bret",
    "address": {
      "street": "Kulas Light"
    },
    "website": "hildegard.org"
  },
  {
    "id": 2,
    "username": "Antonette",
    "address": {
      "street": "Victor Plains"
    },
    "website": "anastasia.net"
  }
]
----

The script within `<ee:set-attributes/>` returns the request path in the HTTP header. For example, assume this metadata in the HTTP header:

[source, http header]
----
{
   Request path=/hellomule
   Raw request path=/hellomule
   Method=GET
   Listener path=/hellomule
   Local Address=/127.0.0.1:8081
   Query String=
   Relative Path=/hellomule
   Masked Request Path=null
   Remote Address=/127.0.0.1:61856
   Request Uri=/hellomule
   Raw request Uri=/hellomule
   Scheme=http
   Version=HTTP/1.1
   Headers=[
      host=localhost:8081
      connection=keep-alive
      cache-control=max-age=0
      sec-ch-ua="Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
      sec-ch-ua-mobile=?0
      sec-ch-ua-platform="macOS"
      upgrade-insecure-requests=1
      user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
      accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
      sec-fetch-site=none
      sec-fetch-mode=navigate
      sec-fetch-user=?1
      sec-fetch-dest=document
      accept-encoding=gzip, deflate, br
      accept-language=en-US,en;q=0.9
   ]
   Query Parameters=[]
   URI Parameters=[]
}
----

The 

 


//end::component-xml-ex3[]

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex2[]
//


//SECTION: ERROR HANDLING if needed
//
//tag::component-error-handling[]

// tag::metadata[]

The Transform component accepts input and output metadata for the Mule message payload, variable, or attribute. You can provide format-specific resources and settings for xref:dataweave::dataweave-formats.adoc[supported MIME types (formats)].
// end::metadata[]

[[error-handling]]
== Error Handling

ERROR_HANDLING_DETAILS_HERE

//end::component-error-handling[]
//


//SECTION: SEE ALSO
//
//tag::see-also[]

[[see-also]]
== See Also

* xref:dataweave::dataweave.adoc[DataWeave Language]
* xref:dataweave::dataweave-selectors.adoc[DataWeave Selectors]

//end::see-also[]
