//
//tag::component-title[]

= Dynamic Evaluate (<ee:dynamic-evaluate/>)

//end::component-title[]
//

//
//tag::component-short-description[]
//     Short description of the form "Do something..." 
//     Example: "Configure log messages anywhere in a flow."

Evaluates an expression to select a DataWeave script, and then executes the new script to generate a result.

//end::component-short-description[]
//

//
//tag::component-long-description[]
//TODO: Uncomment after Transform component doc is ready
//This behavior enables you to dynamically select the script, instead of hardcoding it into the xref:acb-component-transform.adoc[Transform Message component].

The script can use any of the usual xref:2.4@dataweave::dataweave-variables-context.adoc[predefined variables], such as `message`, `payload`,`vars`, or `attributes`, but you can also add custom ones by providing a set of key-value pairs.

//end::component-long-description[]
//


//SECTION: COMPONENT XML
//
//tag::component-xml-title[]

[[component-xml]]
== Component XML

This component supports the following XML structure:

//end::component-xml-title[]
//
//
//tag::component-xml[]

[source,xml]
----
<ee:dynamic-evaluate 
  expression="" 
  doc:name="Dynamic evaluate" 
  doc:id="ojfqoz">
  <ee:parameters>#[]</ee:parameters>
</ee:dynamic-evaluate> 
----

//end::component-xml[]
//
//tag::component-snippet-json[]

[[snippet]]

=== Snippet JSON

Snippet JSON in Anypoint Code Builder serves as a customizable template for the component. 

[source,xml]
----
SNIPPET_JSON_HERE
----

//end::component-snippet-json[]
//
//
//
//
//TABLE: ROOT XML ATTRIBUTES (for the top-level (root) element)
//tag::component-xml-attributes-root[]

Dynamic Evaluate (`<ee:dynamic-evaluate/>`) attributes are configurable through the UI and XML.

[%header,cols="1,1,3a"]
|===
| Attribute Name
| Attribute XML 
| Description

| *Dynamic evaluate* (default)
| `doc:name` 
| Editable name for the component to display in the canvas.

| N/A
| `doc:id` 
| Automatically generated identifier for the component.

| *Expression*
| `expression` 
| Expression that selects a DataWeave script that Mule executes, for example, `expression="#[vars.generateOrderScript]"`.

| *Additional Bindings*
| `parameters`
//TODO: NO DESCRIPTION AVAILABLE
| N/A

| *Target Variable*
| `target`
| 
include::partial$acb-component-info.adoc[tag=target-variable]
include::partial$acb-component-info.adoc[tag=xref-target-variables]

| *Target Value*
| `targetValue`
| 
include::partial$acb-component-info.adoc[tag=target-variable-value]
include::partial$acb-component-info.adoc[tag=xref-target-variables]

|===
//end::component-xml-attributes-root[]
//
//
//TABLE (IF NEEDED): CHILD XML ATTRIBUTES or ELEMENTS
//tag::component-xml-attributes-child1[]

`<ee:parameters/>` is a child element of Dynamic Evaluate.

[%header,cols="1,3a"]
|===
| Child Element 
| Description 

|`<ee:parameters/>`
| Key-value pairs that serve as parameters that the DataWeave script can evaluate, for example, `<ee:parameters>#[{name: attributes.queryParams.userName}]</ee:parameters>`.

|===
//end::component-xml-attributes-child1[]
//
//

//SECTION: EXAMPLES
//
//tag::component-examples-title[]

== Example
//end::component-examples-title[]
//
//
//tag::component-xml-ex1[]
[[example1]]

The following example selects a script from a database through a `userId` query parameter and stores that script in a `userScript` variable. Dynamic Evaluate (`<ee:dynamic-evaluate/>`) accesses the `userScript` variable to invoke the script by using the provided parameter `name`, which contains the value of `attributes.queryParams.userName`.

[source,xml,linenums]
----
<flow name="dynamic-evaluate-example-flow">
  <http:listener config-ref="HTTP_Listener_Configuration" path="/"/>
  <!-- This SQL query uses queryParams.userId to dynamically select a DataWeave script stored in a Database,
  and then assign this script to target variable userScript-->
  <db:select config-ref="dbConfig" target="userScript">
    <db:sql>#["SELECT script FROM SCRIPTS WHERE ID = $(attributes.queryParams.userId)"]</db:sql>
  </db:select>
  <!-- The dynamic evaluate component executes the script stored in vars.userScript-->
  <ee:dynamic-evaluate expression="#[vars.userScript]">
    <!-- This line sets a parameter called 'name', so the expression in the Dynamic Evaluate component can use it -->
    <ee:parameters>#[{name: attributes.queryParams.userName}]</ee:parameters>
  </ee:dynamic-evaluate>
</flow>
----

Assume that the scripts `lsalander` and`mblomkvist` are stored in this example's database:

.Example: lsalander script
----
output application/json
---
{
  message: "Order " ++ attributes.queryParams.orderId ++ " has been received from " ++ name,
  items: payload.items
}
----

.Example: mblomkvist script
----
output application/x-www-form-urlencoded
---
{
  message: "Order " ++ attributes.queryParams.orderId ++ " has been received from " ++ name,
  items: payload.items
}
----

=== Example Application Behavior

When Mule application <<example1, example>> receives `lsalander` as the `queryParams.userId` in the request, Mule executes the `lsalander` script, which results in a JSON response. If the application receives `mblomkvist` as the `queryParams.userId` value, Mule executes a different script that generates a `x-www-form-urlencoded` response.

The example demonstrates how the response type can be parameterized based on the user, but the entire response can be parameterized to suit user needs.
//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex1[]
//
//
//tag::component-xml-ex2[]
[[example2]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex2[]
//


//SECTION: ERROR HANDLING if needed
//
//tag::component-error-handling[]

[[error-handling]]
== Error Handling

ERROR_HANDLING_DETAILS_HERE

//end::component-error-handling[]
//


//SECTION: SEE ALSO
//
//tag::see-also[]

[[see-also]]
== See Also

* xref:2.4@dataweave::index.adoc[]

//end::see-also[]