//
//tag::component-title[]

= Scatter-Gather  (<scatter-gather/>)
:component-filename: scatter-gather

//end::component-title[]
//

//
//tag::component-short-description[]

Process a Mule event through two or more routes, and combine the results into a single event object.

//end::component-short-description[]
//

//
//tag::component-long-description[]
Scatter Gather sends a request to multiple targets concurrently. This component collects the responses from all routes and aggregates them into a single message.

Each route runs on a separate thread to sequentially execute one or more processors (either a connector operation or Mule component). By default, each route runs in parallel. After each route completes successfully, the component combines the resulting Mule events into a new Mule event object that travels to the next processor in the flow.

Repeatable streams are a Mule feature that enables a component to reread a stream. Non-repeatable streams can be read only once before they are lost. By default, Mule components return a repeatable stream unless their streaming strategy is configured to be non-repeatable.

This component can process only repeatable streams and _cannot_ process a non-repeatable stream. If Scatter-Gather receives a non-repeatable stream as input from an upstream component that is configured with such a strategy, Scatter-Gather cannot process it.

//end::component-long-description[]
//


//SECTION: COMPONENT XML
//
//tag::component-xml-title[]

[[component-xml]]
== Component XML

This component supports the following XML structure: 

//end::component-xml-title[]
//
//
//tag::component-xml[]

[source,xml]
----
<scatter-gather doc:name="Scatter-Gather" 
  doc:id="24d159a9" 
  timeout="0" 
  target="myTarget" 
  maxConcurrency="10">
    <route >
      <!-- one or more processors here -->
    </route>
    <route >
      <!-- one or more processors here -->
    </route>
</scatter-gather>
----

//end::component-xml[]
//
//
//TABLE: ROOT XML ATTRIBUTES (for the top-level (root) element)
//tag::component-xml-attributes-root[]

Scatter Gather (`<scatter-gather/>`) attributes are configurable through the UI and XML.

[%header,cols="1,1,3a"]
|===
| Attribute Name
| Attribute XML 
| Description

| *Scatter gather* (default)
| `doc:name` 
| Editable name for the component to display in the canvas.

| N/A
| `doc:id` 
| Automatically generated identifier for the component.

| *Timeout*
| `timeout` 
| Sets the timeout for responses from sent messages, in milliseconds. A value of `0` or less than `0` prevents a timeout. Defaults to `0`. 

| *Max concurrency*
| `maxConcurrency` 
| Sets the maximum number of routes to run concurrently.

By default, all routes run in parallel. Setting this value to `1` makes the component process the routes sequentially.

//TODO: IS THERE DOC FOR THIS?
| *Collect list* 
| N/A
| N/A

| *Target Variable*
| `target`
| 
include::partial$acb-component-info.adoc[tag=target-variable]
include::partial$acb-component-info.adoc[tag=xref-target-variables]

| *Target Value*
| `targetValue`
| 
include::partial$acb-component-info.adoc[tag=target-variable-value]
The default value is `#[payload]`. 

include::partial$acb-component-info.adoc[tag=xref-target-variables]
|===


//end::component-xml-attributes-root[]
//
//
//TABLE (IF NEEDED): CHILD XML ATTRIBUTES or ELEMENTS
//tag::component-xml-attributes-child1[]

`<route/>` is a child element of Scatter Gather. 

[%header,cols="1,3a"]
|===
| Child Element 
| Description 

|`<route/>`
| Accepts one or more components as child elements for processing the Mule event. Multiple `<route/>` configurations are allowed.
|===
//end::component-xml-attributes-child1[]
//
//


//SECTION: EXAMPLES
//
//tag::component-examples-title[]

== Examples

//end::component-examples-title[]
//
//
//tag::component-xml-ex1[]
[[example1]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex1[]
//
//
//tag::component-xml-ex2[]
[[example2]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex2[]
//


//SECTION: ERROR HANDLING if needed
//
//tag::component-error-handling[]

[[error-handling]]
== Error Handling

This component can throw the following errors:

* `MULE:ROUTING`
* `MULE:COMPOSITE_ROUTING`

If you configure a timeout for this component and a route does not complete processing before the timeout expires, the route throws a `MULE:TIMEOUT` error. Mule handles this error as it handls other errors generated from a route: After each route completes (either by processing successfully or by throwing a `MULE:TIMEOUT` error), the successful results and errors are collected into the `MULE:COMPOSITE_ROUTING` error and then processed within a configured error handler component.

//end::component-error-handling[]
//


//SECTION: SEE ALSO
//
//tag::see-also[]

[[see-also]]
== See Also

//TODO: point to Mule variable doc 
* xref:4.4@mule-runtime::about-components.adoc[]
* xref:4.4@mule-runtime::transaction-management.adoc#tx_scopes_routers[How Transactions Affect Scopes and Routers]
* xref:4.4@mule-runtime::error-handling.adoc[]
* xref:4.4@mule-runtime::try-scope-concept.adoc[]
* xref:4.4@mule-runtime::about-mule-event.adoc[]

//end::see-also[]