//
//tag::component-title[]

= Error Handler (<error-handler/>)

//end::component-title[]
//

//
//tag::component-short-description[]
//     Short description of the form "Do something..." 
//     Example: "Configure log messages anywhere in a flow."

Catches an error thrown by the Mule application and routes it to the first On-Error component configuration that matches the error type. 

//end::component-short-description[]
//

//
//tag::component-long-description[]

The Error Handler component has two child elements, On Error Continue and On Error Propagate, which enable you to configure routes that execute when the error raised in the application matches the type of error configured in the handler. Each handler has its own behavior and works relative to the component that contains it (a Flow or a Try scope):

* On Error Continue (`on-error-continue`): executes and uses the result of the execution as the result of its container element (as if the container completed the execution successfully). Any transactions at this point commit successfully.

* On Error Propagate (`on-error-propagate`): rolls back any transactions, executes, and uses that result to rethrow the existing error. In this case, the container element "fails" its execution.

If there's no error handling configuration that matches the error, the app follows a default error handling process. See xref:4.4@mule-runtime::error-handling.adoc#default_error_handling[Using Default Error Handling for Messages] for more information.

//end::component-long-description[]
//


//SECTION: COMPONENT XML
//
//tag::component-xml-title[]

[[component-xml]]
== Component XML

This component supports the following XML structure:

//end::component-xml-title[]
//
//
//tag::component-xml[]

[source,xml]
----
<flow name="myFlow">

    <error-handler>
      <on-error-propagate name="onErrorPropagate" >
        <!-- error handling logic -->
      </on-error-propagate>
      <on-error-continue name="onErrorContinue" >
        <!-- error handling logic -->
      </on-error-continue>
    </error-handler>

</flow>
----

//end::component-xml[]
//
//tag::component-snippet-json[]

[[snippet]]

Snippet JSON in Anypoint Code Builder serves as a customizable template for the component. 

[source,xml]
----
SNIPPET_JSON_HERE
----

//end::component-snippet-json[]
//
//
//
//
//TABLE: ROOT XML ATTRIBUTES (for the top-level (root) element)
//tag::component-xml-attributes-root[]

Error Handler (`<error-handler/>`) attributes are configurable through the UI and XML.

[%header,cols="1,1,3a"]
|===
| Attribute Name
| Attribute XML 
| Description

| *Error handler* (default)
| `doc:name` 
| Editable name for the component to display in the canvas.

| N/A
| `doc:id` 
| Automatically generated identifier for the component.

|===
//end::component-xml-attributes-root[]
//
//
//TABLE (IF NEEDED): CHILD XML ATTRIBUTES or ELEMENTS
//tag::component-xml-attributes-child1[]

The `<on-error-continue/>` and `<on-error-propagate/>` child elements share the following attributes:

[%header,cols="1,1,3a"]
|===
| Attribute Name
| Attribute XML 
| Description

| *When*
| `when` 
| A matching expression that defines the condition to trigger the execution of this on-error strategy. The expression must evaluate to a Boolean value (`true` or `false`).

| *Type*
| `type` 
| A comma-separated list of Mule error types that defines the errors this on-error strategy handles.

| *Log exception*
| `logException` 
| Specifies whether to log the error at level `ERROR` before this strategy handles it. Defaults to `true`.

| *Enable notifications*
| `enableNotifications` 
| Specifies if this strategy triggers a notification of type `ExceptionNotification` when an error occurs. Defaults to `true`.
|===
//end::component-xml-attributes-child1[]
//

//SECTION: EXAMPLES
//
//tag::component-examples-title[]

== Error Handling Example

//end::component-examples-title[]
//
//
//tag::component-xml-ex1[]
[[example1]]

The following example configures handlers to produce `{ "MyError": "value was expected to be null" }` for a `VALIDATION:NOT_NULL`
error and `{ "messageANY" : "Some other error" }` for other error types. 

[source,xml,linenums]
----
<error-handler >
  <on-error-continue
    enableNotifications="true"
    logException="true"
    type="VALIDATION:NOT_NULL">
    <ee:transform >
      <ee:message>
        <ee:set-payload>
        <![CDATA[%dw 2.0
        output application/json
        ---
        {
        MyError : error.description as String
        }]]>
        </ee:set-payload>
      </ee:message>
    </ee:transform>
  </on-error-continue>
  <on-error-continue
    enableNotifications="true"
    logException="true"
    type="ANY">
    <ee:transform>
      <ee:message >
        <ee:set-payload >
        <![CDATA[%dw 2.0
        output application/json
        ---
        {
        "messageANY" : "Some other error"
        }
        ]]>
        </ee:set-payload>
      </ee:message>
    </ee:transform>
  </on-error-continue>
</error-handler>
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex1[]
//
//
//tag::component-xml-ex2[]
[[example2]]

The following example ACTION_VERB_HERE_WITH_DESCRIPTION_OF_WHAT_IT_DOES_OR_SHOWS

[source,xml]
----
< EXAMPLE_XML_HERE />
----

//OPTIONAL: SHOW OUTPUT IF HELPFUL
//The example produces the following output: 

//OUTPUT_HERE 

//end::component-xml-ex2[]
//


//SECTION: ERROR HANDLING if needed
//
//tag::component-error-handling[]

[[error-handling]]
== Error Handling

ERROR_HANDLING_DETAILS_HERE

//end::component-error-handling[]
//


//SECTION: SEE ALSO
//
//tag::see-also[]

[[see-also]]
== See Also

* xref:4.4@mule-runtime::mule-error-concept.adoc[Mule Errors]
* xref:4.4@mule-runtime::mule-server-notifications[Mule Runtime Engine Notifications]

//end::see-also[]
