//
// tag::maven-settings-custom[]

Use the Apache Maven file `settings.xml` to configure the Maven settings, such as repositories, proxy settings, and credentials. For detailed information, see https://maven.apache.org/settings.html[Settings Reference] in the Apache Maven documentation.

If `settings.xml` isn't found in that path, the IDE creates an empty `settings.xml` file in the default location, `${user.home}/.m2/repository`. 

// end::maven-settings-custom[]
//

//
// tag::maven-acb-settings-file[]

Anypoint Code Builder reads its configuration from your Maven `settings.xml` file. To configure Maven, for example, to add repositories, proxies, or credentials, edit your `settings.xml` file, usually located in your `~/.m2/` directory.

If you troubleshoot a project in Anypoint Code Builder, export the file with any sensitive information, such as passwords, obfuscated. See xref:anypoint-code-builder::troubleshooting.adoc#export-troubleshooting-info[Export Troubleshooting Information] for instructions.

// end::maven-acb-settings-file[]
//

//
// tag::nav-to-maven-settings[]
Navigate to `settings.xml`, typically in `{user.home}/.m2/`.
+
If `settings.xml` does not exist, create it.
// end::nav-to-maven-settings[]
//


//
// tag::pom-releases-ee[]
. Specify `repository` settings _within_ `<repositories></repositories>`.
+
[source,xml]
----
<profiles>
...
    <profile>

        <id>Mule</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <repositories>
            <repository>
                <id>MuleRepository</id>
                <name>MuleRepository</name>
                <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
                <layout>default</layout>
                <releases>
                    <enabled>true</enabled>
                </releases>
                <snapshots>
                    <enabled>true</enabled>
                </snapshots>
            </repository>
        </repositories>

    </profile>
...
</profiles>
----
+
For more information, see xref:mule-runtime::maven-reference.adoc#configure-maven-to-access-mulesoft-enterprise-repository[Configure Maven to Access MuleSoft Enterprise Repository].
// end::pom-releases-ee[]
//
