
//
// tag::runtime-java-download[]
You can select any of the supported Mule runtime and Java versions. The IDE saves your version settings to the project's `mule-artifact.json` file.
// end::runtime-java-download[]
//
//
//
// tag::runtime-version-note[]
For information about version support and automated Mule patch updates, see xref:acb-release-notes.adoc#versions-mule-jdk[Mule and Java version support]. 
// end::runtime-version-note[]
//
//
//
// tag::runtime-java-defaults[]
To set default Mule runtime and Java versions for the projects you create, see xref:anypoint-code-builder::int-versions.adoc[].
// end::runtime-java-defaults[]
//

//
// tag::runtime-java-notification[]
The IDE provides a notification if it is necessary to download the selected Mule runtime or Java version for the project. Mule runtime downloads to `${user.home}/AnypointCodeBuilder/runtimes`, and the selected Java version downloads to `${user.home}/AnypointCodeBuilder/java`.
// end::runtime-java-notification[]
//

//
// tag::runtime-java-missing[]
If a Mule runtime or Java configuration is missing, set the versions to use from the canvas. 
// end::runtime-java-missing[]
//


//
// tag::runtime-java-version-selection[]
. Select a Mule runtime version.
. Select a Java version.
// end::runtime-java-version-selection[]
//

//
// tag::open-project-properties-command[]
. Run the following command to open the *Project Properties* tab:
+
[source,command]
--
MuleSoft: Project Properties
--
// end::open-project-properties-command[]
//

//
// tag::open-project-properties-menu[]
. In the Explorer, right-click a configuration XML file in your project directory, and select *Project Properties* from the menu.
//TODO: P3: ADD SCREENSHOT
// end::open-project-properties-menu[]
//