//
// tag::runtime-java-versions-supported[]
//TBD IF WE USE THIS

|===
| Mule runtime version | Java version 
| Mule 4.6 | 1.8.0, 11, 17
| Mule 4.5 | 1.8.0, 11
| Mule 4.4 | 1.8.0, 11
|===

// end::runtime-java-versions-supported[]
//


//
// tag::runtime-java-download[]
You can select any of the supported versions. The IDE saves your version settings to the project's `mule-artifact.json` file.
include::anypoint-code-builder::partial$acb-runtime-java.adoc[tags="runtime-java-defaults"]
// end::runtime-java-download[]
//

//
// tag::runtime-java-defaults[]
To set default Mule runtime and Java versions for the projects you create, see xref:ref-mule-settings.adoc[].
// end::runtime-java-defaults[]
//

//
// tag::runtime-java-notification[]
The IDE provides a notification if it is necessary to download the selected Mule runtime or Java version for the project. Mule runtime downloads to `${user.home}/AnypointCodeBuilder/runtimes`, and the selected Java version downloads to `${user.home}/AnypointCodeBuilder/java`.
// end::runtime-java-notification[]
//

//
// tag::runtime-java-missing[]
If a Mule runtime or Java configuration is missing, set the versions to use from the canvas. 
// end::runtime-java-missing[]
//


//
// tag::runtime-java-version-selection[]
. Select a Mule runtime version.
. Select a Java version.
// end::runtime-java-version-selection[]
//

//
// tag::open-project-properties-command[]
. Provide the following command to open the *Project Properties* tab:
+
[source,command]
--
MuleSoft: Project Properties
--
// end::open-project-properties-command[]
//

//
// tag::open-project-properties-menu[]
. In the Explorer, right-click a configuration XML file in your project directory, and select *Project Properties* from the menu.
//TODO: P3: ADD SCREENSHOT
// end::open-project-properties-menu[]
//