
//
// tag::export-mule-projects-from-studio[]
== Export a Mule Project to a Sharable JAR File in Anypoint Studio

. Open the project to export in Anypoint Studio.
. Select *Export* from the *File* menu.
. In the Import wizard, click to expand the Mule folder, select *Anypoint Studio Project to Mule Deployable Archive (includes Studio metadata)*, and click *Next*.
. Select the project that you want to export and click *Next*.
. In the *JAR file* menu, click the ellipses (...) button to explore your local drive, and select the folder to which you want to export your deployable JAR file. +
Additionally, you can choose *Attach Project Sources* to include metadata that Studio requires to reimport the deployable file as an open Mule project into your workspace.
+
You must keep the *Attach Project Sources* option selected to be able to import the packaged JAR file back into a Studio workspace. This is the same as using the `-DattachMuleSources` flag when packaging using the Mule Maven Plugin. See xref:mule-runtime::mmp-concept.adoc#create-an-application-package-to-import-into-anypoint-studio[Create an Application Package to Import into Anypoint Studio] in the Mule Maven Plugin documentation for more information.

// end::export-mule-projects-from-studio[]
//

//
// tag::import-mule-project-into-acb[]
== Import a Mule Project from a Sharable JAR File in Anypoint Code Builder

Import a shareable JAR file for a snapshot of a Mule project into the desktop IDE.

To create a shareable JAR file, see xref:int-export-mule-project.adoc#shareable[Export to a Shareable JAR File].
The contents are lightweight because they don't include dependencies.
The IDE generates the dependencies configured in the `pom.xml` for the project. 

To import a shareable JAR file in your desktop IDE:

. Ensure that no project is open in the IDE.
// include for this procedure
include::partial$acb-open-packaged-sources.adoc[tags="open-command-palette-desktop"]
include::partial$acb-open-packaged-sources.adoc[tags="load-shareable-jar"]
. If your Mule project folder is closed, <<both-open-project-folder, open a workspace>> for the project at the project's _root_ directory.
+
include::partial$acb-open-packaged-sources.adoc[tags="import-note"]
//step: test project
include::partial$acb-open-packaged-sources.adoc[tags="test-project"]

// end::import-mule-project-into-acb[]
//