
//
// tag::runtime-java-download[]
You can select from locally available Mule runtime and Java versions. The dropdown shows only the Mule runtime versions that are installed on your local disk, including bundled Mule runtime versions that are available immediately after installation. The IDE saves your version settings to the project's `mule-artifact.json` file. Bundled Mule runtime versions enable instant project opening and design. To install additional Mule runtime versions, use the `MuleSoft: Install Runtime` command.
// end::runtime-java-download[]
//
//
//
// tag::runtime-version-note[]
For information about version support and automated Mule patch updates, see xref:acb-release-notes.adoc#versions-mule-jdk[Mule and Java version support]. 
// end::runtime-version-note[]
//
//
//
// tag::runtime-java-defaults[]
To set default Mule runtime and Java versions for the projects you create, see xref:anypoint-code-builder::int-versions.adoc[].
// end::runtime-java-defaults[]
//

//
// tag::runtime-java-notification[]
Projects open instantly using the bundled Mule runtime versions. The IDE provides a notification only if you must download a specific Mule runtime version or Java version for running or debugging your application. The Mule runtime versions downloads to `${user.home}/AnypointCodeBuilder/runtimes`, and the selected Java version downloads to `${user.home}/AnypointCodeBuilder/java`.
// end::runtime-java-notification[]
//

//
// tag::runtime-java-missing[]
If a Mule runtime or Java configuration is missing, set the versions to use from the canvas. 
// end::runtime-java-missing[]
//


//
// tag::runtime-java-version-selection[]
. Select a Mule runtime version.
. Select a Java version.
// end::runtime-java-version-selection[]
//

//
// tag::open-project-properties-command[]
. Run this command to open the *Project Properties* tab:
+
[source,command]
--
MuleSoft: Open Mule Project Properties
--
// end::open-project-properties-command[]
//

//
// tag::open-project-properties-menu[]
. In the Explorer, right-click a configuration XML file in your project directory, and select *Project Properties* from the menu.
//TODO: P3: ADD SCREENSHOT
// end::open-project-properties-menu[]
//