= Anypoint Code Builder Overview
:page-aliases: ui-help.adoc

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]


//intro
Use the Anypoint Code Builder integrated development environment (IDE) for your API designs, implementations, and integration development. Work locally with Anypoint Code Builder on Microsoft Visual Studio Code (VS Code). The IDE supports the development lifecycle:

* API specification design, a mocking service for testing, source control, and publication to Anypoint Exchange
* API implementation features for importing supported API specifications (such as OAS, RAML, AsyncAPI, or GraphQL) and autogenerating interfaces (scaffolding) for flows and error handlers within a Mule application
* Integration development to connect systems, transform data to required formats, and provide business logic to manage messages and events programmatically within a Mule application

You can share project snapshots with members of your team by using import and export features or by using a <<scm, source control management (SCM) system>> of your choice.

For an introduction to Anypoint Code Builder, see our Trailhead badge, https://trailhead.salesforce.com/content/learn/modules/mulesoft-anypoint-code-builder-quick-look[Anypoint Code Builder: Quick Look^] (login required). Sign up if you don't have a Trailhead account.

//extensions info
[[extension-pack]]
== Anypoint Extension Pack

Get the Anypoint Code Builder experience through the Anypoint Extension Pack for Visual Studio Code. The extensions require installation to your VS Code IDE. See xref:start-acb.adoc[].

[[us-eu-clouds]]
== Cloud Hosts

Anypoint Code Builder is available through Anypoint Platform from US, EU, Canada, Japan, India, and Australia cloud hosts. To help your organization meet emerging regulatory requirements that differ by region, Anypoint Platform does not share organization information, permissions, account data, or projects between hosts.

[%header,cols="1,1,2"]
|===
|Control Plane |Platform URL |Description

|US Cloud
|https://anypoint.mulesoft.com/login/[anypoint.mulesoft.com^]
|Non-EU region host. MuleSoft hosts this control plane within data centers in the United States.

|EU Cloud
|https://eu1.anypoint.mulesoft.com/login[eu1.anypoint.mulesoft.com^]
|EU-compliant host. MuleSoft hosts this control plane within EU (Frankfurt) data centers.

|Canada Cloud
|https://ca1.platform.mulesoft.com/login/[ca1.platform.mulesoft.com^]
|MuleSoft hosts this control plane within Canada (North America) data centers.

|Japan Cloud
|https://jp1.platform.mulesoft.com/login/[jp1.platform.mulesoft.com^]
|MuleSoft hosts this control plane within Japan (APAC) data centers.

|India Cloud
|https://in1.platform.mulesoft.com/login/[in1.platform.mulesoft.com^]
|MuleSoft hosts this control plane within India (APAC) data centers.

|Australia Cloud
|https://au1.platform.mulesoft.com/login/[au1.platform.mulesoft.com^]
|MuleSoft hosts this control plane within Australia (APAC) data centers.
|===

Anypoint Platform hosts deployment targets for managed Mule runtime versions and related data, including data and metadata about your Mule implementations.

To change the host from the default (US), see xref:start-acb.adoc#change-clouds[Set Anypoint Code Builder to a Different Control Plane].

Use of Anypoint Code Builder requires an Anypoint Platform user account. Use of some features requires permissions set by an organization administrator (see xref:start-configure-permissions.adoc[]).

If you do not have an Anypoint Platform account through your organization, you can sign up in the US or EU cloud host for Anypoint Platform.

See xref:hosting-home::index.adoc[] for more information.

== Get Familiar with the Basics

Some knowledge about designing an API using API specification languages (such as OAS, RAML, AsyncAPI, or gRPC) can be helpful. API implementations and integration development require familiarity with Mule application development, connectors, and the DataWeave transformation language. Anypoint Code Builder xref:tutorials.adoc[] help you get started with these tasks.

It's also useful to be familiar with these products and features:

* Anypoint Connectors provide operations for retrieving, modifying, and sending data to and from systems. Anypoint Code Builder provides xref:acb-reference.adoc#builtin-connectors[built-in connectors] and access to many other connectors from Anypoint Exchange.

* Core processors (also called Core components or Mule components) are programmatic building blocks that provide the business logic for integration and implementation applications. Examples include For Each (`<foreach/>`), Transform Message (`<ee:transform/>`), and Flow (`<flow/>`). See xref:acb-reference.adoc[].

* DataWeave is the programming language for all expressions and data transformations in your integrations and implementations. The language offers function libraries and mechanisms for creating customizations, including your own functions, libraries, and data types. To learn the basics of DataWeave and experiment with DataWeave scripts, see https://dataweave.mulesoft.com/[DataWeave Tutorial and Playground^].

* Scaffolding is an automatic process that uses APIkit to take an API specification as input and autogenerate an XML-based router and endpoints that you implement within a Mule application.

* A flow is a block of components, including any connector operations, that Mule runtime engine (Mule) executes sequentially on an event and the message it contains. A flow can also contain an operation that triggers the creation of the event and initiates the execution of the flow.
+
A subflow is similar to a flow but does not support the configuration of triggers (sometimes called message sources), which are exclusive to flows.
+
A flow reference enables you to trigger execution of a flow or subflow from another flow.

* A Mule application contains one or more XML-based configuration files for your connectors, components, secure configuration properties, scaffolded API specifications, and other parts of your integrations and implementations. The application runs on Mule and is part of a project that contains the resources needed to configure, build, run, test, and deploy the application.

//Mule application development requires some understanding of the Mule message model, predefined Mule variables (`payload`, `attributes`, `vars`, `errors`), and execution of the Mule event within Mule flows.
//TODO: POINT TO helpful areas of the Mule docs (below)

[[business-groups]]
* Business groups organize APIs, Mule applications, and other resources within an Anypoint Platform organization. Organization administrators create and control access to business groups. For details about business groups, organizations, and related management features, see xref:access-management::business-groups.adoc[].

== Anypoint Platform Product Integrations

//relationships to our other products
Anypoint Code Builder integrates with key Anypoint Platform products and features:

* Anypoint Exchange for publishing the API specifications that you create and importing API specifications and development resources (such as connectors, integration project templates and examples) into your projects
* CloudHub and CloudHub 2.0 for deploying the implementations and integrations that you build
* MuleSoft VCS for importing API specification projects into Anypoint Code Builder and optionally, synchronizing imported projects by using the Anypoint source control management (SCM) system

The use of features provided by Anypoint Platform products requires a connection. You establish this connection by logging in to your Anypoint Platform account from Anypoint Code Builder. For more information, see xref:start-acb.adoc#login-ide[Sign in to Anypoint Platform from Anypoint Code Builder].

[[scm]]
== Source and Version Control

Use any supported source control management (SCM) system. VS Code supports Git out-of-the-box in addition to several extensions for popular version control and SCM systems.

For guidance with Git setup in Anypoint Code Builder, see xref:start-scm.adoc[].

See VS Code documentation on https://code.visualstudio.com/docs/sourcecontrol/overview[Git support^] and https://code.visualstudio.com/docs/sourcecontrol/overview#_scm-providers[extensions for other SCM providers^]. For extension authors only, VS Code also provides a https://code.visualstudio.com/api/extension-guides/scm-provider[VS Code source control API^].

[[acb-startup]]
== Anypoint Code Builder Startup

Anypoint Code Builder optimizes Maven bookkeeping and bundle-loading operations during initialization. This behavior reduces startup overhead so workspaces can become available with less wait time.

It also reads extension bundle directories directly from the extension path when loading workspace assets. This initialization path reduces delays before projects are ready for development tasks.

== Feedback

To provide feedback about Anypoint Code Builder, complete the https://www.surveymonkey.com/r/acb_feedback[feedback survey^].

For questions or general discussion about Anypoint Code Builder, see https://trailhead.salesforce.com/trailblazer-community/topics/mulesoftanypointcodebuilder?sort=LAST_MODIFIED_DATE_DESC[Trailblazer Discussion Topic^].

== See Also

* xref:access-management::index.adoc[]
* xref:exchange::index.adoc[]
* xref:connectors::index.adoc[]
* xref:dataweave::index.adoc[]
* xref:mule-runtime::index.adoc[]
//* xref:design-center::index.adoc[]
//* xref:studio::index.adoc[]
//* xref:configure-permissions.adoc[Configure Permissions]
//* xref:load-acb-web-ide.adoc[Load Anypoint Code Builder]
