= Importing Projects into Anypoint Code Builder
:page-aliases: upload-a-project.adoc[]

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]


Import a project JAR file or folder into a workspace in your IDE.
A project directory contains a Mule application for an integration or implementation.

You can also import a Maven multi-module project and apply the properties, dependencies, and versions from a Maven parent POM file to the `pom.xml` file of each child module. For more information about the Maven parent POM file, see https://maven.apache.org/pom/maven/index.html[Maven Project Parent POM].

If you encounter an import issue, check for workarounds in xref:acb-release-notes.adoc#import-issues[Known Issues] in the Anypoint Code Builder Release Notes or in xref:troubleshooting.adoc[].

To _export_ a JAR file that packages a project with resources from your application, see xref:int-export-mule-project.adoc[].

== Before You Begin

* xref:start-acb.adoc[Set up and access the IDE].
* Close any open project in your IDE.
+
--
// Pointer to Close Project
include::partial$acb-reusable-steps.adoc[tags="close-project"]
--
+
IMPORTANT: Never open or unpack a project folder within another project folder.

//H2: DESKTOP
[[import-desktop]]
== Import and Open a Project in Anypoint Code Builder

Use Anypoint Code Builder to upload a project directory or shareable JAR file into a project workspace.

* <<desktop-project-package>>
* <<desktop-project-folder>>
* <<both-open-project-folder>>


[[desktop-project-package]]
=== Import a Shareable Project JAR File into Anypoint Code Builder

Import a shareable JAR file for a snapshot of a Mule project into Anypoint Code Builder.

To create a shareable JAR, see xref:int-export-mule-project.adoc#export-mule-project[Export Mule Project].
The contents are lightweight because they don't include dependencies.
The IDE generates the dependencies configured in the `pom.xml` for the project. 

To import a shareable JAR file in Anypoint Code Builder:

. Ensure that no project is open in the IDE.
// include for this procedure
include::partial$acb-open-packaged-sources.adoc[tags="open-command-palette-desktop"]
include::partial$acb-open-packaged-sources.adoc[tags="load-shareable-jar"]
. If your Mule project folder is closed, <<both-open-project-folder, open a workspace>> for the project at the project's _root_ directory.
+
include::partial$acb-open-packaged-sources.adoc[tags="import-note"]
//step: test project
include::partial$acb-open-packaged-sources.adoc[tags="test-project"]


[[desktop-project-folder]]
=== Import a Project Folder into Anypoint Code Builder

Although it is more common to import a shareable JAR file or to open a project workspace from file directory, you can also drag a Mule project folder into the Explorer view and open the project in a VS Code workspace.

Open any valid project folder, including a project from Anypoint Studio (Studio) that's stored on your desktop. Alternatively, use the procedure in <<both-open-project-folder>> to open the project from your file directory instead of dragging and dropping the folder into the IDE.

To import a project folder into Anypoint Code Builder:

. Ensure that no project is open in the IDE.
include::partial$acb-open-packaged-sources.adoc[tags="import-project-folder-desktop"]
. If your Mule project folder is closed, <<both-open-project-folder, open a workspace>> for the project at the project's _root_ directory.
+
include::partial$acb-open-packaged-sources.adoc[tags="import-note"]
//step: if prompted, set version
include::partial$acb-reusable-steps.adoc[tags="set-version-prompted"]
//step: test project
include::partial$acb-open-packaged-sources.adoc[tags="test-project"]

[[both-open-project-folder]]
== Open a Project Folder

Open or reopen a project workspace folder for your application. This procedure works for projects built in Anypoint Code Builder and for projects stored on your desktop that are built in Anypoint Studio (Studio).

// include for this procedure
include::partial$acb-open-packaged-sources.adoc[tags="open-workspace-root"]
include::partial$acb-open-packaged-sources.adoc[tags="load-project"]
//step: test project
include::partial$acb-open-packaged-sources.adoc[tags="test-project"]

== See Also

* xref:start-workspaces.adoc[]
* xref:int-export-mule-project.adoc[]
