= MuleSoft Settings

include::reuse::partial$beta-banner.adoc[tag="anypoint-code-builder"]


Anypoint Code Builder provides configurable settings that apply across all your Anypoint Code Builder projects. Many of the default settings are suitable for most users. However, if you use the EU cloud, it is important to change the default US cloud setting.

To open the settings: 

//shared steps for opening Mule settings
include::partial$acb-reusable-steps.adoc[tags="open-mule-settings"]
include::partial$acb-reusable-steps.adoc[tags="mule-settings-nav-options"]

For information about specific Mule settings, see the sections that follow.

////
HIDING EINSTEIN SECTION: NOT FOR FEB RELEASE
[[setting-einstein]]
==  Mule > Application: Einstein

If an organization administrator set permissions for you to access and use Einstein AI features, you can disable or enable (default) the feature. When you disable Einstein, the UI no longer displays AI features.

For access to Einstein, see start-configure-permissions.adoc[].
////

[[setting-default-runtime-java]]
== Mule › Application: Default Mule Runtime And Java Versions

Set a default Mule runtime engine and Java version for new Mule projects (integrations and implementations) by clicking the link *Edit defaults through command palette*.  


[[setting-group-id]]
== Mule › Application: Group ID

Set the Maven group ID value for Anypoint Code Builder to use when you create a Mule integration or implementation project. This setting populates the `pom.xml` file for each Mule project. The default is `com.mycompany`, for example, `<groupId>com.mycompany</groupId>` in the `pom.xml`. You can change the setting within your project, as needed.

For information about Maven group IDs, see https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Introduction to the POM^] in the Apache Maven Project documentation. 

[[setting-logging]]
==  Mule > Logging: Level

Set the verbosity of logs that appear in the Anypoint Code Builder extension, Mule DX Server, and Mule DX Server: Scaffolding logs. Verbosity options are progressive:

* Off: No issues 
* Fatal: Fatal issues only
* Error: Fatal and Error issues 
* Warn (default): Fatal, Error, and Warn issues  
* Info: Fatal, Error, Warn, and Info issues 
* Debug: Fatal, Error, Warn, Info, and Debug issues
* Trace: Fatal, Error, Warn, Info, Debug, and Trace issues

[[setting-lsp]]
== Mule › Lsp › Trace: Server

You can enable and control the verbosity of `LogTrace` notifications to VS Code from the `muleLanguageServerProtocol` service. 

Available settings: 

* *off* (default)
* *messages*
* *verbose* 

[[setting-mule-args]]
== Mule › Runtime: Default Arguments

Set default command-line arguments to use when starting Mule Runtime engine (Mule). Mule starts when you run a Mule application in an integration or implementation project.

Common uses of this setting are to:

* Append an encryption key value (such as `-M-Dencryption.key=my-key`) when running a local deployment that incorporates secure configuration properties
* Set a variable (such as `-M-Denv=dev`) that Mule uses when selecting a configuration properties file by its file name
* Increase the JVM heap size (such as `-M-Xmx2g`) when running memory-intensive Mule applications locally

To set the maximum JVM heap size to 2 GB, add the following argument:

[source,text]
----
-M-Xmx2g
----

To also set the initial heap size:

[source,text]
----
-M-Xms512m -M-Xmx2g
----

For more information about passing properties and arguments when running Mule applications, including examples, use cases, and troubleshooting, see xref:int-run-mule-apps-with-properties.adoc[].
For information about secure configuration properties, see xref:int-create-secure-configs.adoc[]. 

[[setting-metaspace]]
== Mule › Runtime: Default Metaspace Size

Metaspace is an area for non-heap memory used to store class metadata, constant pool information, and method bytecode.

Typically, the default of *1g* (1 GB) is sufficient. However, you can change the metaspace size when installing Mule Runtime engine (Mule).
//TODO: WHEN INSTALLING MULE FOR THE FIRST TIME ONLY, OR WHAT ABOUT WHEN UPDATING?

[[setting-region]]
== Mule: Control Plane

Select a control plane for Anypoint Code Builder:

* *US Cloud* (default)
* *EU Cloud*

For more information, see xref:index.adoc#us-eu-clouds[US and EU Cloud Hosts].

[[setting-telemetry]]
==  Mule > Telemetry

You can enable or disable telemetry services in the US cloud. By default, this setting is disabled and not used for the EU cloud. When telemetry services are enabled, Anypoint Code Builder sends anonymous usage data to the MuleSoft team. The data helps identify important usage trends.

[[setting-home-dir]]
==  Mule: Home Directory

Set a home directory for downloaded assets, which include Mule runtime (`runtime/`) and Java (`java/`) versions for your implementations and integrations.


[[setting-auto-complete]]
==  Mule > Editor > Auto-completion: Enablement

Enable auto-completion suggestions in the API design editor in Anypoint Code Builder. This setting prevents the need to press Ctrl+Space to activate a list of suggestions and is disabled by default. See also <<setting-auto-complete-debouncer>>.

[[setting-auto-complete-debouncer]]
==  Mule > Editor > Auto-completion: Trigger Delay

Set the time in milliseconds to wait before displaying auto-completion options. This setting defaults to 1500 milliseconds. See also <<setting-auto-complete>>.

Avoid setting a long delay. If you activate the auto-completion menu but initiate other actions in your project before the delay period ends, Anypoint Code Builder automatically returns focus to the editor and opens the menu where you activated auto-completion. Such actions include opening the command palette or using the command terminal after activating the menu.

If you move your cursor to a new location or use the up or down arrow keys in the editor before the trigger delay expires, the request to open the auto-completion menu is cancelled.

[[setting-fips-enabled]]
== Mule > Runtime: Fips Enabled

Enable FIPS compliance mode for your Mule applications. When enabled, the embedded JVM uses Bouncy Castle FIPS (BCFIPS) modules for all cryptographic operations. Required for regulated PCE and GIA2H environments.

Enabling this setting automatically configures BCFIPS libraries, generates a custom `java.security` file, creates a BCFKS-format keystore, and updates each Mule application run configuration with the required FIPS parameters.

For more information, see xref:start-fips-compliance.adoc[].

[[setting-fips-mode]]
== Mule > Runtime: Fips Mode

Select the FIPS compliance level. This setting only applies when <<setting-fips-enabled, Fips Enabled>> is selected.

Available options:

* *FIPS 140-2*
* *FIPS 140-3*

For more information, see xref:start-fips-compliance.adoc[].

[[setting-fips-cacerts-path]]
== Mule > Runtime: Fips Custom Cacerts Path

Optional path to a custom `cacerts` file. If not specified, the default `cacerts` from the JDK is used. When FIPS mode is enabled, this file is automatically converted to BCFKS format.

For more information, see xref:start-fips-compliance.adoc[].
